export interface Country {
    value: string;
    label: string;
}

export const getCountries = (): Country[] => {
    return [
        { value: 'Magyarország', label: 'Magyarország' },
        { value: 'Németország', label: 'Németország' },
        { value: 'Ausztria', label: 'Ausztria' },
        { value: 'Franciaország', label: 'Franciaország' },
        { value: 'Olaszország', label: 'Olaszország' },
        { value: 'Spanyolország', label: 'Spanyolország' },
        { value: 'Hollandia', label: 'Hollandia' },
        { value: 'Belgium', label: 'Belgium' },
        { value: 'Luxemburg', label: 'Luxemburg' },
        { value: 'Finnország', label: 'Finnország' },
        { value: 'Svédország', label: 'Svédország' },
        { value: 'Dánia', label: 'Dánia' },
        { value: 'Norvégia', label: 'Norvégia' },
        { value: 'Svájc', label: 'Svájc' },
        { value: 'Lichtenstein', label: 'Lichtenstein' },
        { value: 'Csehország', label: 'Csehország' },
        { value: 'Szlovákia', label: 'Szlovákia' },
        { value: 'Szlovénia', label: 'Szlovénia' },
        { value: 'Horvátország', label: 'Horvátország' },
        { value: 'Románia', label: 'Románia' },
        { value: 'Bulgária', label: 'Bulgária' },
        { value: 'Lengyelország', label: 'Lengyelország' },
        { value: 'Észtország', label: 'Észtország' },
        { value: 'Lettország', label: 'Lettország' },
        { value: 'Litvánia', label: 'Litvánia' },
        { value: 'Egyesült Királyság', label: 'Egyesült Királyság' },
        { value: 'Írország', label: 'Írország' },
        { value: 'Portugália', label: 'Portugália' },
        { value: 'Görögország', label: 'Görögország' },
        { value: 'Ciprus', label: 'Ciprus' },
        { value: 'Málta', label: 'Málta' },
        { value: 'Egyesült Államok', label: 'Egyesült Államok' },
        { value: 'Kanada', label: 'Kanada' },
        { value: 'Japán', label: 'Japán' },
        { value: 'Kína', label: 'Kína' },
        { value: 'India', label: 'India' },
        { value: 'Brazília', label: 'Brazília' },
        { value: 'Ausztrália', label: 'Ausztrália' },
        { value: 'Új-Zéland', label: 'Új-Zéland' },
        { value: 'Dél-Korea', label: 'Dél-Korea' },
        { value: 'Szingapúr', label: 'Szingapúr' },
        { value: 'Hong Kong', label: 'Hong Kong' },
        { value: 'Tajvan', label: 'Tajvan' },
        { value: 'Thaiföld', label: 'Thaiföld' },
        { value: 'Malajzia', label: 'Malajzia' },
        { value: 'Indonézia', label: 'Indonézia' },
        { value: 'Fülöp-szigetek', label: 'Fülöp-szigetek' },
        { value: 'Vietnam', label: 'Vietnam' },
        { value: 'Törökország', label: 'Törökország' },
        { value: 'Izrael', label: 'Izrael' },
        { value: 'Egyesült Arab Emírségek', label: 'Egyesült Arab Emírségek' },
        { value: 'Szaúd-Arábia', label: 'Szaúd-Arábia' },
        { value: 'Dél-afrikai Köztársaság', label: 'Dél-afrikai Köztársaság' },
        { value: 'Egyiptom', label: 'Egyiptom' },
        { value: 'Marokkó', label: 'Marokkó' },
        { value: 'Tunézia', label: 'Tunézia' },
        { value: 'Algéria', label: 'Algéria' },
        { value: 'Libia', label: 'Libia' },
        { value: 'Etiópia', label: 'Etiópia' },
        { value: 'Kenya', label: 'Kenya' },
        { value: 'Nigéria', label: 'Nigéria' },
        { value: 'Ghána', label: 'Ghána' },
        { value: 'Egyéb', label: 'Egyéb' }
    ];
};
