# Generated by Django 4.2.7 on 2026-09-20 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0073_postransaction_storno_fields'),
        ('pos', '0002_posterminal_warehouses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0040_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_grade_id', models.PositiveSmallIntegerField(help_text='A PTS-2 vezérlőben beállított üzemanyag azonosító (1-20).', unique=True, verbose_name='Fuel Grade ID')),
                ('name', models.CharField(help_text='Pl. Benzin 95, Gázolaj, LPG', max_length=100, verbose_name='Név')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, help_text='A hozzárendelt raktári termék (benzinkút raktárból vételezett tétel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_grades', to='warehouse.material', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Üzemanyag fajta',
                'verbose_name_plural': 'Üzemanyag fajták',
                'db_table': 'fuel_grades',
                'ordering': ['fuel_grade_id'],
            },
        ),
        migrations.CreateModel(
            name='FuelPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_id', models.PositiveSmallIntegerField(help_text='A PTS-2 vezérlőben beállított logikai kút azonosító (1-100).', unique=True, verbose_name='Kút száma')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Név')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kútfej',
                'verbose_name_plural': 'Kútfejek',
                'db_table': 'fuel_pumps',
                'ordering': ['pump_id'],
            },
        ),
        migrations.CreateModel(
            name='FuelStationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Modul engedélyezve')),
                ('controller_url', models.CharField(default='http://192.168.1.117', help_text='Pl. http://192.168.1.117 vagy https://192.168.1.117 (DIP-1 OFF esetén HTTPS)', max_length=255, verbose_name='PTS-2 vezérlő címe')),
                ('auth_type', models.CharField(choices=[('digest', 'Digest autentikáció (DIP-2 OFF)'), ('basic', 'Basic autentikáció (DIP-2 ON)')], default='digest', max_length=10, verbose_name='Autentikáció típusa')),
                ('username', models.CharField(default='admin', max_length=50, verbose_name='Felhasználónév')),
                ('password', models.CharField(default='admin', max_length=50, verbose_name='Jelszó')),
                ('request_timeout', models.PositiveSmallIntegerField(default=5, help_text='Ennyi másodpercig várja a PTS-2 vezérlő válaszát egy kérésnél.', verbose_name='Kérés időkorlát (mp)')),
                ('poll_interval', models.PositiveSmallIntegerField(default=2, help_text='A kassza képernyő ekkora időközzel kérdezi le a kútfejek állapotát.', verbose_name='Kútállapot lekérdezés gyakorisága (mp)')),
                ('auto_sync_prices', models.BooleanField(default=True, help_text='A termék bruttó árából számolt kútár automatikusan felkerül a PTS-2 vezérlőre.', verbose_name='Árak automatikus szinkronizálása')),
                ('auto_close_transaction', models.BooleanField(default=True, help_text='Fizetés után a kút tranzakciója automatikusan lezárásra (nullázásra) kerül a vezérlőben.', verbose_name='Tranzakció automatikus lezárása')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_warehouse', models.ForeignKey(blank=True, help_text='Ebből a raktárból kerül levonásra az eladott üzemanyag mennyisége.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_station_config', to='warehouse.warehouse', verbose_name='Üzemanyag raktár')),
            ],
            options={
                'verbose_name': 'Benzinkút modul beállítás',
                'verbose_name_plural': 'Benzinkút modul beállítások',
                'db_table': 'fuel_station_config',
            },
        ),
        migrations.CreateModel(
            name='FuelSaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nozzle_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Síp')),
                ('pts_transaction_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='PTS tranzakciószám')),
                ('state', models.CharField(choices=[('authorized', 'Engedélyezve'), ('filling', 'Töltés folyamatban'), ('end_of_transaction', 'Töltés befejezve'), ('paid', 'Kifizetve'), ('cancelled', 'Törölve')], db_index=True, default='authorized', max_length=30, verbose_name='Állapot')),
                ('source', models.CharField(choices=[('pos', 'POS indítású'), ('auto', 'Automatikusan átvett / kézi kútüzem')], default='pos', max_length=10, verbose_name='Eredet')),
                ('volume', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Mennyiség (liter)')),
                ('unit_price', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Egységár (bruttó)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Összeg (bruttó)')),
                ('is_test', models.BooleanField(default=False, verbose_name='Teszt/kalibrációs töltés')),
                ('stock_deducted', models.BooleanField(default=False, verbose_name='Készletlevonás megtörtént')),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='Utolsó PTS állapot válasz')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Töltés kezdete')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Töltés vége')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kútzárás (nullázás) időpontja')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fizetés időpontja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kasszás')),
                ('fuel_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuel.fuelgrade', verbose_name='Üzemanyag fajta')),
                ('pos_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transaction', to='sales.postransaction', verbose_name='POS bizonylat')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_transactions', to='fuel.fuelpump', verbose_name='Kútfej')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.posterminal', verbose_name='POS terminál')),
            ],
            options={
                'verbose_name': 'Kút tranzakció',
                'verbose_name_plural': 'Kút tranzakciók',
                'db_table': 'fuel_sale_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelPumpTotalsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nozzle_number', models.PositiveSmallIntegerField(verbose_name='Síp')),
                ('volume_total', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Ömlési óra (liter)')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Pénz óra')),
                ('source', models.CharField(choices=[('pump_totals', 'Kútból kiolvasva (PumpGetTotals)'), ('last_saved', 'Vezérlő memóriából (PumpGetLastSavedTotals)')], max_length=20, verbose_name='Forrás')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiolvashoz idő')),
                ('fuel_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuel.fuelgrade', verbose_name='Üzemanyag fajta')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='totals_logs', to='fuel.fuelpump', verbose_name='Kútfej')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Olvasta')),
            ],
            options={
                'verbose_name': 'Kútóra kiolvasás',
                'verbose_name_plural': 'Kútóra kiolvasások',
                'db_table': 'fuel_pump_totals_logs',
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelPumpNozzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nozzle_number', models.PositiveSmallIntegerField(verbose_name='Síp száma')),
                ('fuel_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nozzles', to='fuel.fuelgrade', verbose_name='Üzemanyag fajta')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzles', to='fuel.fuelpump', verbose_name='Kútfej')),
            ],
            options={
                'verbose_name': 'Kútsíp',
                'verbose_name_plural': 'Kútsípok',
                'db_table': 'fuel_pump_nozzles',
                'ordering': ['pump', 'nozzle_number'],
                'unique_together': {('pump', 'nozzle_number')},
            },
        ),
    ]
