# Generated by Django 4.2.7 on 2026-09-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelpumpnozzle',
            options={'ordering': ['pump', 'nozzle_number'], 'verbose_name': 'Kútpisztoly', 'verbose_name_plural': 'Kútpisztolyok'},
        ),
        migrations.AlterField(
            model_name='fuelpumpnozzle',
            name='nozzle_number',
            field=models.PositiveSmallIntegerField(verbose_name='Pisztoly száma'),
        ),
        migrations.AlterField(
            model_name='fuelpumptotalslog',
            name='nozzle_number',
            field=models.PositiveSmallIntegerField(verbose_name='Pisztoly'),
        ),
        migrations.AlterField(
            model_name='fuelsaletransaction',
            name='nozzle_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pisztoly'),
        ),
    ]
