# Generated by Django 4.2.7 on 2026-09-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_alter_fuelpumpnozzle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelsaletransaction',
            name='state',
            field=models.CharField(choices=[('authorized', 'Engedélyezve'), ('filling', 'Töltés folyamatban'), ('end_of_transaction', 'Töltés befejezve'), ('paid', 'Kifizetve'), ('rebill', 'Újrakibizonylatolandó (sztnó után)'), ('cancelled', 'Törölve')], db_index=True, default='authorized', max_length=30, verbose_name='Állapot'),
        ),
    ]
