# Generated by Django 4.2.7 on 2026-09-20 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0041_alter_materialcostitem_calculation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0003_posterminal_fuel_module_enabled_and_more'),
        ('fuel', '0003_alter_fuelsaletransaction_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Műszak sorszáma')),
                ('status', models.CharField(choices=[('open', 'Nyitott'), ('closed', 'Zárva')], default='open', max_length=10, verbose_name='Állapot')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nyitás időpontja')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Zárás időpontja')),
                ('summary', models.JSONField(blank=True, null=True, verbose_name='Zárási összesítés')),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Számolt készpénz')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Megjegyzés')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='fuel_shifts/', verbose_name='Jegyzőkönyv PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_shifts_closed', to=settings.AUTH_USER_MODEL, verbose_name='Zárta')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_shifts_opened', to=settings.AUTH_USER_MODEL, verbose_name='Nyitotta')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_shifts', to='pos.posterminal', verbose_name='Kassza terminál')),
            ],
            options={
                'verbose_name': 'Üzemanyag műszak',
                'verbose_name_plural': 'Üzemanyag műszakok',
                'db_table': 'fuel_shifts',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelShiftTankReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Nyitó tartály készlet (liter)')),
                ('received', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Bevételezés (liter)')),
                ('dispensed', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Készletcsökkenés – kútóra elmozdulás (liter)')),
                ('calculated_closing', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Számított záró készlet (liter)')),
                ('measured_closing', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Mért (tényleges) záró készlet (liter)')),
                ('difference', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Eltérés (mért – számított)')),
                ('fuel_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuel.fuelgrade', verbose_name='Üzemanyag fajta')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.material', verbose_name='Termék (denormalizált)')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_readings', to='fuel.fuelshift', verbose_name='Műszak')),
            ],
            options={
                'verbose_name': 'Műszak tartály bejegyzés',
                'verbose_name_plural': 'Műszak tartály bejegyzések',
                'db_table': 'fuel_shift_tank_readings',
                'ordering': ['fuel_grade__fuel_grade_id'],
                'unique_together': {('shift', 'fuel_grade')},
            },
        ),
        migrations.CreateModel(
            name='FuelShiftNozzleReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nozzle_number', models.PositiveSmallIntegerField(verbose_name='Pisztoly')),
                ('opening_total', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Nyitó óraállás (liter)')),
                ('closing_total', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Záró óraállás (liter)')),
                ('closing_source', models.CharField(choices=[('auto', 'Kiolvasva'), ('manual', 'Kézi')], default='manual', max_length=10, verbose_name='Záró állás forrása')),
                ('fuel_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuel.fuelgrade', verbose_name='Üzemanyag fajta')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuel.fuelpump', verbose_name='Kútfej')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzle_readings', to='fuel.fuelshift', verbose_name='Műszak')),
            ],
            options={
                'verbose_name': 'Műszak kútóra bejegyzés',
                'verbose_name_plural': 'Műszak kútóra bejegyzések',
                'db_table': 'fuel_shift_nozzle_readings',
                'ordering': ['pump__pump_id', 'nozzle_number'],
                'unique_together': {('shift', 'pump', 'nozzle_number')},
            },
        ),
    ]
