# Generated by Django 4.2.7 on 2025-09-07 21:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_company_company_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Alapanyag neve')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kód')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('unit', models.CharField(default='db', max_length=20, verbose_name='Mértékegység')),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum készletszint')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
            ],
            options={
                'verbose_name': 'Alapanyag',
                'verbose_name_plural': 'Alapanyagok',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Típus neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
            ],
            options={
                'verbose_name': 'Alapanyag típus',
                'verbose_name_plural': 'Alapanyag típusok',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Raktár neve')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kód')),
                ('address', models.TextField(verbose_name='Cím')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
            ],
            options={
                'verbose_name': 'Raktár',
                'verbose_name_plural': 'Raktárak',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Polc neve')),
                ('code', models.CharField(max_length=20, verbose_name='Kód')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Raktár')),
            ],
            options={
                'verbose_name': 'Polc',
                'verbose_name_plural': 'Polcok',
                'ordering': ['warehouse', 'name'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='MaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Bevételezési szám')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mennyiség')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységár')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Összes ár')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('status', models.CharField(choices=[('pending', 'Függőben'), ('received', 'Bevételezve'), ('cancelled', 'Törölve')], default='pending', max_length=20, verbose_name='Státusz')),
                ('receipt_date', models.DateTimeField(verbose_name='Bevételezés dátuma')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.material', verbose_name='Alapanyag')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.shelf', verbose_name='Polc')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company', verbose_name='Beszállító')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Raktár')),
            ],
            options={
                'verbose_name': 'Alapanyag bevételezés',
                'verbose_name_plural': 'Alapanyag bevételezések',
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.materialtype', verbose_name='Típus'),
        ),
        migrations.CreateModel(
            name='MaterialSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, max_length=50, verbose_name='Beszállító kód')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységár')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Elsődleges beszállító')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.material', verbose_name='Alapanyag')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company', verbose_name='Beszállító')),
            ],
            options={
                'verbose_name': 'Alapanyag beszállító',
                'verbose_name_plural': 'Alapanyag beszállítók',
                'ordering': ['material', 'supplier'],
                'unique_together': {('material', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mennyiség')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Utolsó frissítés')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.material', verbose_name='Alapanyag')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.shelf', verbose_name='Polc')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Frissítette')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Raktár')),
            ],
            options={
                'verbose_name': 'Készlet',
                'verbose_name_plural': 'Készletek',
                'ordering': ['material', 'warehouse', 'shelf'],
                'unique_together': {('material', 'warehouse', 'shelf')},
            },
        ),
    ]
