# Generated by Django 4.2.7 on 2025-09-07 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fajsúly'),
        ),
        migrations.AddField(
            model_name='material',
            name='density_unit',
            field=models.CharField(choices=[('kg/m3', 'kg/m³'), ('g/cm3', 'g/cm³'), ('kg/liter', 'kg/liter')], default='kg/m3', max_length=10, verbose_name='Fajsúly mértékegység'),
        ),
        migrations.AddField(
            model_name='material',
            name='dimension_unit',
            field=models.CharField(choices=[('mm', 'mm'), ('cm', 'cm'), ('m', 'm')], default='mm', max_length=10, verbose_name='Méret mértékegység'),
        ),
        migrations.AddField(
            model_name='material',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Magasság'),
        ),
        migrations.AddField(
            model_name='material',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hosszúság'),
        ),
        migrations.AddField(
            model_name='material',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Szélesség'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('db', 'db'), ('m', 'm'), ('m2', 'm²'), ('m3', 'm³'), ('kg', 'kg'), ('liter', 'liter')], default='db', max_length=20, verbose_name='Mértékegység'),
        ),
    ]
