# Generated by Django 4.2.7 on 2026-01-03 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_material_density_material_density_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_format',
            field=models.CharField(choices=[('roll', 'Tekercses'), ('sheet', 'Táblás'), ('piece', 'Darabos'), ('bulk', 'Ömlesztett')], default='piece', max_length=20, verbose_name='Anyagformátum'),
        ),
        migrations.AddField(
            model_name='material',
            name='roll_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tekercses anyag szélessége (cm vagy m)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tekercs szélesség'),
        ),
        migrations.AddField(
            model_name='material',
            name='sheet_division',
            field=models.CharField(blank=True, choices=[('full', 'Csak egész tábla'), ('half', '1/2 és egész'), ('third', '1/3, 1/2 és egész')], help_text='Hogyan osztható a tábla', max_length=20, null=True, verbose_name='Tábla oszthatóság'),
        ),
        migrations.AddField(
            model_name='material',
            name='yield_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Hány százalék a tényleges kihozatal (pl. 85% = 15% hulló)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kihozatal %'),
        ),
    ]
