# Generated by Django 4.2.7 on 2026-01-03 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_material_material_format_material_roll_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='currency',
            field=models.CharField(default='HUF', max_length=3, verbose_name='Pénznem'),
        ),
        migrations.AddField(
            model_name='material',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Haszonkulcs százalékban', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Haszonkulcs %'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bekerülési ár mértékegységenként', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységár (bekerülési)'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Eladási ár mértékegységenként (számított vagy manuális)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységár (eladási)'),
        ),
    ]
