# Generated by Django 4.2.7 on 2026-01-03 19:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_company_company_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0007_materialcostitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mennyiség')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Szélesség')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hosszúság')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vastagság')),
                ('dimension_unit', models.CharField(default='mm', max_length=10, verbose_name='Méret mértékegység')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, help_text='Bevételezés szerinti egységár', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységérték')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='Mennyiség × egységérték', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Teljes érték')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('status', models.CharField(choices=[('normal', 'Normál'), ('defective', 'Hibás'), ('scrapped', 'Selejtezett')], default='normal', max_length=20, verbose_name='Státusz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
            ],
            options={
                'verbose_name': 'Készlet',
                'verbose_name_plural': 'Készletek',
                'ordering': ['material', 'warehouse', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('transfer', 'Mozgatás'), ('scrap', 'Selejtezés'), ('mark_defective', 'Hibásnak jelölés')], max_length=20, verbose_name='Művelet típusa')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mennyiség')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dátum')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Végrehajtotta')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_movements', to='warehouse.warehouse', verbose_name='Honnan')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouse.materialstock', verbose_name='Készlet')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='warehouse.warehouse', verbose_name='Hova')),
            ],
            options={
                'verbose_name': 'Készlet mozgás',
                'verbose_name_plural': 'Készlet mozgások',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='materialreceipt',
            options={'ordering': ['-receipt_date', '-created_at'], 'verbose_name': 'Bevételezés', 'verbose_name_plural': 'Bevételezések'},
        ),
        migrations.RemoveField(
            model_name='materialreceipt',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='materialreceipt',
            name='shelf',
        ),
        migrations.RemoveField(
            model_name='materialreceipt',
            name='status',
        ),
        migrations.RemoveField(
            model_name='materialreceipt',
            name='total_price',
        ),
        migrations.AddField(
            model_name='material',
            name='area_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Szélesség x hosszúság egységnyi súlya', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Terület súly'),
        ),
        migrations.AddField(
            model_name='material',
            name='area_weight_unit',
            field=models.CharField(choices=[('g/m2', 'g/m²'), ('kg/m2', 'kg/m²')], default='g/m2', max_length=10, verbose_name='Terület súly mértékegység'),
        ),
        migrations.AddField(
            model_name='material',
            name='specific_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Térfogat egységnyi súlya', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fajsúly'),
        ),
        migrations.AddField(
            model_name='material',
            name='specific_weight_unit',
            field=models.CharField(choices=[('kg/m3', 'kg/m³'), ('g/cm3', 'g/cm³'), ('kg/liter', 'kg/liter')], default='kg/m3', max_length=10, verbose_name='Fajsúly mértékegység'),
        ),
        migrations.AddField(
            model_name='material',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Teljes súly (számított vagy megadott)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Súly'),
        ),
        migrations.AddField(
            model_name='material',
            name='weight_unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('t', 't')], default='kg', max_length=10, verbose_name='Súly mértékegység'),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='dimension_unit',
            field=models.CharField(default='mm', max_length=10, verbose_name='Méret mértékegység'),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Számla szám'),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='invoice_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Számla érték'),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hosszúság'),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vastagság'),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Szélesség'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Rögzítve'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Rögzítette'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='warehouse.material', verbose_name='Alapanyag'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Megjegyzés'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mennyiség'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='receipt_date',
            field=models.DateField(verbose_name='Bevételezés dátuma'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'company_type': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_receipts', to='crm.company', verbose_name='Beszállító'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységár'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_receipts', to='warehouse.warehouse', verbose_name='Raktár'),
        ),
        migrations.DeleteModel(
            name='MaterialSupplierPrice',
        ),
        migrations.AddField(
            model_name='materialstock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.material', verbose_name='Alapanyag'),
        ),
        migrations.AddField(
            model_name='materialstock',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='warehouse.materialreceipt', verbose_name='Bevételezés'),
        ),
        migrations.AddField(
            model_name='materialstock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_stocks', to='warehouse.warehouse', verbose_name='Raktár'),
        ),
    ]
