# Generated by Django 4.2.7 on 2026-01-03 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_materialstock_stockmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='volume_liter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Liter alapú anyagok térfogata', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Térfogat (liter)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_format',
            field=models.CharField(choices=[('sheet', 'Táblás/Íves'), ('roll', 'Tekercses'), ('linear', 'Folyóméter alapú'), ('piece', 'Darab'), ('weight', 'Súly alapú'), ('liter', 'Liter alapú')], default='piece', max_length=20, verbose_name='Anyagformátum'),
        ),
    ]
