# Generated by Django 4.2.7 on 2026-01-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_material_volume_liter_alter_material_material_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='height_fixed',
            field=models.BooleanField(default=False, help_text='Ha be van kapcsolva, a magasság nem módosítható bevételezéskor', verbose_name='Magasság rögzített'),
        ),
        migrations.AddField(
            model_name='material',
            name='length_fixed',
            field=models.BooleanField(default=False, help_text='Ha be van kapcsolva, a hosszúság nem módosítható bevételezéskor', verbose_name='Hosszúság rögzített'),
        ),
        migrations.AddField(
            model_name='material',
            name='width_fixed',
            field=models.BooleanField(default=False, help_text='Ha be van kapcsolva, a szélesség nem módosítható bevételezéskor', verbose_name='Szélesség rögzített'),
        ),
    ]
