# Generated by Django 4.2.7 on 2026-01-03 21:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_company_company_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0010_material_height_fixed_material_length_fixed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True, verbose_name='Számla szám')),
                ('invoice_date', models.DateField(verbose_name='Számla kelte')),
                ('receipt_date', models.DateField(verbose_name='Bevételezés dátuma')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fizetési határidő')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fizetés dátuma')),
                ('payment_method', models.CharField(choices=[('cash', 'Készpénz'), ('transfer', 'Átutalás'), ('card', 'Bankkártya'), ('credit', 'Halasztott fizetés')], default='transfer', max_length=20, verbose_name='Fizetési mód')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Végösszeg')),
                ('status', models.CharField(choices=[('draft', 'Piszkozat'), ('confirmed', 'Megerősített'), ('received', 'Bevételezve'), ('paid', 'Kifizetve'), ('cancelled', 'Törölve')], default='draft', max_length=20, verbose_name='Státusz')),
                ('invoice_images', models.JSONField(blank=True, default=list, help_text='Számla kép fájlnevek JSON array formában', verbose_name='Számla képek')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Rögzítette')),
                ('supplier', models.ForeignKey(limit_choices_to={'company_type': 'supplier'}, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='crm.company', verbose_name='Beszállító')),
            ],
            options={
                'verbose_name': 'Beszállítói számla',
                'verbose_name_plural': 'Beszállítói számlák',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mennyiség')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységár')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Összesen')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Szélesség')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hosszúság')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vastagság')),
                ('dimension_unit', models.CharField(default='mm', max_length=10, verbose_name='Méret mértékegység')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.supplierinvoice', verbose_name='Számla')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='warehouse.material', verbose_name='Alapanyag')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='warehouse.warehouse', verbose_name='Raktár')),
            ],
            options={
                'verbose_name': 'Számla tétel',
                'verbose_name_plural': 'Számla tételek',
                'ordering': ['invoice', 'id'],
            },
        ),
    ]
