# Generated by Django 4.2.7 on 2026-01-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_supplierinvoice_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bevételezés dátuma'),
        ),
    ]
