# Generated by Django 4.2.7 on 2026-01-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_alter_supplierinvoice_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(default='db', help_text='pl. db, kg, m, m2, nm, l, stb.', max_length=20, verbose_name='Mennyiségi egység'),
        ),
        migrations.AddField(
            model_name='material',
            name='available_lengths',
            field=models.JSONField(blank=True, default=list, help_text='Opcionális hosszúságok JSON array formában', verbose_name='Elérhető hosszúságok'),
        ),
        migrations.AddField(
            model_name='material',
            name='available_thicknesses',
            field=models.JSONField(blank=True, default=list, help_text='Opcionális vastagságok JSON array formában', verbose_name='Elérhető vastagságok'),
        ),
        migrations.AddField(
            model_name='material',
            name='available_widths',
            field=models.JSONField(blank=True, default=list, help_text='Opcionális szélességek JSON array formában, pl. [100, 150, 200]', verbose_name='Elérhető szélességek'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='fulfillment_date',
            field=models.DateField(blank=True, help_text='A számlán feltüntetett teljesítési dátum', null=True, verbose_name='Teljesítési dátum (NAV)'),
        ),
    ]
