# Generated by Django 4.2.7 on 2026-01-03 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0013_invoiceitem_unit_material_available_lengths_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Gyűjtő neve')),
                ('description', models.TextField(blank=True, help_text='Opcionális leírás a gyűjtőről', verbose_name='Leírás')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_material_groups', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
            ],
            options={
                'verbose_name': 'Alapanyag gyűjtő',
                'verbose_name_plural': 'Alapanyag gyűjtők',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='material_group',
            field=models.ForeignKey(blank=True, help_text='Opcionális gyűjtő kategória (pl. Épületháló)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='warehouse.materialgroup', verbose_name='Alapanyag gyűjtő'),
        ),
    ]
