# Generated by Django 4.2.7 on 2026-01-03 23:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0014_materialgroup_material_material_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_date', models.DateField(verbose_name='Selejtezés dátuma')),
                ('scrap_number', models.CharField(help_text='Automatikusan generált egyedi azonosító', max_length=100, unique=True, verbose_name='Selejtezési szám')),
                ('reason', models.TextField(verbose_name='Selejtezés indoka')),
                ('images', models.JSONField(blank=True, default=list, help_text='Selejtezett termékekről készült fotók fájlnevei JSON array formában', verbose_name='Fotók')),
                ('total_cost_value', models.DecimalField(decimal_places=2, default=0, help_text='Selejtezett termékek bekerülési értéke', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Beszerzési érték összesen')),
                ('total_selling_value', models.DecimalField(decimal_places=2, default=0, help_text='Selejtezett termékek eladási értéke', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Eladási érték összesen')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('is_approved', models.BooleanField(default=False, help_text='Vezető vagy felelős jóváhagyta a selejtezést', verbose_name='Jóváhagyva')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Jóváhagyás dátuma')),
                ('notes', models.TextField(blank=True, verbose_name='Egyéb megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Rögzítve')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scraps', to=settings.AUTH_USER_MODEL, verbose_name='Jóváhagyta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scraps', to=settings.AUTH_USER_MODEL, verbose_name='Rögzítette')),
            ],
            options={
                'verbose_name': 'Selejtezési jegyzőkönyv',
                'verbose_name_plural': 'Selejtezési jegyzőkönyvek',
                'ordering': ['-scrap_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mennyiség')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Szélesség')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hosszúság')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vastagság')),
                ('dimension_unit', models.CharField(default='mm', max_length=10, verbose_name='Méret mértékegység')),
                ('unit_cost_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egység bekerülési érték')),
                ('unit_selling_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egység eladási érték')),
                ('total_cost_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Teljes bekerülési érték')),
                ('total_selling_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Teljes eladási érték')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_items', to='warehouse.material', verbose_name='Alapanyag')),
                ('scrap_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.scraprecord', verbose_name='Selejtezési jegyzőkönyv')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_items', to='warehouse.materialstock', verbose_name='Készlet')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_items', to='warehouse.warehouse', verbose_name='Raktár')),
            ],
            options={
                'verbose_name': 'Selejtezett tétel',
                'verbose_name_plural': 'Selejtezett tételek',
                'ordering': ['scrap_record', 'id'],
            },
        ),
    ]
