# Generated by Django 4.2.7 on 2026-01-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_scraprecord_scrapitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('material', 'Alapanyag'), ('product', 'Termék')], default='material', max_length=20, verbose_name='Kategória'),
        ),
    ]
