# Generated by Django 4.2.7 on 2026-01-04 00:56

from django.db import migrations, models
import django.db.models.deletion


def convert_category_to_flags(apps, schema_editor):
    """Konvertálja a category mezőt is_material és is_product flag-ekre"""
    Material = apps.get_model('warehouse', 'Material')
    
    # 'material' category -> is_material=True, is_product=False
    Material.objects.filter(category='material').update(is_material=True, is_product=False)
    
    # 'product' category -> is_material=False, is_product=True
    Material.objects.filter(category='product').update(is_material=False, is_product=True)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_company_company_type_company_is_customer_and_more'),
        ('warehouse', '0016_material_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_material',
            field=models.BooleanField(default=True, help_text='Gyártáshoz használható alapanyag', verbose_name='Alapanyag'),
        ),
        migrations.AddField(
            model_name='material',
            name='is_product',
            field=models.BooleanField(default=False, help_text='Értékesíthető termék', verbose_name='Termék'),
        ),
        migrations.RunPython(convert_category_to_flags, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
        migrations.AlterField(
            model_name='material',
            name='default_supplier',
            field=models.ForeignKey(blank=True, help_text='Ez a beszállító lesz használva a kalkulációban', limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_materials', to='crm.company', verbose_name='Alapértelmezett beszállító'),
        ),
        migrations.AlterField(
            model_name='materialcostitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Null = belső gyártás', limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_cost_items', to='crm.company', verbose_name='Beszállító'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_receipts', to='crm.company', verbose_name='Beszállító'),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='crm.company', verbose_name='Beszállító'),
        ),
    ]
