# Generated by Django 4.2.7 on 2026-01-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_materialsupplier_supplier_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='warehouse.materialgroup', verbose_name='Szülő kategória'),
        ),
    ]
