# Generated by Django 4.2.7 on 2026-02-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_materialgroup_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='vat_type_id',
            field=models.UUIDField(blank=True, help_text='Az alapértelmezett ÁFA osztály (PixInvoice VATType UUID)', null=True, verbose_name='ÁFA osztály'),
        ),
    ]
