# Generated by Django 4.2.7 on 2026-03-19 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_material_vat_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcostitem',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Haszon kulcs (%)'),
        ),
    ]
