# Generated by Django 4.2.7 on 2026-03-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_alter_materialcostitem_markup_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Opcionális elnevezés, pl. A4, A3', max_length=200, verbose_name='Megnevezés')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Szélesség')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hosszúság')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Magasság')),
                ('dimension_unit', models.CharField(choices=[('mm', 'mm'), ('cm', 'cm'), ('m', 'm')], default='mm', max_length=5, verbose_name='Mértékegység')),
                ('pricing_type', models.CharField(choices=[('custom', 'Egyedi'), ('area', 'Terület alapján'), ('weight', 'Súly alapján'), ('volume', 'Térfogat alapján')], default='custom', max_length=10, verbose_name='Ár típusa')),
                ('custom_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Egyedi ár')),
                ('calculated_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Számított ár')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='warehouse.material', verbose_name='Alapanyag')),
            ],
            options={
                'verbose_name': 'Rendelhető méret',
                'verbose_name_plural': 'Rendelhető méretek',
                'ordering': ['material', 'sort_order', 'width', 'length'],
            },
        ),
    ]
