# Generated by Django 4.2.7 on 2026-05-01 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_material_price_source_costitem_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialstock',
            name='used_length',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Felhasznált hosszúság'),
        ),
    ]
