# Generated by Django 4.2.7 on 2026-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_materialstock_add_used_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreceipt',
            name='stock_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Db szám'),
        ),
    ]
