# Generated by Django 4.2.7 on 2026-05-10 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0026_materialreceipt_add_stock_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRemnant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Szélesség (mm)')),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Táblás anyagnál kötelező', max_digits=10, null=True, verbose_name='Magasság (mm)')),
                ('length_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Tekercses anyagnál: maradék folyóméter mm-ben', max_digits=10, null=True, verbose_name='Hosszúság (mm)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Darabszám')),
                ('is_available', models.BooleanField(default=True, verbose_name='Elérhető')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Becsült érték (HUF/db)')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('source_job_ref', models.CharField(blank=True, help_text='pl. Megrendelés #42, UV Kalkuláció #5', max_length=200, verbose_name='Forrás munka')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_remnants', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remnants', to='warehouse.material', verbose_name='Alapanyag')),
                ('source_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remnants', to='warehouse.materialstock', verbose_name='Forrás készletsor')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remnants', to='warehouse.warehouse', verbose_name='Raktár')),
            ],
            options={
                'verbose_name': 'Alapanyag maradék',
                'verbose_name_plural': 'Alapanyag maradékok',
                'ordering': ['-created_at'],
            },
        ),
    ]
