# Generated by Django 4.2.7 on 2026-05-10 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0027_material_remnant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialremnant',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='materialremnant',
            name='height_mm',
        ),
        migrations.RemoveField(
            model_name='materialremnant',
            name='length_mm',
        ),
        migrations.RemoveField(
            model_name='materialremnant',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='materialremnant',
            name='source_job_ref',
        ),
        migrations.RemoveField(
            model_name='materialremnant',
            name='unit_value',
        ),
        migrations.RemoveField(
            model_name='materialremnant',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='materialremnant',
            name='width_mm',
        ),
        migrations.AddField(
            model_name='materialremnant',
            name='note',
            field=models.TextField(blank=True, verbose_name='Megjegyzés'),
        ),
        migrations.AddField(
            model_name='materialremnant',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mértékegység'),
        ),
        migrations.AlterField(
            model_name='materialremnant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_remnants', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozó'),
        ),
        migrations.AlterField(
            model_name='materialremnant',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Mennyiség'),
        ),
        migrations.AlterField(
            model_name='materialremnant',
            name='source_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remnants', to='warehouse.materialstock', verbose_name='Forrás készlet'),
        ),
        migrations.AlterField(
            model_name='materialremnant',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remnants', to='warehouse.warehouse', verbose_name='Raktár'),
        ),
    ]
