# Generated by Django 4.2.7 on 2026-07-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_remove_materialremnant_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsize',
            name='grip_height_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Az ívfogás miatti redukció hosszúságban mm-ben', max_digits=8, verbose_name='Hosszúsági ívfogás (mm)'),
        ),
        migrations.AddField(
            model_name='materialsize',
            name='grip_width_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Az ívfogás miatti redukció szélességben mm-ben (pl. 10 → nyomtatható szélesség = szélesség − 10)', max_digits=8, verbose_name='Szélességi ívfogás (mm)'),
        ),
    ]
