# Generated by Django 4.2.7 on 2026-09-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0029_materialsize_grip_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_groups',
            field=models.ManyToManyField(blank=True, help_text='Egy alapanyag több gyűjtőbe is tartozhat', related_name='materials_m2m', to='warehouse.materialgroup', verbose_name='Alapanyag gyűjtők (több)'),
        ),
    ]
