# Generated by Django 4.2.7 on 2026-09-12 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0030_material_groups_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialgroup',
            name='public_description',
            field=models.TextField(blank=True, default='', verbose_name='Publikus oldal leírás (HTML)'),
        ),
        migrations.AddField(
            model_name='materialgroup',
            name='public_slug',
            field=models.SlugField(blank=True, help_text="Egyedi URL-azonosító, pl. 'ajandektargyak' → /shop/ajandektargyak", max_length=100, null=True, unique=True, verbose_name='Publikus link (slug)'),
        ),
        migrations.AddField(
            model_name='materialgroup',
            name='public_title',
            field=models.CharField(blank=True, default='', help_text='Ha üres, a kategória neve kerül megjelenítésre', max_length=200, verbose_name='Publikus oldal cím'),
        ),
        migrations.AddField(
            model_name='materialgroup',
            name='show_prices',
            field=models.BooleanField(default=True, verbose_name='Árak megjelenítése a publikus oldalon'),
        ),
        migrations.CreateModel(
            name='MaterialGroupApiSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Szinkron neve')),
                ('api_url', models.URLField(max_length=500, verbose_name='API URL')),
                ('api_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=4, verbose_name='HTTP metódus')),
                ('api_headers', models.JSONField(blank=True, default=dict, help_text='pl. {"Authorization": "Bearer TOKEN", "X-Api-Key": "..."}', null=True, verbose_name='API fejlécek (JSON)')),
                ('api_body', models.JSONField(blank=True, default=dict, null=True, verbose_name='POST törzs / GET paraméterek (JSON)')),
                ('field_mapping', models.JSONField(blank=True, default=dict, help_text='Külső mező neve → belső mező neve, pl. {"termek_nev": "name", "ar": "unit_selling_price"}', null=True, verbose_name='Mező-leképezés (JSON)')),
                ('items_path', models.CharField(blank=True, default='', help_text='pl. "results" vagy "data.items" — üres = a teljes válasz egy tömb', max_length=200, verbose_name='Tömb elérési útja a válaszban')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60, verbose_name='Szinkronizáció gyakorisága (perc)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Utolsó szinkron')),
                ('last_sync_status', models.CharField(choices=[('idle', 'Még nem futott'), ('ok', 'Sikeres'), ('error', 'Hiba')], default='idle', max_length=10, verbose_name='Utolsó szinkron státusza')),
                ('last_sync_message', models.TextField(blank=True, default='', verbose_name='Utolsó szinkron üzenet')),
                ('last_sync_count', models.IntegerField(default=0, verbose_name='Legutóbbi szinkronált termékek száma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_syncs', to='warehouse.materialgroup', verbose_name='Alapanyag gyűjtő')),
            ],
            options={
                'verbose_name': 'API szinkron konfiguráció',
                'verbose_name_plural': 'API szinkron konfigurációk',
                'ordering': ['material_group', 'name'],
            },
        ),
    ]
