# Generated by Django 4.2.7 on 2026-09-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0031_material_group_public_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Külső forrásból szinkronizált termékkép URL', max_length=500, verbose_name='Képek URL'),
        ),
    ]
