# Generated by Django 4.2.7 on 2026-09-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_company_discount_group'),
        ('warehouse', '0032_material_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialgroupapisync',
            name='default_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Eladási ár = beszerzési ár × (1 + haszonkulcs / 100). 0 = nincs felár.', max_digits=7, verbose_name='Haszonkulcs (%)'),
        ),
        migrations.AddField(
            model_name='materialgroupapisync',
            name='default_supplier',
            field=models.ForeignKey(blank=True, help_text='Ha meg van adva, a szinkronizált termékek ehhez a beszállítóhoz lesznek rendelve.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_syncs', to='crm.company', verbose_name='Alapértelmezett beszállító'),
        ),
    ]
