# Generated by Django 4.2.7 on 2026-09-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0033_apisync_supplier_markup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='SKU')),
                ('color', models.CharField(blank=True, default='', max_length=100, verbose_name='Szín')),
                ('color_hex', models.CharField(blank=True, default='', max_length=20, verbose_name='Szín HEX')),
                ('size', models.CharField(blank=True, default='', max_length=50, verbose_name='Méret')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Készlet (elsődleges)')),
                ('stock_supplier', models.IntegerField(default=0, verbose_name='Készlet (beszállító)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ár')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='warehouse.material', verbose_name='Alapanyag')),
            ],
            options={
                'verbose_name': 'Termék variáns',
                'verbose_name_plural': 'Termék variánsok',
                'ordering': ['color', 'size'],
                'unique_together': {('material', 'sku')},
            },
        ),
    ]
