# Generated by Django 4.2.7 on 2026-09-18 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0034_material_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Vonalkód/QR kód')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='warehouse.material', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Vonalkód',
                'verbose_name_plural': 'Vonalkódok',
                'ordering': ['code'],
            },
        ),
    ]
