# Generated by Django 4.2.7 on 2026-09-18 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0035_materialbarcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ha ki van töltve, a POS ezt az árat kínálja fel akciós árként a normál ár helyett', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Akciós ár (bruttó)'),
        ),
    ]
