# Generated by Django 4.2.7 on 2026-09-19 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_company_discount_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0036_material_promo_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReceiptBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('delivery', 'Szállítólevél'), ('invoice', 'Számla')], default='delivery', max_length=20, verbose_name='Dokumentum típusa')),
                ('receipt_date', models.DateField(verbose_name='Teljesítés dátuma')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Szállítólevél/Számla szám')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Rögzítette')),
                ('supplier', models.ForeignKey(blank=True, limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_receipt_batches', to='crm.company', verbose_name='Beszállító')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_receipt_batches', to='warehouse.warehouse', verbose_name='Raktár')),
            ],
            options={
                'verbose_name': 'Bevételezés',
                'verbose_name_plural': 'Bevételezések',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.materialreceiptbatch', verbose_name='Bevételezés (fejléc)'),
        ),
    ]
