# Generated by Django 4.2.7 on 2026-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0037_materialreceiptbatch_materialreceipt_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreceipt',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Ha üres, a termék alapértelmezett mértékegysége érvényes', max_length=20, verbose_name='Mennyiségi egység'),
        ),
    ]
