# Generated by Django 4.2.7 on 2026-09-19 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0038_materialreceipt_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Dátum')),
                ('note', models.TextField(blank=True, default='', verbose_name='Megjegyzés')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktakes', to=settings.AUTH_USER_MODEL, verbose_name='Készítette')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktakes', to='warehouse.warehouse', verbose_name='Raktár')),
            ],
            options={
                'verbose_name': 'Leltár',
                'verbose_name_plural': 'Leltárak',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=50, verbose_name='Cikkszám (snapshot)')),
                ('material_name', models.CharField(max_length=200, verbose_name='Név (snapshot)')),
                ('material_unit', models.CharField(blank=True, default='', max_length=20, verbose_name='Egység (snapshot)')),
                ('book_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Nyilvántartott mennyiség')),
                ('counted_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Megszámolt mennyiség')),
                ('unit_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Beszerzési egységár (snapshot)')),
                ('book_unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Nyilvántartott egységérték (snapshot)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_items', to='warehouse.material', verbose_name='Termék')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.stocktake', verbose_name='Leltár')),
            ],
            options={
                'verbose_name': 'Leltár tétel',
                'verbose_name_plural': 'Leltár tételek',
                'ordering': ['material_name'],
                'unique_together': {('stocktake', 'material')},
            },
        ),
    ]
