# Generated by Django 4.2.7 on 2026-09-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0039_stocktake_stocktakeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('transfer', 'Mozgatás'), ('scrap', 'Selejtezés'), ('mark_defective', 'Hibásnak jelölés'), ('fuel_sale', 'Üzemanyag eladás')], max_length=20, verbose_name='Művelet típusa'),
        ),
    ]
