# Generated by Django 4.2.7 on 2026-09-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0040_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcostitem',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Fix költség'), ('unit', 'Darab alapú'), ('length', 'Folyóméter'), ('perimeter', 'Kerület'), ('area', 'Terület'), ('volume', 'Térfogat'), ('weight', 'Súly'), ('time', 'Idő')], default='unit', max_length=20, verbose_name='Számítás típusa'),
        ),
    ]
