# Generated by Django 4.2.7 on 2025-09-05 23:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Cégnév')),
                ('tax_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Adószám formátuma: 12345678-1-41', regex='^\\d{8}-\\d{1}-\\d{2}$')], verbose_name='Adószám')),
                ('country', models.CharField(default='Magyarország', max_length=100, verbose_name='Ország')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Irányítószám')),
                ('city', models.CharField(max_length=100, verbose_name='Város')),
                ('street_name', models.CharField(max_length=200, verbose_name='Utcanév')),
                ('house_number', models.CharField(max_length=20, verbose_name='Házszám')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
            ],
            options={
                'verbose_name': 'Cég',
                'verbose_name_plural': 'Cégek',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Érvényes magyar telefonszám formátum', regex='^(\\+36|06)?[0-9]{1,2}[0-9]{7,8}$')], verbose_name='Telefonszám')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail cím')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Pozíció')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company', verbose_name='Cég')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
            ],
            options={
                'verbose_name': 'Kapcsolattartó',
                'verbose_name_plural': 'Kapcsolattartók',
                'ordering': ['name'],
            },
        ),
    ]
