# Generated by Django 4.2.7 on 2025-09-06 00:39

import apps.crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, verbose_name='Cím'),
        ),
        migrations.AddField(
            model_name='company',
            name='eu_tax_number',
            field=models.CharField(blank=True, help_text='EU adószám: HU11956541', max_length=20, null=True, validators=[apps.crm.models.validate_eu_tax_number], verbose_name='EU adószám'),
        ),
        migrations.AddField(
            model_name='company',
            name='group_tax_number',
            field=models.CharField(blank=True, help_text='Csoport adószám: 12345678-1-12', max_length=20, null=True, validators=[apps.crm.models.validate_group_tax_number], verbose_name='Csoport adószám'),
        ),
        migrations.AddField(
            model_name='company',
            name='street_type',
            field=models.CharField(blank=True, default='utca', max_length=50, verbose_name='Közterület típusa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Város'),
        ),
        migrations.AlterField(
            model_name='company',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Házszám'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Irányítószám'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Közterület neve'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, help_text='Magyar adószám: 12345678-1-41', max_length=20, null=True, validators=[apps.crm.models.validate_hungarian_tax_number], verbose_name='Adószám'),
        ),
    ]
