# Generated by Django 4.2.7 on 2025-09-06 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_company_address_company_eu_tax_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail cím'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Érvényes magyar telefonszám formátum', regex='^(\\+36|06)?[0-9]{1,2}[0-9]{7,8}$')], verbose_name='Telefonszám'),
        ),
    ]
