# Generated by Django 4.2.7 on 2025-09-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_contact_email_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('customer', 'Ügyfél'), ('supplier', 'Beszállító')], default='customer', max_length=20, verbose_name='Típus'),
        ),
    ]
