# Generated by Django 4.2.7 on 2026-01-04 00:13

from django.db import migrations, models


def convert_company_types(apps, schema_editor):
    """Konvertálja a company_type értékeket is_customer és is_supplier mezőkre"""
    Company = apps.get_model('crm', 'Company')
    
    for company in Company.objects.all():
        if hasattr(company, 'company_type'):
            if company.company_type == 'customer':
                company.is_customer = True
                company.is_supplier = False
            elif company.company_type == 'supplier':
                company.is_customer = False
                company.is_supplier = True
            company.save()


def reverse_company_types(apps, schema_editor):
    """Visszaállítja a company_type értékeket"""
    Company = apps.get_model('crm', 'Company')
    
    for company in Company.objects.all():
        if company.is_customer and not company.is_supplier:
            company.company_type = 'customer'
        elif company.is_supplier and not company.is_customer:
            company.company_type = 'supplier'
        else:
            # Ha mindkettő vagy egyik sem, akkor ügyfél legyen
            company.company_type = 'customer'
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_company_company_type'),
    ]

    operations = [
        # Először hozzáadjuk az új mezőket
        migrations.AddField(
            model_name='company',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='Ügyfél'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='Beszállító'),
        ),
        # Konvertáljuk az adatokat
        migrations.RunPython(convert_company_types, reverse_company_types),
        # Végül töröljük a régi mezőt
        migrations.RemoveField(
            model_name='company',
            name='company_type',
        ),
    ]
