# Generated by Django 4.2.7 on 2026-01-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_contact_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Készpénz'), ('TRANSFER', 'Átutalás')], default='CASH', max_length=20, verbose_name='Fizetési mód'),
        ),
    ]
