# Generated by Django 4.2.7 on 2026-01-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_company_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_receipt',
            field=models.BooleanField(default=False, verbose_name='Nyugtás'),
        ),
    ]
