# Generated by Django 4.2.7 on 2026-01-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_contact_is_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Keresztnév'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Vezetéknév'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teljes név'),
        ),
    ]
