# Generated by Django 4.2.7 on 2026-01-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_contact_first_name_contact_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_hungarian_taxpayer',
            field=models.BooleanField(default=True, verbose_name='Magyar adóalany'),
        ),
        # migrations.AddField(
        #     model_name='company',
        #     name='vat_status',
        #     field=models.CharField(choices=[('DOMESTIC', 'Magyar adószámos'), ('PRIVATE_PERSON', 'Magánszemély'), ('OTHER', 'Egyéb')], default='DOMESTIC', max_length=20, verbose_name='Vevő adóalanyisága'),
        # ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, help_text='Magyar adószám: 12345678-1-41', max_length=20, null=True, verbose_name='Adószám'),
        ),
    ]
