# Generated by Django 4.2.7 on 2026-01-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_company_is_hungarian_taxpayer_company_vat_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vat_status',
            field=models.CharField(choices=[('DOMESTIC', 'Magyar adószámos'), ('PRIVATE_PERSON', 'Magánszemély'), ('OTHER', 'Egyéb')], default='DOMESTIC', max_length=20, verbose_name='Vevő adóalanyisága'),
        ),
    ]
