# Generated by Django 4.2.7 on 2026-01-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_company_vat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Külső azonosító (PixInvoice UUID)'),
        ),
    ]
