# Generated by Django 4.2.7 on 2026-08-18 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0014_company_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Név')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
                ('members', models.ManyToManyField(blank=True, related_name='discount_groups', to='crm.company', verbose_name='Tagok')),
            ],
            options={
                'verbose_name': 'Kedvezmény csoport',
                'verbose_name_plural': 'Kedvezmény csoportok',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Név')),
                ('target_type', models.CharField(choices=[('product', 'Termék'), ('material', 'Alapanyag'), ('service', 'Szolgáltatás'), ('category', 'Kategória')], max_length=20, verbose_name='Mire')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='Cél azonosító')),
                ('target_name', models.CharField(blank=True, max_length=300, verbose_name='Cél neve')),
                ('discount_type', models.CharField(choices=[('percent', 'Százalékos'), ('fixed', 'Fix összeg')], default='percent', max_length=10, verbose_name='Típus')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Értéke')),
                ('stackable', models.BooleanField(default=False, verbose_name='Halmozható')),
                ('sort_order', models.IntegerField(default=0)),
                ('discount_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='crm.discountgroup', verbose_name='Kedvezmény csoport')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
