# Generated by Django 4.2.7 on 2026-08-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_discount_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='discount_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_assignments', to='crm.discountgroup', verbose_name='Kedvezmény csoport'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='target_type',
            field=models.CharField(choices=[('product', 'Termék'), ('material', 'Alapanyag'), ('service', 'Szolgáltatás'), ('material_group', 'Anyagcsoport'), ('service_group', 'Szolgáltatáscsoport')], max_length=20, verbose_name='Mire'),
        ),
    ]
