# Generated by Django 4.2.7 on 2025-09-07 22:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('tax_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Tax number must be 8 digits')], verbose_name='Tax Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('country', models.CharField(default='Hungary', max_length=100, verbose_name='Country')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=27.0, max_digits=5, verbose_name='VAT Rate (%)')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
            },
        ),
        migrations.CreateModel(
            name='NAVConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Configuration Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('api_url', models.URLField(verbose_name='API URL')),
                ('is_test_environment', models.BooleanField(default=True, verbose_name='Test Environment')),
                ('login', models.CharField(max_length=100, verbose_name='Login')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('tax_number', models.CharField(max_length=20, verbose_name='Tax Number')),
                ('sign_key', models.CharField(max_length=100, verbose_name='Sign Key')),
                ('exchange_key', models.CharField(max_length=100, verbose_name='Exchange Key')),
                ('software_id', models.CharField(max_length=50, verbose_name='Software ID')),
                ('software_name', models.CharField(max_length=100, verbose_name='Software Name')),
                ('software_operation', models.CharField(default='ONLINE_SERVICE', max_length=50, verbose_name='Software Operation')),
                ('software_main_version', models.CharField(max_length=20, verbose_name='Software Main Version')),
                ('software_dev_name', models.CharField(max_length=100, verbose_name='Software Developer Name')),
                ('software_dev_contact', models.CharField(max_length=200, verbose_name='Software Developer Contact')),
                ('software_dev_country_code', models.CharField(default='HU', max_length=2, verbose_name='Software Developer Country Code')),
                ('software_dev_tax_number', models.CharField(max_length=20, verbose_name='Software Developer Tax Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NAV Configuration',
                'verbose_name_plural': 'NAV Configurations',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Currency')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Exchange Rate')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('submitted_to_nav', 'Submitted to NAV'), ('nav_processed', 'NAV Processed'), ('nav_rejected', 'NAV Rejected')], default='draft', max_length=20, verbose_name='Status')),
                ('nav_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='NAV Transaction ID')),
                ('nav_submission_date', models.DateTimeField(blank=True, null=True, verbose_name='NAV Submission Date')),
                ('nav_response', models.TextField(blank=True, null=True, verbose_name='NAV Response')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.customer', verbose_name='Customer')),
                ('items', models.ManyToManyField(to='invoices.invoiceitem', verbose_name='Invoice Items')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
