# Generated by Django 4.2.7 on 2025-09-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='county_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='County Code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='VAT Code'),
        ),
    ]
