# Generated by Django 4.2.7 on 2025-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_customer_county_code_customer_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='building',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='customer',
            name='door',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Door'),
        ),
        migrations.AddField(
            model_name='customer',
            name='floor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Floor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Tax Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='public_place_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Public Place Category'),
        ),
        migrations.AddField(
            model_name='customer',
            name='staircase',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Staircase'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Street Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Street Number'),
        ),
    ]
