# Generated by Django 4.2.7 on 2025-09-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_customer_building_customer_door_customer_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vat_group_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Group ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_group_member_tax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT Group Member Tax Number'),
        ),
    ]
