# Generated by Django 4.2.7 on 2025-09-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_customer_vat_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='eu_tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='EU Tax Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_hungarian_tax_number',
            field=models.BooleanField(default=True, verbose_name='Is Hungarian Tax Number'),
        ),
    ]
