# Generated by Django 4.2.7 on 2025-09-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_customer_eu_tax_number_and_more'),
    ]

    operations = [
    ]
