# Generated by Django 4.2.7 on 2025-09-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20250909_2306'),
    ]

    operations = [
    ]
