# Generated by Django 4.2.7 on 2025-09-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20250909_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_hungarian_tax_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_hungarian_taxpayer',
            field=models.BooleanField(default=True, verbose_name='Hungarian Taxpayer'),
        ),
    ]
