# Generated by Django 4.2.7 on 2025-09-09 22:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_remove_customer_is_hungarian_tax_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Keresztnév')),
                ('last_name', models.CharField(max_length=100, verbose_name='Vezetéknév')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pozíció')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Osztály')),
                ('contact_type', models.CharField(choices=[('primary', 'Elsődleges'), ('billing', 'Számlázási'), ('technical', 'Technikai'), ('sales', 'Értékesítési'), ('support', 'Támogatási'), ('other', 'Egyéb')], default='primary', max_length=20, verbose_name='Kapcsolattartó típusa')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobil')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Megjegyzések')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Elsődleges kapcsolattartó')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='invoices.customer', verbose_name='Ügyfél')),
            ],
            options={
                'verbose_name': 'Kapcsolattartó',
                'verbose_name_plural': 'Kapcsolattartók',
                'ordering': ['-is_primary', 'last_name', 'first_name'],
            },
        ),
    ]
