# Generated by Django 4.2.7 on 2025-09-09 23:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Cég neve')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rövid név')),
                ('tax_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Adószám 8 számjegyű kell legyen')], verbose_name='Adószám')),
                ('full_tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teljes adószám')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Cím')),
                ('street_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Utca')),
                ('public_place_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Közterület típusa')),
                ('street_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Házszám')),
                ('building', models.CharField(blank=True, max_length=20, null=True, verbose_name='Épület')),
                ('staircase', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lépcsőház')),
                ('floor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emelet')),
                ('door', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ajtó')),
                ('city', models.CharField(max_length=100, verbose_name='Város')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Irányítószám')),
                ('country', models.CharField(default='Magyarország', max_length=100, verbose_name='Ország')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('vat_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='VAT kód')),
                ('county_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Megye kód')),
                ('vat_group_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT csoport azonosító')),
                ('vat_group_member_tax_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT csoport tag adószáma')),
                ('is_hungarian_taxpayer', models.BooleanField(default=True, verbose_name='Magyar adószámos')),
                ('eu_tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='EU adószám')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cég',
                'verbose_name_plural': 'Cégek',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('password', models.CharField(max_length=255, verbose_name='Jelszó')),
                ('first_name', models.CharField(max_length=100, verbose_name='Keresztnév')),
                ('last_name', models.CharField(max_length=100, verbose_name='Vezetéknév')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(related_name='users', to='invoices.company', verbose_name='Hozzárendelt cégek')),
            ],
            options={
                'verbose_name': 'Rendszer felhasználó',
                'verbose_name_plural': 'Rendszer felhasználók',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Számlatömb neve')),
                ('prefix', models.CharField(max_length=20, verbose_name='Előtag')),
                ('start_number', models.PositiveIntegerField(default=1, verbose_name='Kezdő sorszám')),
                ('current_number', models.PositiveIntegerField(default=0, verbose_name='Jelenlegi sorszám')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_blocks', to='invoices.company', verbose_name='Cég')),
            ],
            options={
                'verbose_name': 'Számlatömb',
                'verbose_name_plural': 'Számlatömbök',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyNAVConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Konfiguráció neve')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('is_default', models.BooleanField(default=False, verbose_name='Alapértelmezett')),
                ('api_url', models.URLField(verbose_name='API URL')),
                ('is_test_environment', models.BooleanField(default=True, verbose_name='Teszt környezet')),
                ('username', models.CharField(max_length=100, verbose_name='Felhasználónév')),
                ('password', models.CharField(max_length=200, verbose_name='Jelszó')),
                ('tax_number', models.CharField(max_length=20, verbose_name='Adószám')),
                ('xml_sign_key', models.CharField(max_length=100, verbose_name='XML aláírókulcs')),
                ('xml_exchange_key', models.CharField(max_length=100, verbose_name='XML cserekulcs')),
                ('software_id', models.CharField(max_length=50, verbose_name='Szoftver azonosító')),
                ('software_name', models.CharField(max_length=100, verbose_name='Szoftver neve')),
                ('software_operation', models.CharField(default='ONLINE_SERVICE', max_length=50, verbose_name='Szoftver működés')),
                ('software_main_version', models.CharField(max_length=20, verbose_name='Szoftver főverzió')),
                ('software_dev_name', models.CharField(max_length=100, verbose_name='Szoftver fejlesztő neve')),
                ('software_dev_contact', models.CharField(max_length=200, verbose_name='Szoftver fejlesztő kapcsolat')),
                ('software_dev_country_code', models.CharField(default='HU', max_length=2, verbose_name='Szoftver fejlesztő ország kód')),
                ('software_dev_tax_number', models.CharField(max_length=20, verbose_name='Szoftver fejlesztő adószáma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_configurations', to='invoices.company', verbose_name='Cég')),
            ],
            options={
                'verbose_name': 'Cég NAV konfiguráció',
                'verbose_name_plural': 'Cég NAV konfigurációk',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.company', verbose_name='Cég'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.invoiceblock', verbose_name='Számlatömb'),
        ),
    ]
