# Generated by Django 4.2.7 on 2025-09-10 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_company_systemuser_invoiceblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='invoices.customer', verbose_name='Ügyfél'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_users', to='invoices.contact', verbose_name='Kapcsolattartó'),
        ),
    ]
