# Generated by Django 4.2.7 on 2025-09-10 00:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_company_customer_systemuser_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companynavconfiguration',
            options={'ordering': ['company', 'name'], 'verbose_name': 'Company NAV Configuration', 'verbose_name_plural': 'Company NAV Configurations'},
        ),
        migrations.AlterModelOptions(
            name='invoiceblock',
            options={'ordering': ['company', 'name'], 'verbose_name': 'Invoice Block', 'verbose_name_plural': 'Invoice Blocks'},
        ),
        migrations.AlterModelOptions(
            name='systemuser',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'System User', 'verbose_name_plural': 'System Users'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='building',
        ),
        migrations.RemoveField(
            model_name='company',
            name='county_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='company',
            name='door',
        ),
        migrations.RemoveField(
            model_name='company',
            name='eu_tax_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_hungarian_taxpayer',
        ),
        migrations.RemoveField(
            model_name='company',
            name='public_place_category',
        ),
        migrations.RemoveField(
            model_name='company',
            name='staircase',
        ),
        migrations.RemoveField(
            model_name='company',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vat_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vat_group_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vat_group_member_tax_number',
        ),
        migrations.RemoveField(
            model_name='companynavconfiguration',
            name='username',
        ),
        migrations.RemoveField(
            model_name='companynavconfiguration',
            name='xml_exchange_key',
        ),
        migrations.RemoveField(
            model_name='companynavconfiguration',
            name='xml_sign_key',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='password',
        ),
        migrations.AddField(
            model_name='companynavconfiguration',
            name='exchange_key',
            field=models.CharField(default=1, max_length=100, verbose_name='Exchange Key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companynavconfiguration',
            name='login',
            field=models.CharField(default=1, max_length=100, verbose_name='Login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companynavconfiguration',
            name='sign_key',
            field=models.CharField(default=1, max_length=100, verbose_name='Sign Key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemuser',
            name='password_hash',
            field=models.CharField(default=1, max_length=255, verbose_name='Password Hash'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(default='Hungary', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='full_tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Tax Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Tax number must be 8 digits')], verbose_name='Tax Number'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_configurations', to='invoices.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='is_test_environment',
            field=models.BooleanField(default=True, verbose_name='Test Environment'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Configuration Name'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='software_dev_contact',
            field=models.CharField(max_length=200, verbose_name='Software Developer Contact'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='software_dev_country_code',
            field=models.CharField(default='HU', max_length=2, verbose_name='Software Developer Country Code'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='software_dev_name',
            field=models.CharField(max_length=100, verbose_name='Software Developer Name'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='software_dev_tax_number',
            field=models.CharField(max_length=20, verbose_name='Software Developer Tax Number'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='software_id',
            field=models.CharField(max_length=50, verbose_name='Software ID'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='software_main_version',
            field=models.CharField(max_length=20, verbose_name='Software Main Version'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='software_name',
            field=models.CharField(max_length=100, verbose_name='Software Name'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='software_operation',
            field=models.CharField(default='ONLINE_SERVICE', max_length=50, verbose_name='Software Operation'),
        ),
        migrations.AlterField(
            model_name='companynavconfiguration',
            name='tax_number',
            field=models.CharField(max_length=20, verbose_name='Tax Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.invoiceblock', verbose_name='Invoice Block'),
        ),
        migrations.AlterField(
            model_name='invoiceblock',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_blocks', to='invoices.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='invoiceblock',
            name='current_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Current Number'),
        ),
        migrations.AlterField(
            model_name='invoiceblock',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='invoiceblock',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Block Name'),
        ),
        migrations.AlterField(
            model_name='invoiceblock',
            name='prefix',
            field=models.CharField(max_length=20, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='invoiceblock',
            name='start_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Start Number'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='companies',
            field=models.ManyToManyField(related_name='users', to='invoices.company', verbose_name='Companies'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
    ]
