# Generated by Django 4.2.7 on 2025-09-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_seed_ocr_vat_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='nature_indicator',
            field=models.CharField(choices=[('PRODUCT', 'Termék'), ('SERVICE', 'Szolgáltatás'), ('OTHER', 'Egyéb')], default='PRODUCT', max_length=20, verbose_name='Line Nature'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_of_measure',
            field=models.CharField(default='PIECE', max_length=20, verbose_name='Unit of Measure'),
        ),
    ]
