# Generated by Django 4.2.7 on 2025-09-11 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_alter_invoiceitem_nature_indicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='modification_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Modification Index'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='modify_without_master',
            field=models.BooleanField(default=False, verbose_name='Modify Without Master'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='invoices.invoice', verbose_name='Original Invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Original Invoice Number'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='line_operation',
            field=models.CharField(blank=True, choices=[('CREATE', 'CREATE'), ('MODIFY', 'MODIFY'), ('DELETE', 'DELETE')], max_length=10, null=True, verbose_name='Line Operation'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='original_line_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Original Line Number'),
        ),
    ]
