# Generated by Django 4.2.7 on 2025-09-11 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0028_invoice_print_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_date', models.DateField(verbose_name='Statement Date')),
                ('sequence_number', models.CharField(max_length=50, verbose_name='Sequence Number')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Currency')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements', to='invoices.companybankaccount', verbose_name='Bank Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='invoices.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'ordering': ['-statement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amount')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.bankstatement', verbose_name='Bank Statement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statement_items', to='invoices.customer', verbose_name='Customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_items', to='invoices.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Bank Statement Item',
                'verbose_name_plural': 'Bank Statement Items',
            },
        ),
    ]
