# Generated by Django 4.2.7 on 2025-09-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0029_add_bank_statements'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('submitted_to_nav', 'Submitted to NAV'), ('nav_processed', 'NAV Processed'), ('nav_rejected', 'NAV Rejected')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
