# Generated by Django 4.2.7 on 2025-09-11 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0030_add_partial_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proforma_number', models.CharField(max_length=32, unique=True, verbose_name='Díjbekérő száma')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Currency')),
                ('payment_method', models.CharField(choices=[('transfer', 'Átutalás'), ('cash', 'Készpénz'), ('card', 'Bankkártya'), ('cod', 'Utánvét'), ('other', 'Egyéb')], default='transfer', max_length=20, verbose_name='Fizetési mód')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to='invoices.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to='invoices.customer', verbose_name='Customer')),
                ('items', models.ManyToManyField(related_name='proformas', to='invoices.invoiceitem', verbose_name='Items')),
            ],
            options={
                'verbose_name': 'Proforma Invoice',
                'verbose_name_plural': 'Proforma Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
