# Generated by Django 4.2.7 on 2025-09-11 16:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0031_add_proforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advance_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_allocations_as_advance', to='invoices.invoice')),
                ('final_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_allocations_as_final', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Advance Allocation',
                'verbose_name_plural': 'Advance Allocations',
            },
        ),
    ]
