# Generated by Django 4.2.7 on 2025-09-12 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0032_add_advance_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmailSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('smtp_host', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=200, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=500, null=True)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('imap_host', models.CharField(blank=True, max_length=200, null=True)),
                ('imap_user', models.CharField(blank=True, max_length=200, null=True)),
                ('imap_password', models.CharField(blank=True, max_length=500, null=True)),
                ('imap_sent_folder', models.CharField(blank=True, default='Sent', max_length=200, null=True)),
                ('default_subject_template', models.CharField(blank=True, default='Számla {invoice_number}', max_length=200, null=True)),
                ('default_body_template', models.TextField(blank=True, default='Tisztelt {customer_name}!\n\nKüldjük a(z) {invoice_number} számú számlát PDF csatolmányként.\n\nÜdvözlettel,\n{company_name}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='invoices.company')),
            ],
            options={
                'verbose_name': 'Company Email Settings',
                'verbose_name_plural': 'Company Email Settings',
            },
        ),
    ]
