# Generated by Django 4.2.7 on 2025-09-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0036_incoming_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incominginvoicedigest',
            new_name='invoices_in_company_e916a8_idx',
            old_name='invoices_inc_issue_date_idx',
        ),
        migrations.RenameIndex(
            model_name='incominginvoicedigest',
            new_name='invoices_in_company_85cae4_idx',
            old_name='invoices_inc_ins_date_idx',
        ),
    ]
