# Generated by Django 4.2.14 on 2025-09-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0038_incoming_invoice_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incominginvoicedata',
            new_name='invoices_in_company_12996e_idx',
            old_name='invoices_in_company_7e63f1_idx',
        ),
        migrations.RenameIndex(
            model_name='incominginvoicedata',
            new_name='invoices_in_company_6ec2ff_idx',
            old_name='invoices_in_company_6c2e13_idx',
        ),
    ]
