# Generated by Django 4.2.14 on 2025-09-13 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0039_rename_invoices_in_company_7e63f1_idx_invoices_in_company_12996e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Batch Name')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('PENDING', 'Függő'), ('EXPORTED', 'Exportálva')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_batches', to='invoices.companybankaccount', verbose_name='Bank Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_batches', to='invoices.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Payment Batch',
                'verbose_name_plural': 'Payment Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Átutalás'), ('cash', 'Készpénz'), ('card', 'Bankkártya'), ('voucher', 'Utalvány'), ('cod', 'Utánvét'), ('other', 'Egyéb')], default='transfer', max_length=20, verbose_name='Fizetési mód'),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Átutalás'), ('cash', 'Készpénz'), ('card', 'Bankkártya'), ('voucher', 'Utalvány'), ('cod', 'Utánvét'), ('other', 'Egyéb')], default='transfer', max_length=20, verbose_name='Fizetési mód'),
        ),
        migrations.CreateModel(
            name='PaymentBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('supplier_tax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=300, null=True)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='HUF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.paymentbatch')),
            ],
            options={
                'verbose_name': 'Payment Batch Item',
                'verbose_name_plural': 'Payment Batch Items',
                'indexes': [models.Index(fields=['invoice_number'], name='invoices_pa_invoice_364b81_idx'), models.Index(fields=['supplier_tax_number'], name='invoices_pa_supplie_7afc24_idx')],
                'unique_together': {('batch', 'invoice_number', 'supplier_tax_number')},
            },
        ),
    ]
