# Generated by Django 4.2.14 on 2025-09-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0042_apiaccessrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccessrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access_rules', to='invoices.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='apiaccessrule',
            name='invoice_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_access_rules', to='invoices.invoiceblock', verbose_name='Invoice Block'),
        ),
    ]
