# Generated by Django 4.2.14 on 2025-09-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0043_alter_apiaccessrule_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='API-kulcs'),
        ),
    ]
