# Generated by Django 4.2.14 on 2025-09-14 19:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0044_company_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='API kapcsolat neve')),
                ('api_key', models.CharField(max_length=64, unique=True, verbose_name='API-kulcs')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to='invoices.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'API Client',
                'verbose_name_plural': 'API Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIClientAccessRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('ALL', 'All access'), ('nav.companyQuery', 'NAV céglekérdezés'), ('customer.sync', 'Ügyfél szinkronizálás'), ('contact.sync', 'Kapcsolattartó szinkronizálás'), ('invoice.send', 'Számla küldés')], max_length=64)),
                ('allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='invoices.apiclient', verbose_name='API Client')),
                ('invoice_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_client_access_rules', to='invoices.invoiceblock', verbose_name='Invoice Block')),
            ],
            options={
                'verbose_name': 'API Client Access Rule',
                'verbose_name_plural': 'API Client Access Rules',
            },
        ),
        migrations.AddConstraint(
            model_name='apiclientaccessrule',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_block__isnull', True)), fields=('api_client', 'scope'), name='unique_api_client_scope'),
        ),
        migrations.AddConstraint(
            model_name='apiclientaccessrule',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_block__isnull', False)), fields=('api_client', 'invoice_block', 'scope'), name='unique_api_client_block_scope'),
        ),
    ]
