# Generated by Django 4.2.7 on 2025-09-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0045_apiclient_apiclientaccessrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemailsettings',
            name='imap_port',
            field=models.PositiveIntegerField(default=993),
        ),
    ]
