# Generated by Django 4.2.7 on 2026-01-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0047_incomingdocument'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incomingdocument',
            new_name='invoices_in_company_0af141_idx',
            old_name='invoices_in_company_invoice_idx',
        ),
        migrations.RenameIndex(
            model_name='incomingdocument',
            new_name='invoices_in_company_912df2_idx',
            old_name='invoices_in_company_supp_idx',
        ),
    ]
