# Generated by Django 4.2.7 on 2026-01-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0048_rename_invoices_in_company_invoice_idx_invoices_in_company_0af141_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vattype',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Kód (NAV)'),
        ),
    ]
