# Generated by Django 4.2.7 on 2026-01-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0049_alter_vattype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='erp_order_ids',
            field=models.JSONField(blank=True, help_text='List of ERP order IDs associated with this invoice', null=True, verbose_name='ERP Order IDs'),
        ),
    ]
