# Generated by Django 4.2.7 on 2026-01-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0053_emergency_access_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
    ]
