# Generated by Django 4.2.7 on 2026-01-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0054_add_last_login_to_systemuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominginvoicedigest',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
