# Generated by Django 4.2.7 on 2026-01-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0055_incominginvoicedigest_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='Vevő'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='Beszállító'),
        ),
    ]
