# Generated by Django 4.2.7 on 2026-01-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0060_companybankaccount_round_flag'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incominginvoicedigest',
            new_name='invoices_in_company_a8376d_idx',
            old_name='invoices_in_company_9c6841_idx',
        ),
        migrations.AddField(
            model_name='customerbankaccount',
            name='round_transfer_to_whole',
            field=models.BooleanField(default=False, verbose_name='Csak egész számos utalás'),
        ),
    ]
