# Generated by Django 4.2.7 on 2026-01-20 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0061_rename_invoices_in_company_9c6841_idx_invoices_in_company_a8376d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementitem',
            name='incoming_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_items', to='invoices.incominginvoicedigest', verbose_name='Incoming Invoice'),
        ),
    ]
