# Generated by Django 4.2.7 on 2026-01-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0062_bankstatementitem_incoming_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominginvoicedigest',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='incominginvoicedigest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Reference'),
        ),
        migrations.AddField(
            model_name='incominginvoicedigest',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='incominginvoicedigest',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
    ]
