# Generated by Django 4.2.7 on 2026-01-22 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0064_customer_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_receipt',
            field=models.BooleanField(default=False, verbose_name='Nyugtás'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='invoices.customer', verbose_name='Ügyfél'),
        ),
    ]
