# Generated by Django 4.2.7 on 2026-01-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0065_contact_is_receipt_alter_contact_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbankaccount',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Jóváhagyva'),
        ),
    ]
