# Generated by Django 4.2.7 on 2026-01-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0066_customerbankaccount_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tax Number'),
        ),
    ]
