# Generated by Django 4.2.7 on 2026-01-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0067_alter_customer_tax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_currency',
            field=models.CharField(default='HUF', max_length=3, verbose_name='Alapértelmezett deviza'),
        ),
    ]
