# Generated by Django 4.2.7 on 2026-01-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0068_customer_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Currency Code')),
                ('name', models.CharField(max_length=50, verbose_name='Currency Name')),
                ('symbol', models.CharField(blank=True, max_length=5, null=True, verbose_name='Symbol')),
                ('current_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='Current Rate (to HUF)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='invoiceblock',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_blocks', to='invoices.companybankaccount', verbose_name='Default Bank Account'),
        ),
        migrations.AddField(
            model_name='invoiceblock',
            name='default_currency',
            field=models.CharField(default='HUF', max_length=3, verbose_name='Default Currency'),
        ),
    ]
