# Generated by Django 4.2.7 on 2026-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0069_currency_invoiceblock_default_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceblock',
            name='language',
            field=models.CharField(choices=[('hu', 'Magyar'), ('en', 'Angol'), ('de', 'Német')], default='hu', max_length=5, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='invoiceblock',
            name='second_language',
            field=models.CharField(blank=True, choices=[('hu', 'Magyar'), ('en', 'Angol'), ('de', 'Német')], max_length=5, null=True, verbose_name='Second Language'),
        ),
    ]
