# Generated by Django 4.2.7 on 2026-01-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0071_invoiceblock_footer_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['order_index', 'name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='Order Index'),
        ),
    ]
