# Generated by Django 4.2.7 on 2026-02-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0072_alter_company_options_company_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominginvoicedigest',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Exchange Rate'),
        ),
        migrations.AddField(
            model_name='incominginvoicedigest',
            name='invoice_net_amount_huf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Net Amount HUF'),
        ),
        migrations.AddField(
            model_name='incominginvoicedigest',
            name='invoice_vat_amount_huf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='VAT Amount HUF'),
        ),
    ]
