# Generated by Django 4.2.7 on 2026-02-18 07:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0075_alter_companyemailsettings_arrears_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('invoice_send', 'Számlaküldés'), ('arrears', 'Kintlévőségi'), ('reminder_1', '1. felszólítás'), ('reminder_2', '2. felszólítás'), ('legal', 'Ügyvédi')], max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('subject_template', models.CharField(blank=True, max_length=250, null=True)),
                ('body_template', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='invoices.company')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_signatures', to='invoices.company')),
            ],
            options={
                'verbose_name': 'Email Signature',
                'verbose_name_plural': 'Email Signatures',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(fields=('company', 'template_type'), name='unique_company_template_type'),
        ),
    ]
