# Generated by Django 4.2.7 on 2026-02-19 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0080_invoice_arrears_status_and_email_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_mode', models.CharField(choices=[('interval', 'Időalapú'), ('weekday', 'Heti naphoz kötött'), ('monthday', 'Havi naphoz kötött')], default='interval', max_length=16)),
                ('interval_unit', models.CharField(choices=[('day', 'Naponta'), ('week', 'Hetente'), ('month', 'Havonta'), ('year', 'Évente')], default='month', max_length=12)),
                ('interval_value', models.PositiveIntegerField(default=1)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month_last_day', models.BooleanField(default=False)),
                ('next_issue_date', models.DateField()),
                ('last_issue_date', models.DateField(blank=True, null=True)),
                ('due_offset_days', models.IntegerField(default=0)),
                ('delivery_offset_days', models.IntegerField(default=0)),
                ('approval_required', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_send_email', models.BooleanField(default=False)),
                ('email_template_type', models.CharField(default='invoice_send', max_length=32)),
                ('extra_emails', models.JSONField(blank=True, default=list)),
                ('template_payload', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scheduled_invoices', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_invoices', to='invoices.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_invoices', to='invoices.customer')),
                ('invoice_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_invoices', to='invoices.invoiceblock')),
                ('last_generated_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_source_records', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Scheduled Invoice',
                'verbose_name_plural': 'Scheduled Invoices',
                'ordering': ['next_issue_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledInvoiceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_for_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_runs', to='invoices.invoice')),
                ('scheduled_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='invoices.scheduledinvoice')),
            ],
            options={
                'verbose_name': 'Scheduled Invoice Run',
                'verbose_name_plural': 'Scheduled Invoice Runs',
                'ordering': ['-created_at'],
                'unique_together': {('scheduled_invoice', 'invoice')},
            },
        ),
        migrations.AddIndex(
            model_name='scheduledinvoice',
            index=models.Index(fields=['company', 'is_active', 'next_issue_date'], name='invoices_sc_company_e77670_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledinvoice',
            index=models.Index(fields=['company', 'customer'], name='invoices_sc_company_54bcd0_idx'),
        ),
    ]
