# Generated by Django 4.2.7 on 2026-03-04 08:46

from django.db import migrations, models
import django.db.models.deletion
import invoices.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0086_customer_group_tax_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingProforma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proforma_number', models.CharField(max_length=100)),
                ('supplier_tax_number', models.CharField(blank=True, max_length=30, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=300, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, default='TRANSFER', max_length=30, null=True)),
                ('currency', models.CharField(blank=True, default='HUF', max_length=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('unpaid', 'Kifizetetlen'), ('paid', 'Kifizetett'), ('invoiced', 'Kiszámlázott')], default='unpaid', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_proformas', to='invoices.company')),
            ],
            options={
                'verbose_name': 'Incoming Proforma',
                'verbose_name_plural': 'Incoming Proformas',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomingProformaDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IMAGE', 'Számlakép'), ('OTHER', 'Egyéb'), ('CONTRACT', 'Szerződés'), ('SUPPLIER', 'Szállító'), ('PERFORMANCE_CERT', 'Teljesítés igazolás')], default='IMAGE', max_length=16)),
                ('file', models.FileField(upload_to=invoices.models.incoming_proforma_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='invoices.incomingproforma')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomingProformaInvoiceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('supplier_tax_number', models.CharField(blank=True, max_length=30, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=300, null=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(blank=True, default='HUF', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_links', to='invoices.incomingproforma')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('proforma', 'invoice_number', 'supplier_tax_number')},
            },
        ),
        migrations.AddIndex(
            model_name='incomingproforma',
            index=models.Index(fields=['company', 'status'], name='invoices_in_company_6f7fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingproforma',
            index=models.Index(fields=['company', 'supplier_tax_number'], name='invoices_in_company_4b9931_idx'),
        ),
    ]
