# Generated by Django 4.2.7 on 2026-06-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0088_currency_display_decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='arrears_log',
            field=models.JSONField(blank=True, null=True, verbose_name='Behajtási napló'),
        ),
    ]
