# Generated by Django 4.2.7 on 2026-06-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0089_arrears_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingproforma',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Kifizetetlen'), ('partial', 'Részben fizetve'), ('paid', 'Kifizetett'), ('invoiced', 'Kiszámlázott')], default='unpaid', max_length=20),
        ),
    ]
