# Generated by Django 4.2.7 on 2026-06-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0090_add_partial_status_to_incoming_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Kifizetetlen'), ('partial', 'Részben fizetve'), ('paid', 'Kifizetett'), ('invoiced', 'Kiszámlázott')], default='unpaid', max_length=20),
        ),
    ]
