# Generated by Django 4.2.7 on 2026-06-30 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0092_alter_emailtemplate_template_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=300, verbose_name='Esemény')),
                ('category', models.CharField(default='log', max_length=40, verbose_name='Kategória')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP cím')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metaadatok')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='invoices.invoice', verbose_name='Számla')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Számla napló',
                'verbose_name_plural': 'Számla naplók',
                'ordering': ['-created_at'],
            },
        ),
    ]
