# Generated by Django 4.2.7 on 2026-07-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0093_add_invoice_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominginvoicedigest',
            name='supplier_group_member_tax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Supplier Group Member Tax Number'),
        ),
    ]
