# Generated by Django 4.2.7 on 2026-07-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0094_add_supplier_group_member_tax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='erp_rfq_ids',
            field=models.JSONField(blank=True, help_text='List of ERP RFQ IDs (QuoteRequest) directly invoiced without CustomerOrder', null=True, verbose_name='ERP RFQ IDs'),
        ),
    ]
