# Generated by Django 4.2.7 on 2025-09-05 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=50, unique=True, verbose_name='Munkalap szám')),
                ('status', models.CharField(choices=[('draft', 'Vázlat'), ('planned', 'Tervezett'), ('in_progress', 'Folyamatban'), ('completed', 'Kész'), ('cancelled', 'Törölve')], default='draft', max_length=20, verbose_name='Státusz')),
                ('priority', models.CharField(choices=[('low', 'Alacsony'), ('normal', 'Normál'), ('high', 'Magas'), ('urgent', 'Sürgős')], default='normal', max_length=10, verbose_name='Prioritás')),
                ('planned_start_date', models.DateTimeField(verbose_name='Tervezett kezdés')),
                ('planned_end_date', models.DateTimeField(verbose_name='Tervezett befejezés')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Tényleges kezdés')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tényleges befejezés')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Felelős')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Készítette')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order', verbose_name='Megrendelés')),
            ],
            options={
                'verbose_name': 'Munkalap',
                'verbose_name_plural': 'Munkalapok',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('status', models.CharField(choices=[('draft', 'Vázlat'), ('planned', 'Tervezett'), ('in_progress', 'Folyamatban'), ('completed', 'Kész'), ('cancelled', 'Törölve')], default='draft', max_length=20, verbose_name='Státusz')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product', verbose_name='Termék')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manufacturing.workorder', verbose_name='Munkalap')),
            ],
            options={
                'verbose_name': 'Munkalap tétel',
                'verbose_name_plural': 'Munkalap tételek',
            },
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Függőben'), ('passed', 'Megfelelő'), ('failed', 'Nem megfelelő'), ('rework', 'Újramunka')], default='pending', max_length=20, verbose_name='Státusz')),
                ('inspection_date', models.DateTimeField(verbose_name='Ellenőrzés dátuma')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ellenőr')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product', verbose_name='Termék')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.workorder', verbose_name='Munkalap')),
            ],
            options={
                'verbose_name': 'Minőségbiztosítás',
                'verbose_name_plural': 'Minőségbiztosítások',
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Kiosztva'), ('in_progress', 'Folyamatban'), ('completed', 'Kész'), ('approved', 'Jóváhagyva'), ('rejected', 'Elutasítva'), ('revision', 'Átnézésre küldve')], default='assigned', max_length=20, verbose_name='Státusz')),
                ('description', models.TextField(verbose_name='Gyártási feladat')),
                ('deadline', models.DateTimeField(verbose_name='Határidő')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Befejezve')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Jóváhagyva')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Elutasítás oka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_productions', to=settings.AUTH_USER_MODEL, verbose_name='Jóváhagyta')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gyártó')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.workorder', verbose_name='Munkalap')),
            ],
            options={
                'verbose_name': 'Gyártási fázis',
                'verbose_name_plural': 'Gyártási fázisok',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Bevételezés'), ('out', 'Kiadás'), ('adjustment', 'Korrekció'), ('transfer', 'Áthelyezés')], max_length=20, verbose_name='Mozgás típusa')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Hivatkozás')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dátum')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Készítette')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Készlet mozgás',
                'verbose_name_plural': 'Készlet mozgások',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség')),
                ('location', models.CharField(max_length=100, verbose_name='Hely')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum készlet')),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maximum készlet')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Utolsó frissítés')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Készlet',
                'verbose_name_plural': 'Készletek',
            },
        ),
        migrations.CreateModel(
            name='DesignPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Kiosztva'), ('in_progress', 'Folyamatban'), ('completed', 'Kész'), ('approved', 'Jóváhagyva'), ('rejected', 'Elutasítva'), ('revision', 'Átnézésre küldve')], default='assigned', max_length=20, verbose_name='Státusz')),
                ('description', models.TextField(verbose_name='Tervezési feladat')),
                ('deadline', models.DateTimeField(verbose_name='Határidő')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Befejezve')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Jóváhagyva')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Elutasítás oka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_designs', to=settings.AUTH_USER_MODEL, verbose_name='Jóváhagyta')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tervező')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.workorder', verbose_name='Munkalap')),
            ],
            options={
                'verbose_name': 'Tervezési fázis',
                'verbose_name_plural': 'Tervezési fázisok',
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség')),
                ('unit', models.CharField(max_length=20, verbose_name='Mértékegység')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_bom', to='sales.product', verbose_name='Komponens')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='sales.product', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Anyagjegyzék',
                'verbose_name_plural': 'Anyagjegyzékek',
                'unique_together': {('product', 'component')},
            },
        ),
    ]
