# Generated by Django 4.2.7 on 2025-09-07 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_contact_email_alter_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0006_remove_employee_department_employee_departments'),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Név')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('deadline', models.DateField(verbose_name='Határidő')),
                ('status', models.CharField(choices=[('open', 'Nyitott'), ('closed', 'Zárt')], default='open', max_length=10, verbose_name='Állapot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacts', models.ManyToManyField(blank=True, to='crm.contact', verbose_name='Kapcsolattartók')),
                ('project_manager', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Projektvezető')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projektek',
            },
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('is_default', models.BooleanField(default=False, verbose_name='Alapértelmezett')),
                ('calculators', models.JSONField(blank=True, default=list, verbose_name='Kalkulátorok')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hr_departments', models.ManyToManyField(blank=True, to='hr.department', verbose_name='HR osztályok')),
            ],
            options={
                'verbose_name': 'Termék osztály',
                'verbose_name_plural': 'Termék osztályok',
            },
        ),
        migrations.CreateModel(
            name='ManufacturingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Dátum')),
                ('name', models.CharField(max_length=200, verbose_name='Név')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('internal_description', models.TextField(blank=True, verbose_name='Belső leírás')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség')),
                ('net_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nettó egység ár')),
                ('net_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nettó ár')),
                ('status', models.CharField(choices=[('quote_request_open', 'Ajánlatkérés nyitott'), ('quote_request_priced', 'Ajánlatkérés árazott'), ('quote_request_sent', 'Ajánlatkérés kiküldött'), ('ordered', 'Megrendelve'), ('design_in_progress', 'Tervezés alatt'), ('design_approved', 'Tervezés jóváhagyva'), ('production_in_progress', 'Gyártás alatt'), ('production_completed', 'Gyártás kész'), ('finished_goods_warehouse', 'Készárú raktárban'), ('installation_in_progress', 'Kihelyezés alatt'), ('delivered', 'Kiszállítva'), ('invoiced', 'Számlázva'), ('paid', 'Kifizetve')], default='quote_request_open', max_length=30, verbose_name='Állapot')),
                ('deadline', models.DateField(verbose_name='Határidő')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact', verbose_name='Ügyfél')),
                ('product_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.productclass', verbose_name='Termék osztály')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Gyártási termék',
                'verbose_name_plural': 'Gyártási termékek',
            },
        ),
    ]
