# Generated by Django 4.2.7 on 2025-12-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_manufacturingproduct_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Profit'),
        ),
        migrations.AddField(
            model_name='project',
            name='profit_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Profitarány (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Összesített költség'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Összesített bevétel'),
        ),
    ]
