# Generated by Django 4.2.7 on 2026-01-03 01:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0003_material_material_format_material_roll_width_and_more'),
        ('manufacturing', '0004_project_profit_project_profit_margin_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Szolgáltatás neve')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kód')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('unit', models.CharField(choices=[('db', 'darab'), ('m', 'folyóméter'), ('m2', 'négyzetméter'), ('kg', 'kilogramm'), ('hour', 'óra'), ('perimeter', 'kerület (méter)')], default='db', max_length=20, verbose_name='Mértékegység')),
                ('calculation_basis', models.CharField(choices=[('fixed', 'Fix ár'), ('area', 'Terület alapú'), ('perimeter', 'Kerület alapú'), ('length', 'Hossz alapú'), ('weight', 'Súly alapú'), ('quantity', 'Darabszám alapú')], default='fixed', max_length=20, verbose_name='Kalkuláció alapja')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Ár mértékegységenként', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységár (nettó)')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('category', models.CharField(blank=True, help_text='pl. Nyomtatás, Utómunka, Szállítás', max_length=100, verbose_name='Kategória')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
            ],
            options={
                'verbose_name': 'Szolgáltatás',
                'verbose_name_plural': 'Szolgáltatások',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CalculatorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kalkulátor neve')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kód')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('default_markup_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alapértelmezett haszonkulcs %')),
                ('input_fields', models.JSONField(default=list, help_text='Kalkulátorhoz szükséges input mezők definíciója', verbose_name='Bemenet mezők')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('allowed_materials', models.ManyToManyField(blank=True, help_text='Ezekből az alapanyagokból lehet választani', to='warehouse.material', verbose_name='Engedélyezett alapanyagok')),
                ('allowed_services', models.ManyToManyField(blank=True, help_text='Ezeket a szolgáltatásokat lehet hozzáadni', to='manufacturing.service', verbose_name='Engedélyezett szolgáltatások')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calculator_templates', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
            ],
            options={
                'verbose_name': 'Kalkulátor sablon',
                'verbose_name_plural': 'Kalkulátor sablonok',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_values', models.JSONField(default=dict, verbose_name='Bemenet értékek')),
                ('selected_materials', models.JSONField(default=list, verbose_name='Kiválasztott alapanyagok')),
                ('selected_services', models.JSONField(default=list, verbose_name='Kiválasztott szolgáltatások')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Alapanyag költség')),
                ('service_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Szolgáltatás költség')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Össz bekerülési ár')),
                ('markup_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Haszonkulcs %')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Eladási ár')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('quote_reference', models.CharField(blank=True, help_text='Hivatkozás ajánlatra', max_length=100, verbose_name='Ajánlat referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.calculatortemplate', verbose_name='Kalkulátor sablon')),
            ],
            options={
                'verbose_name': 'Kalkuláció',
                'verbose_name_plural': 'Kalkulációk',
                'ordering': ['-created_at'],
            },
        ),
    ]
