# Generated by Django 4.2.7 on 2026-01-03 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_service_calculatortemplate_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='material_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alapanyag haszonkulcs %'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='material_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Alapanyag eladási ár'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='service_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Szolgáltatás haszonkulcs %'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='service_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Szolgáltatás eladási ár'),
        ),
        migrations.AddField(
            model_name='calculatortemplate',
            name='default_material_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alapanyag haszonkulcs %'),
        ),
        migrations.AddField(
            model_name='calculatortemplate',
            name='default_service_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Szolgáltatás haszonkulcs %'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='markup_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Haszonkulcs % (deprecated)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Össz eladási ár'),
        ),
        migrations.AlterField(
            model_name='calculatortemplate',
            name='default_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alapértelmezett haszonkulcs % (deprecated)'),
        ),
    ]
