# Generated by Django 4.2.7 on 2026-01-03 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0006_calculation_material_markup_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=35.0, help_text='Haszonkulcs százalékban', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Haszonkulcs %'),
        ),
        migrations.AddField(
            model_name='service',
            name='unit_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bekerülési ár mértékegységenként', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységár (bekerülési)'),
        ),
        migrations.AddField(
            model_name='service',
            name='unit_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Eladási ár mértékegységenként (számított vagy manuális)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységár (eladási)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Használd helyette: unit_selling_price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységár (nettó) - DEPRECATED'),
        ),
    ]
