# Generated by Django 4.2.7 on 2026-01-03 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_remove_department_manager_department_managers'),
        ('crm', '0004_company_company_type'),
        ('manufacturing', '0007_service_markup_percentage_service_unit_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_supplier',
            field=models.ForeignKey(blank=True, help_text='Ez a beszállító lesz használva a kalkulációban', limit_choices_to={'company_type': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_services', to='crm.company', verbose_name='Alapértelmezett beszállító'),
        ),
        migrations.AddField(
            model_name='service',
            name='internal_production_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Belső gyártás bekerülési költsége', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Belső gyártási költség'),
        ),
        migrations.AddField(
            model_name='service',
            name='internal_production_department',
            field=models.ForeignKey(blank=True, help_text='Melyik osztály végzi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_services', to='hr.department', verbose_name='Gyártó osztály'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_internal_production',
            field=models.BooleanField(default=False, help_text='Házon belül végezzük', verbose_name='Belső gyártás'),
        ),
        migrations.CreateModel(
            name='ServiceSupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Ez a beszállító lesz használva a kalkulációban', verbose_name='Alapértelmezett beszállító')),
                ('fixed_cost', models.DecimalField(decimal_places=2, default=0, help_text='Fix költség (pl. beállítási díj)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fix költség')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Ár darabonként/mértékegységenként', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységár')),
                ('price_per_perimeter', models.DecimalField(decimal_places=2, default=0, help_text='Ár folyóméterenként (kerület)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ár kerület alapján')),
                ('price_per_area', models.DecimalField(decimal_places=2, default=0, help_text='Ár négyzetméterenként', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ár terület alapján')),
                ('price_per_weight', models.DecimalField(decimal_places=2, default=0, help_text='Ár kilogrammonként', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ár súly alapján')),
                ('price_per_time', models.DecimalField(decimal_places=2, default=0, help_text='Ár óránként', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ár idő alapján')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('min_order_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum rendelési mennyiség')),
                ('lead_time_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Szállítási határidő (nap)')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='manufacturing.service', verbose_name='Szolgáltatás')),
                ('supplier', models.ForeignKey(limit_choices_to={'company_type': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='crm.company', verbose_name='Beszállító')),
            ],
            options={
                'verbose_name': 'Szolgáltatás beszállítói ár',
                'verbose_name_plural': 'Szolgáltatás beszállítói árak',
                'ordering': ['service', 'supplier'],
                'unique_together': {('service', 'supplier')},
            },
        ),
    ]
