# Generated by Django 4.2.7 on 2026-01-03 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_service_default_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='internal_fixed_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Belső fix költség'),
        ),
        migrations.AddField(
            model_name='service',
            name='internal_price_per_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Belső ár terület alapján'),
        ),
        migrations.AddField(
            model_name='service',
            name='internal_price_per_perimeter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Belső ár kerület alapján'),
        ),
        migrations.AddField(
            model_name='service',
            name='internal_price_per_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Belső ár idő alapján'),
        ),
        migrations.AddField(
            model_name='service',
            name='internal_price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Belső egységár'),
        ),
        migrations.AddField(
            model_name='service',
            name='internal_price_per_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Belső ár súly alapján'),
        ),
        migrations.AlterField(
            model_name='service',
            name='calculation_basis',
            field=models.CharField(choices=[('fixed', 'Fix ár'), ('area', 'Terület alapú'), ('perimeter', 'Kerület alapú'), ('length', 'Hossz alapú'), ('weight', 'Súly alapú'), ('quantity', 'Darabszám alapú')], default='fixed', help_text='DEPRECATED: A kalkuláció alapját a beszállítói vagy belső gyártási árkalkuláció határozza meg', max_length=20, verbose_name='Kalkuláció alapja'),
        ),
        migrations.AlterField(
            model_name='service',
            name='internal_production_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Használd helyette az árkalkulációs komponenseket', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Belső gyártási költség (deprecated)'),
        ),
    ]
