# Generated by Django 4.2.7 on 2026-01-03 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_company_company_type'),
        ('manufacturing', '0009_service_internal_fixed_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(default=False, help_text='Ez a költség elem belső gyártáshoz tartozik', verbose_name='Belső gyártás')),
                ('name', models.CharField(help_text='pl. Anyagköltség, Munkadíj, stb.', max_length=200, verbose_name='Megnevezés')),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fix költség'), ('unit', 'Darab alapú'), ('length', 'Folyóméter'), ('perimeter', 'Kerület'), ('area', 'Terület'), ('weight', 'Súly'), ('time', 'Idő')], default='unit', max_length=20, verbose_name='Számítás típusa')),
                ('unit', models.CharField(blank=True, help_text='pl. db, kg, m, m², óra', max_length=50, verbose_name='Egység')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Bekerülési egységár', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységár')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Haszon kulcs (%)')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, help_text='Automatikusan számított', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Eladási ár')),
                ('currency', models.CharField(default='HUF', max_length=3, verbose_name='Pénznem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='manufacturing.service', verbose_name='Szolgáltatás')),
                ('supplier', models.ForeignKey(blank=True, help_text='Null = belső gyártás', limit_choices_to={'company_type': 'supplier'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_cost_items', to='crm.company', verbose_name='Beszállító')),
            ],
            options={
                'verbose_name': 'Szolgáltatás költség elem',
                'verbose_name_plural': 'Szolgáltatás költség elemek',
                'ordering': ['service', 'supplier', 'name'],
            },
        ),
    ]
