# Generated by Django 4.2.7 on 2026-01-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_company_company_type_company_is_customer_and_more'),
        ('manufacturing', '0010_servicecostitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company', verbose_name='Cég'),
        ),
        migrations.AlterField(
            model_name='service',
            name='default_supplier',
            field=models.ForeignKey(blank=True, help_text='Ez a beszállító lesz használva a kalkulációban', limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_services', to='crm.company', verbose_name='Alapértelmezett beszállító'),
        ),
        migrations.AlterField(
            model_name='servicecostitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Null = belső gyártás', limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_cost_items', to='crm.company', verbose_name='Beszállító'),
        ),
        migrations.AlterField(
            model_name='servicesupplierprice',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='crm.company', verbose_name='Beszállító'),
        ),
    ]
