# Generated by Django 4.2.7 on 2026-01-17 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0012_manufacturingproduct_contact_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=35.0, help_text='Haszonkulcs százalékban', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Haszonkulcs %'),
        ),
    ]
