# Generated by Django 4.2.7 on 2026-01-17 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0013_alter_service_markup_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecostitem',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Haszon kulcs (%)'),
        ),
    ]
