# Generated by Django 4.2.7 on 2026-01-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0014_alter_servicecostitem_markup_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='calculation_unit',
            field=models.CharField(choices=[('db', 'darab'), ('m', 'folyóméter'), ('m2', 'négyzetméter'), ('kg', 'kilogramm'), ('hour', 'óra'), ('perimeter', 'kerület (méter)'), ('minute', 'perc')], default='db', help_text='Ha eltér az alap mértékegységtől, a rendszer átváltja', max_length=20, verbose_name='Kalkulációs mértékegység'),
        ),
        migrations.AddField(
            model_name='servicecostitem',
            name='rounding_step',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Pl. 0.5 óra, 10 perc, 1 db. Mindig felfelé kerekít.', max_digits=10, verbose_name='Elszámolási egység (kerekítés)'),
        ),
    ]
