# Generated by Django 4.2.7 on 2026-01-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_pixinvoiceconfig_base_url'),
        ('manufacturing', '0015_service_calculation_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingproduct',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cikkszám'),
        ),
        migrations.CreateModel(
            name='ManufacturingCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='other', max_length=20, verbose_name='Típus')),
                ('ref_id', models.IntegerField(blank=True, null=True, verbose_name='Referencia ID')),
                ('name', models.CharField(max_length=200, verbose_name='Megnevezés')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Mennyiség')),
                ('unit', models.CharField(default='db', max_length=20, verbose_name='Egység')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Egységár (Eladási)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bekerülési ár')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Haszonkulcs %')),
                ('selling_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Eladási egységár')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Eladási ár összesen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='manufacturing.manufacturingproduct', verbose_name='Termék')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company', verbose_name='Beszállító')),
            ],
            options={
                'verbose_name': 'Gyártási költség elem',
                'verbose_name_plural': 'Gyártási költség elemek',
            },
        ),
    ]
