# Generated by Django 4.2.7 on 2026-01-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_contact_first_name_contact_last_name_and_more'),
        ('manufacturing', '0016_manufacturingproduct_code_manufacturingcostitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingcostitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company', verbose_name='Beszállító'),
        ),
    ]
