# Generated by Django 4.2.7 on 2026-01-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_kioskdevice_ip_address'),
        ('manufacturing', '0017_alter_manufacturingcostitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingcostitem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='Belső részleg'),
        ),
        migrations.AddField(
            model_name='manufacturingcostitem',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Belső gyártás'),
        ),
    ]
