# Generated by Django 4.2.7 on 2026-01-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0018_manufacturingcostitem_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingproduct',
            name='is_fixed_quantity',
            field=models.BooleanField(default=False, verbose_name='Fix mennyiség'),
        ),
    ]
