# Generated by Django 4.2.7 on 2026-01-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0019_manufacturingproduct_is_fixed_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingcostitem',
            name='markup_percent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Haszonkulcs %'),
        ),
    ]
