# Generated by Django 4.2.7 on 2026-01-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0020_alter_manufacturingcostitem_markup_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingcostitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Bekerülési ár'),
        ),
        migrations.AlterField(
            model_name='manufacturingcostitem',
            name='markup_percent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Haszonkulcs %'),
        ),
        migrations.AlterField(
            model_name='manufacturingcostitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Eladási ár összesen'),
        ),
        migrations.AlterField(
            model_name='manufacturingcostitem',
            name='selling_unit_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Eladási egységár'),
        ),
        migrations.AlterField(
            model_name='manufacturingcostitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Egységár (Eladási)'),
        ),
    ]
