# Generated by Django 4.2.7 on 2026-01-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_company_vat_status'),
        ('manufacturing', '0021_alter_manufacturingcostitem_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingproduct',
            name='allowed_companies',
            field=models.ManyToManyField(blank=True, to='crm.company', verbose_name='Engedélyezett cégek'),
        ),
    ]
