# Generated by Django 4.2.7 on 2026-01-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_company_external_id'),
        ('manufacturing', '0022_manufacturingproduct_allowed_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingproduct',
            name='allowed_contacts',
            field=models.ManyToManyField(blank=True, related_name='allowed_products', to='crm.contact', verbose_name='Engedélyezett kapcsolattartók'),
        ),
    ]
