# Generated by Django 4.2.7 on 2026-02-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0024_servicegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='manufacturing.servicegroup', verbose_name='Szülő csoport'),
        ),
    ]
