# Generated by Django 4.2.7 on 2026-02-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0025_servicegroup_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='description',
            field=models.TextField(blank=True, verbose_name='Leírás'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='manufacturing.productclass', verbose_name='Szülő kategória'),
        ),
    ]
