# Generated by Django 4.2.7 on 2026-02-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0026_productclass_description_productclass_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='services', to='manufacturing.servicegroup', verbose_name='Szolgáltatás csoportok'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, help_text='pl. Nyomtatás, Utómunka, Szállítás', max_length=100, verbose_name='Kategória (Legacy)'),
        ),
    ]
