# Generated by Django 4.2.7 on 2026-03-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0027_service_groups_alter_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Termék neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('calculators', models.ManyToManyField(blank=True, related_name='product_templates', to='manufacturing.calculatortemplate', verbose_name='Kalkulátorok')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_templates', to='manufacturing.productclass', verbose_name='Termékkategória')),
            ],
            options={
                'verbose_name': 'Termék sablon',
                'verbose_name_plural': 'Termék sablonok',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplateSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Méret neve (pl. A4, B2)')),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Szélesség (mm)')),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Magasság (mm)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='manufacturing.producttemplate', verbose_name='Termék sablon')),
            ],
            options={
                'verbose_name': 'Termék méret',
                'verbose_name_plural': 'Termék méretek',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
