# Generated by Django 4.2.7 on 2026-03-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0028_product_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Cikkszám'),
        ),
    ]
