# Generated by Django 4.2.7 on 2026-03-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0029_product_template_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplatesize',
            name='height_max_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Magasság max (mm)'),
        ),
        migrations.AddField(
            model_name='producttemplatesize',
            name='width_max_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Szélesség max (mm)'),
        ),
        migrations.AlterField(
            model_name='producttemplatesize',
            name='height_mm',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Magasság min (mm)'),
        ),
        migrations.AlterField(
            model_name='producttemplatesize',
            name='width_mm',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Szélesség min (mm)'),
        ),
    ]
