# Generated by Django 4.2.7 on 2026-03-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0030_producttemplatesize_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatortemplate',
            name='calculator_type',
            field=models.CharField(blank=True, choices=[('generic', 'Általános'), ('sheet_print', 'Íves/Táblás optimalizálás'), ('roll_print', 'Tekercses kalkuláció')], default='generic', max_length=50, verbose_name='Működési logika'),
        ),
        migrations.AddField(
            model_name='calculatortemplate',
            name='category',
            field=models.CharField(blank=True, choices=[('sheet_print', 'Íves/Táblás nyomtatás'), ('roll_print', 'Tekercses nyomtatás'), ('lightbox', 'Világító tábla'), ('other', 'Egyéb')], default='other', max_length=50, verbose_name='Kategória'),
        ),
    ]
