# Generated by Django 4.2.7 on 2026-03-16 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_material_vat_type_id'),
        ('manufacturing', '0031_calculatortemplate_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttemplate',
            name='calculators',
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='allowed_materials',
            field=models.ManyToManyField(blank=True, related_name='product_templates', to='warehouse.material', verbose_name='Engedélyezett alapanyagok'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='allowed_services',
            field=models.ManyToManyField(blank=True, related_name='product_templates', to='manufacturing.service', verbose_name='Engedélyezett szolgáltatások'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='calculator_type',
            field=models.CharField(blank=True, choices=[('generic', 'Általános'), ('sheet_print', 'Íves/Táblás optimalizálás'), ('roll_print', 'Tekercses kalkuláció')], default='generic', max_length=50, verbose_name='Működési logika'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='default_material_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alapanyag haszonkulcs %'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='default_service_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Szolgáltatás haszonkulcs %'),
        ),
    ]
