# Generated by Django 4.2.7 on 2026-03-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_material_vat_type_id'),
        ('manufacturing', '0032_producttemplate_calculator_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='allowed_material_groups',
            field=models.ManyToManyField(blank=True, related_name='product_templates', to='warehouse.materialgroup', verbose_name='Engedélyezett alapanyag kategóriák'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='custom_size_enabled',
            field=models.BooleanField(default=False, verbose_name='Egyedi méret engedélyezett'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='custom_size_height_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Egyedi M. max'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='custom_size_height_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Egyedi M. min'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='custom_size_unit',
            field=models.CharField(blank=True, choices=[('mm', 'mm'), ('cm', 'cm'), ('m', 'm')], default='mm', max_length=5, verbose_name='Egyedi méret egység'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='custom_size_width_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Egyedi Sz. max'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='custom_size_width_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Egyedi Sz. min'),
        ),
        migrations.AddField(
            model_name='producttemplatesize',
            name='unit',
            field=models.CharField(choices=[('mm', 'mm'), ('cm', 'cm'), ('m', 'm')], default='mm', max_length=5, verbose_name='Mértékegység'),
        ),
    ]
