# Generated by Django 4.2.7 on 2026-03-16 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0033_producttemplate_customsize_materialgroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplateServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('1', '1. oldal'), ('2', '2. oldal')], default='1', max_length=1, verbose_name='Oldal')),
                ('group_index', models.IntegerField(default=0, verbose_name='Csoport sorrend')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_groups', to='manufacturing.producttemplate', verbose_name='Termék sablon')),
                ('services', models.ManyToManyField(blank=True, related_name='template_service_groups', to='manufacturing.service', verbose_name='Szolgáltatások')),
            ],
            options={
                'verbose_name': 'Szolgáltatás csoport',
                'verbose_name_plural': 'Szolgáltatás csoportok',
                'ordering': ['side', 'group_index'],
            },
        ),
    ]
