# Generated by Django 4.2.7 on 2026-03-16 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0034_service_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pl. 1 vágással hány ívet lehet feldolgozni. 0 = korlátlan.', max_digits=10, null=True, verbose_name='Kapacitás (ív/vágás)'),
        ),
        migrations.AddField(
            model_name='service',
            name='max_height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0 = korlátlan / végtelen', max_digits=10, null=True, verbose_name='Max magasság (mm)'),
        ),
        migrations.AddField(
            model_name='service',
            name='max_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0 = korlátlan / végtelen', max_digits=10, null=True, verbose_name='Max szélesség (mm)'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_type',
            field=models.CharField(blank=True, choices=[('per_sheet', 'Ívenként'), ('per_job', 'Munkánként (flat)'), ('per_cut', 'Vágásonként (kapacitással)')], default='per_sheet', max_length=20, verbose_name='Árazás típusa'),
        ),
        migrations.AddField(
            model_name='service',
            name='setup_cost_selling',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fix beállítási / indítási díj, egyszer számolódik munkánként', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Beállítási díj (eladási Ft)'),
        ),
        migrations.AddField(
            model_name='service',
            name='unit_cost_selling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Egységköltség (eladási Ft / ív|db|vágás)'),
        ),
    ]
