# Generated by Django 4.2.7 on 2026-03-17 20:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0035_service_pricing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplateQuantityDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField(default=1, verbose_name='Min. mennyiség (db-tól)')),
                ('discount_type', models.CharField(choices=[('percent', 'Százalékos (%)'), ('fixed', 'Fix összeg (Ft)')], default='percent', max_length=10, verbose_name='Kedvezmény típusa')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kedvezmény értéke')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_discounts', to='manufacturing.producttemplate', verbose_name='Termék sablon')),
            ],
            options={
                'verbose_name': 'Mennyiségi kedvezmény',
                'verbose_name_plural': 'Mennyiségi kedvezmények',
                'ordering': ['min_quantity'],
            },
        ),
    ]
