# Generated by Django 4.2.7 on 2026-03-18 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0036_producttemplate_quantity_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttemplatequantitydiscount',
            options={'ordering': ['min_amount'], 'verbose_name': 'Összeghatáros kedvezmény', 'verbose_name_plural': 'Összeghatáros kedvezmények'},
        ),
        migrations.RemoveField(
            model_name='producttemplatequantitydiscount',
            name='min_quantity',
        ),
        migrations.AddField(
            model_name='producttemplatequantitydiscount',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min. rendelési összeg (Ft-tól)'),
        ),
    ]
