# Generated by Django 4.2.7 on 2026-03-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0037_amount_discount_replace_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='print_service',
            field=models.ForeignKey(blank=True, help_text='Az íves nyomtatáshoz rendelt szolgáltatás (pl. Fekete-fehér íves nyomtatás). Ha klikkdíjas, a klikk díjjal számol.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_service_templates', to='manufacturing.service', verbose_name='Nyomtatási szolgáltatás'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='print_sides',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Egyoldalas (simplex)'), (2, 'Kétoldalas (duplex)')], default=1, help_text='1 = simplex, 2 = duplex. Klikkdíjas számításnál 1 ív = 1×sides klikk.', verbose_name='Nyomtatás oldalak száma'),
        ),
        migrations.AlterField(
            model_name='service',
            name='calculation_unit',
            field=models.CharField(blank=True, choices=[('db', 'darab'), ('m', 'folyóméter'), ('m2', 'négyzetméter'), ('kg', 'kilogramm'), ('hour', 'óra'), ('perimeter', 'kerület (méter)'), ('click', 'klikk (klikkdíjas)'), ('minute', 'perc')], default='db', help_text='Ha eltér az alap mértékegységtől, a rendszer átváltja. Klikkdíjas esetén az ív nyomtatási klikkszám alapján számol.', max_length=20, verbose_name='Kalkulációs mértékegység'),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.CharField(choices=[('db', 'darab'), ('m', 'folyóméter'), ('m2', 'négyzetméter'), ('kg', 'kilogramm'), ('hour', 'óra'), ('perimeter', 'kerület (méter)'), ('click', 'klikk (klikkdíjas)')], default='db', max_length=20, verbose_name='Mértékegység'),
        ),
        migrations.AlterField(
            model_name='servicecostitem',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Fix költség'), ('unit', 'Darab alapú'), ('click', 'Klikkdíjas (ív-produkció alapú)'), ('length', 'Folyóméter'), ('perimeter', 'Kerület'), ('area', 'Terület'), ('weight', 'Súly'), ('time', 'Idő')], default='unit', max_length=20, verbose_name='Számítás típusa'),
        ),
    ]
