# Generated by Django 4.2.7 on 2026-03-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0038_print_settings_click_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='print_service_options',
            field=models.ManyToManyField(blank=True, help_text='Válasszon klikkdíjas nyomtatási szolgáltatásokat (pl. Konica 1 old. színes, Konica 2 old. FH). A felhasználó ezek közül választ a PrintEditorban.', related_name='click_print_product_templates', to='manufacturing.service', verbose_name='Klikkdíjas nyomtatási opciók'),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='calculator_type',
            field=models.CharField(blank=True, choices=[('generic', 'Általános'), ('sheet_print', 'Íves/Táblás optimalizálás'), ('roll_print', 'Tekercses kalkuláció'), ('click_sheet_print', 'Klikkdíjas íves nyomtatás')], default='generic', max_length=50, verbose_name='Működési logika'),
        ),
    ]
