# Generated by Django 4.2.7 on 2026-03-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0039_click_sheet_print_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='fix_cost_first_side_only',
            field=models.BooleanField(default=False, help_text='Ha igaz, 2 oldalas nyomtatásnál a fix költségeket csak az 1. oldalra számolja.', verbose_name='Fix költségek csak az 1. oldalra'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='print_service_options_order',
            field=models.JSONField(blank=True, default=list, help_text='A print_service_options M2M mezőhöz tartozó rendezési sorrend (ID-k listája).', verbose_name='Klikkdíjas opciók sorrendje'),
        ),
        migrations.AlterField(
            model_name='service',
            name='calculation_unit',
            field=models.CharField(blank=True, choices=[('db', 'darab'), ('m', 'folyóméter'), ('m2', 'négyzetméter'), ('kg', 'kilogramm'), ('hour', 'óra'), ('perimeter', 'kerület (méter)'), ('sheet', 'ív (ív alapú)'), ('click', 'klikk (klikkdíjas)'), ('minute', 'perc')], default='db', help_text='Ha eltér az alap mértékegységtől, a rendszer átváltja. Klikkdíjas esetén az ív nyomtatási klikkszám alapján számol.', max_length=20, verbose_name='Kalkulációs mértékegység'),
        ),
        migrations.AlterField(
            model_name='service',
            name='unit',
            field=models.CharField(choices=[('db', 'darab'), ('m', 'folyóméter'), ('m2', 'négyzetméter'), ('kg', 'kilogramm'), ('hour', 'óra'), ('perimeter', 'kerület (méter)'), ('sheet', 'ív (ív alapú)'), ('click', 'klikk (klikkdíjas)')], default='db', max_length=20, verbose_name='Mértékegység'),
        ),
    ]
