# Generated by Django 4.2.7 on 2026-03-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0040_add_print_options_order_and_fix_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='required_services',
            field=models.ManyToManyField(blank=True, related_name='required_for_templates', to='manufacturing.service', verbose_name='Kötelező kapcsolódó szolgáltatások'),
        ),
    ]
