# Generated by Django 4.2.7 on 2026-03-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0041_producttemplate_required_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='finishing_services',
            field=models.ManyToManyField(blank=True, related_name='finishing_for_templates', to='manufacturing.service', verbose_name='Kész termékre vonatkozó szolgáltatások'),
        ),
    ]
