# Generated by Django 4.2.7 on 2026-03-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0042_producttemplate_finishing_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttemplateservicegroup',
            name='side',
            field=models.CharField(choices=[('1', '1. oldal'), ('2', '2. oldal'), ('F', 'Kész termék')], default='1', max_length=1, verbose_name='Oldal'),
        ),
    ]
