# Generated by Django 4.2.7 on 2026-03-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0043_alter_producttemplateservicegroup_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='multi_sheet_enabled',
            field=models.BooleanField(default=False, help_text='Ha igaz, a felhasználó több ívet (oldalt) adhat a megrendeléshez.', verbose_name='Több ív engedélyezése'),
        ),
    ]
