# Generated by Django 4.2.7 on 2026-04-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0044_add_multi_sheet_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Védett szolgáltatások nem törölhetők. Rendszer-szintű kalkulációhoz szükségesek.', verbose_name='Védett'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Védett csoport és benne lévő szolgáltatások nem törölhetők.', verbose_name='Védett'),
        ),
    ]
