# Generated by Django 4.2.7 on 2026-04-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printshop', '0006_print_templates'),
        ('manufacturing', '0046_populate_protected_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='template_categories',
            field=models.ManyToManyField(blank=True, help_text='Válaszd ki, mely sablon kategóriák jelenjenek meg a Print Editorban ennél a terméknél.', related_name='product_templates', to='printshop.printtemplatecategory', verbose_name='Sablon kategóriák'),
        ),
    ]
