# Generated by Django 4.2.7 on 2026-04-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0047_add_template_categories_to_product_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingcostitem',
            name='currency',
            field=models.CharField(default='HUF', max_length=3, verbose_name='Pénznem'),
        ),
        migrations.AddField(
            model_name='manufacturingcostitem',
            name='is_per_unit',
            field=models.BooleanField(default=False, verbose_name='Egységre vetített'),
        ),
    ]
