# Generated by Django 4.2.7 on 2026-04-24 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturing', '0048_add_currency_is_per_unit_to_costitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingProductAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='manufacturing_products/%Y/%m/%d/', verbose_name='Fájl')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltve')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='manufacturing.manufacturingproduct', verbose_name='Termék')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Feltöltötte')),
            ],
            options={
                'verbose_name': 'Gyártási termék csatolmány',
                'verbose_name_plural': 'Gyártási termék csatolmányok',
            },
        ),
    ]
