# Generated by Django 4.2.7 on 2026-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0049_add_manufacturing_product_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingproduct',
            name='price_from_cost_calc',
            field=models.BooleanField(default=True, verbose_name='Ár az árkalkulációból'),
        ),
    ]
