# Generated by Django 4.2.7 on 2026-04-29 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0050_price_from_cost_calc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturingcostitem',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Gyártási költség elem', 'verbose_name_plural': 'Gyártási költség elemek'},
        ),
        migrations.AddField(
            model_name='manufacturingcostitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='manufacturing.manufacturingcostitem', verbose_name='Szülő költség'),
        ),
        migrations.AddField(
            model_name='manufacturingcostitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sorrend'),
        ),
    ]
