# Generated by Django 4.2.7 on 2026-04-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0051_alter_manufacturingcostitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingcostitem',
            name='status',
            field=models.CharField(choices=[('new', 'Új'), ('confirmed', 'Megerősítve'), ('in_production', 'Gyártásban'), ('ready', 'Kész'), ('in_delivery', 'Szállítás alatt'), ('delivered', 'Kiszállítva'), ('cancelled', 'Törölve')], default='new', max_length=20, verbose_name='Státusz'),
        ),
    ]
