# Generated by Django 4.2.7 on 2026-04-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0052_manufacturingcostitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingcostitem',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='Szünetel'),
        ),
        migrations.AddField(
            model_name='manufacturingcostitem',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Megjegyzések'),
        ),
        migrations.AddField(
            model_name='manufacturingcostitem',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Sorhely'),
        ),
    ]
