# Generated by Django 4.2.7 on 2026-04-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0053_manufacturingcostitem_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingcostitem',
            name='supplier_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Beszállítói e-mail kiküldve'),
        ),
    ]
