# Generated by Django 4.2.7 on 2026-05-05 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturing', '0054_manufacturingcostitem_supplier_email_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingCostItemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cost_item_attachments/%Y/%m/%d/', verbose_name='Fájl')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='Megjegyzés')),
                ('storage_file_id', models.IntegerField(blank=True, null=True, verbose_name='Storage fájl ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltve')),
                ('cost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='manufacturing.manufacturingcostitem', verbose_name='Költség elem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Feltöltötte')),
            ],
            options={
                'verbose_name': 'Költség elem csatolmány',
                'verbose_name_plural': 'Költség elem csatolmányok',
            },
        ),
    ]
