# Generated by Django 4.2.7 on 2026-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0055_costitem_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingproduct',
            name='printshop_params',
            field=models.JSONField(blank=True, null=True, verbose_name='PrintShop paraméterek'),
        ),
    ]
