# Generated by Django 4.2.7 on 2026-05-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0057_formulas_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Védett terméksablon nem törölhető. Minden termékkategóriában az alapminta.', verbose_name='Védett'),
        ),
    ]
