# Generated by Django 4.2.7 on 2026-05-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0058_product_template_is_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingproduct',
            name='kind',
            field=models.CharField(choices=[('manufacturing', 'Egyedi gyártás'), ('service', 'Szolgáltatás')], db_index=True, default='manufacturing', max_length=20, verbose_name='Típus'),
        ),
        migrations.AddField(
            model_name='manufacturingproduct',
            name='source_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='manufacturing.service', verbose_name='Forrás szolgáltatás sablon'),
        ),
    ]
