# Generated by Django 4.2.7 on 2026-05-11 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_taskconfiguration_due_month_of_year'),
        ('manufacturing', '0059_manufacturingproduct_kind_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingproduct',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='manufacturingproduct',
            name='source_service',
        ),
        migrations.AddField(
            model_name='servicecostitem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_cost_items', to='hr.department', verbose_name='HR Osztály (belső gyártásnál)'),
        ),
        migrations.AddField(
            model_name='servicecostitem',
            name='price_calculation_version',
            field=models.CharField(blank=True, default='1. verzió', help_text='Azonos verziónév alá tartozó költségelemek együtt adnak egy egységárat', max_length=100, verbose_name='Árkalkulációs verzió'),
        ),
        migrations.AddField(
            model_name='servicecostitem',
            name='price_quantity',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Az ár hány szolgáltatás mértékegységre vonatkozik. Pl. 10 darabos árnál 10.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Ár mennyisége'),
        ),
    ]
