# Generated by Django 4.2.7 on 2026-05-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0060_service_cost_item_version_dept_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_price_calculation_version',
            field=models.CharField(blank=True, default='', help_text='Melyik árkalkulációs verzió alapján számolja a nettó egységárat', max_length=100, verbose_name='Alapértelmezett árkalkulációs verzió'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_source_mode',
            field=models.CharField(choices=[('manual', 'Kézi nettó egységár'), ('default_version', 'Alapértelmezett árkalkuláció'), ('optimal_version', 'Optimális árkalkuláció')], default='manual', max_length=20, verbose_name='Ár forrása'),
        ),
    ]
