# Generated by Django 4.2.7 on 2026-05-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0061_service_price_source_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingcostitemattachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Eredeti fájlnév'),
        ),
    ]
