# Generated by Django 4.2.7 on 2026-05-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0062_manufacturingcostitemattachment_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingcostitemattachment',
            name='is_documentation',
            field=models.BooleanField(default=False, verbose_name='Kész dokumentáció'),
        ),
    ]
