# Generated by Django 4.2.7 on 2026-05-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0063_manufacturingcostitemattachment_is_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingcostitem',
            name='status',
            field=models.CharField(choices=[('new', 'Új'), ('confirmed', 'Megerősítve'), ('sent', 'Kiküldve'), ('in_production', 'Gyártásban'), ('ready', 'Kész'), ('in_delivery', 'Szállítás alatt'), ('delivered', 'Kiszállítva'), ('cancelled', 'Törölve')], default='new', max_length=20, verbose_name='Státusz'),
        ),
    ]
