# Generated by Django 4.2.7 on 2026-05-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0065_add_ordered_status_to_costitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingcostitem',
            name='status',
            field=models.CharField(choices=[('new', 'Új'), ('sent', 'Kiküldve'), ('ordered', 'Megrendelve'), ('confirmed', 'Megerősítve'), ('in_production', 'Gyártásban'), ('ready', 'Kész'), ('in_delivery', 'Szállítás alatt'), ('delivered', 'Kiszállítva'), ('rejected', 'Elutasítva'), ('cancelled', 'Törölve')], default='new', max_length=20, verbose_name='Státusz'),
        ),
    ]
