# Generated by Django 4.2.7 on 2026-05-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0066_add_rejected_to_cost_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroup',
            name='code',
            field=models.CharField(blank=True, help_text='Rendszer-azonosító kód (pl. PRINT_DIGIPRINT_CLICK).', max_length=50, null=True, unique=True, verbose_name='Kód'),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='calculator_type',
            field=models.CharField(blank=True, choices=[('generic', 'Általános'), ('sheet_print', 'Íves/Táblás optimalizálás'), ('roll_print', 'Tekercses kalkuláció'), ('click_sheet_print', 'Klikkdíjas íves nyomtatás'), ('screen_print', 'Szitanyomás'), ('pad_print', 'Tamponnyomás')], default='generic', max_length=50, verbose_name='Működési logika'),
        ),
    ]
