# Generated by Django 4.2.7 on 2026-05-31 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0067_servicegroup_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='service_group',
            field=models.ForeignKey(blank=True, help_text='A nyomtatási mód szolgáltatás-csoportja; ennek alkategóriái (Nyomtatás, Kötelező, Utómunka, Kész termékre) töltik a szerkesztő select-jeit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_templates_for_group', to='manufacturing.servicegroup', verbose_name='Nyomtatási mód szolgáltatás-csoport'),
        ),
    ]
