# Generated by Django 4.2.7 on 2026-05-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0068_producttemplate_service_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='binding_services',
            field=models.ManyToManyField(blank=True, help_text='A termékhez választható kötészeti módok (pl. Ívben, Irkatűzött, Spirálozott). A felhasználó a Print Editorban választ közülük.', related_name='binding_for_templates', to='manufacturing.service', verbose_name='Kötészeti módok'),
        ),
    ]
