# Generated by Django 4.2.7 on 2026-05-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0069_producttemplate_binding_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='image',
            field=models.ImageField(blank=True, help_text='A termékkatalógus oldalon megjelenő kép.', null=True, upload_to='manufacturing/product_templates/', verbose_name='Katalógus kép'),
        ),
    ]
