# Generated by Django 4.2.7 on 2026-06-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0070_producttemplate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='image',
            field=models.ImageField(blank=True, help_text='A termékkatalógus oldalon megjelenő kategória kép.', null=True, upload_to='manufacturing/product_classes/', verbose_name='Kategória kép'),
        ),
    ]
