# Generated by Django 4.2.7 on 2026-06-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0071_productclass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Határidő'),
        ),
    ]
