# Generated by Django 4.2.7 on 2026-07-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0072_deadline_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplatesize',
            name='grip_height_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ívfogás miatti redukció hosszúságban mm-ben — csökkenti a nyomtatható területet', max_digits=8, verbose_name='Hosszúsági ívfogás (mm)'),
        ),
        migrations.AddField(
            model_name='producttemplatesize',
            name='grip_width_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ívfogás miatti redukció szélességben mm-ben — csökkenti a nyomtatható területet', max_digits=8, verbose_name='Szélességi ívfogás (mm)'),
        ),
    ]
