# Generated by Django 4.2.7 on 2026-07-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0073_producttemplatesize_grip_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttemplatesize',
            name='grip_height_mm',
        ),
        migrations.RemoveField(
            model_name='producttemplatesize',
            name='grip_width_mm',
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='grip_height_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ívfogás miatti redukció hosszúságban — minden méretre és az egyedi méretre is vonatkozik', max_digits=8, verbose_name='Hosszúsági ívfogás (mm)'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='grip_width_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ívfogás miatti redukció szélességben — minden méretre és az egyedi méretre is vonatkozik', max_digits=8, verbose_name='Szélességi ívfogás (mm)'),
        ),
    ]
