# Generated by Django 4.2.7 on 2026-07-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0074_producttemplate_grip_fields_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='allow_custom_cost',
            field=models.BooleanField(default=False, help_text='Engedélyezi, hogy a kalkulátor oldalon egyedi költséget lehessen megadni.', verbose_name='Egyedi költség engedélyezése'),
        ),
    ]
