# Generated by Django 4.2.7 on 2026-08-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0075_add_allow_custom_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='screen_print_colors',
            field=models.PositiveSmallIntegerField(default=1, help_text='Szitanyomás kalkulátornál: hány szín kerül nyomtatásra (1-6). Csak screen_print típusnál aktív.', verbose_name='Szitanyomás színek száma'),
        ),
    ]
