# Generated by Django 4.2.7 on 2026-09-06 21:14

import apps.manufacturing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0076_screen_print_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplateGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.manufacturing.models._product_template_gallery_path, verbose_name='Kép')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='manufacturing.producttemplate', verbose_name='Termék sablon')),
            ],
            options={
                'verbose_name': 'Termék galéria kép',
                'verbose_name_plural': 'Termék galéria képek',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
