# Generated by Django 4.2.7 on 2026-09-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0077_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='public_description',
            field=models.TextField(blank=True, default='', help_text='A portálon megjelenő formázott termékleírás (HTML formátumban).', verbose_name='Publikus leírás (HTML)'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='youtube_url',
            field=models.CharField(blank=True, default='', help_text='Opcionális YouTube videó URL a publikus termékleíráshoz.', max_length=500, verbose_name='YouTube videó URL'),
        ),
    ]
