# Generated by Django 4.2.7 on 2025-09-05 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ügyfél neve')),
                ('company', models.CharField(max_length=200, verbose_name='Cég neve')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Cím')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='Adószám')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Kapcsolattartó')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ügyfél',
                'verbose_name_plural': 'Ügyfelek',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('expected_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Megrendelés szám')),
                ('status', models.CharField(choices=[('draft', 'Vázlat'), ('confirmed', 'Megerősítve'), ('in_production', 'Gyártásban'), ('completed', 'Kész'), ('shipped', 'Szállítva'), ('delivered', 'Kiszállítva'), ('cancelled', 'Törölve')], default='draft', max_length=20, verbose_name='Státusz')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Összeg')),
                ('delivery_date', models.DateField(verbose_name='Szállítási dátum')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Készítette')),
            ],
            options={
                'verbose_name': 'Megrendelés',
                'verbose_name_plural': 'Megrendelések',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Termék neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('unit', models.CharField(max_length=20, verbose_name='Mértékegység')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alapár')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Termék',
                'verbose_name_plural': 'Termékek',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=50, unique=True, verbose_name='Ajánlat szám')),
                ('status', models.CharField(choices=[('draft', 'Vázlat'), ('sent', 'Elküldve'), ('accepted', 'Elfogadva'), ('partially_accepted', 'Részben elfogadva'), ('rejected', 'Elutasítva'), ('expired', 'Lejárt')], default='draft', max_length=20, verbose_name='Státusz')),
                ('valid_until', models.DateField(verbose_name='Érvényes eddig')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Összeg')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Készítette')),
            ],
            options={
                'verbose_name': 'Ajánlat',
                'verbose_name_plural': 'Ajánlatok',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True, verbose_name='Kérés szám')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('description', models.TextField(verbose_name='Leírás')),
                ('status', models.CharField(choices=[('new', 'Új'), ('in_progress', 'Feldolgozás alatt'), ('quoted', 'Ajánlat kész'), ('accepted', 'Elfogadva'), ('rejected', 'Elutasítva'), ('expired', 'Lejárt')], default='new', max_length=20, verbose_name='Státusz')),
                ('deadline', models.DateField(verbose_name='Határidő')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer', verbose_name='Ügyfél')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kérte')),
            ],
            options={
                'verbose_name': 'Ajánlat kérés',
                'verbose_name_plural': 'Ajánlat kérések',
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Egységár')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Összár')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Elfogadva')),
                ('accepted_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Elfogadott mennyiség')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product', verbose_name='Termék')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quote', verbose_name='Ajánlat')),
            ],
            options={
                'verbose_name': 'Ajánlat tétel',
                'verbose_name_plural': 'Ajánlat tételek',
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.quoterequest', verbose_name='Ajánlat kérés'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Egységár')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Összár')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='Megrendelés')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Megrendelés tétel',
                'verbose_name_plural': 'Megrendelés tételek',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.quote', verbose_name='Ajánlat'),
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('probability', models.IntegerField()),
                ('expected_close_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.lead')),
            ],
        ),
    ]
