# Generated by Django 4.2.7 on 2025-09-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_manufacturingproduct_currency_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.project', verbose_name='Projekt'),
        ),
        migrations.CreateModel(
            name='QuoteRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Termék'), ('manufacturing', 'Egyedi gyártás')], max_length=20, verbose_name='Tétel típusa')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Mennyiség')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturing_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.manufacturingproduct', verbose_name='Gyártási termék')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.product', verbose_name='Termék')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quoterequest', verbose_name='Ajánlatkérés')),
            ],
            options={
                'verbose_name': 'Ajánlatkérés tétel',
                'verbose_name_plural': 'Ajánlatkérés tételek',
            },
        ),
    ]
