# Generated by Django 4.2.7 on 2025-09-13 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_company_company_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_quoterequest_project_quoterequestitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Cikkszám')),
                ('name', models.CharField(max_length=200, verbose_name='Szolgáltatás neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('unit', models.CharField(default='óra', max_length=20, verbose_name='Mértékegység')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Alap nettó ár')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Szolgáltatás',
                'verbose_name_plural': 'Szolgáltatások',
            },
        ),
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'verbose_name': 'Árajánlat', 'verbose_name_plural': 'Árajánlatok'},
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company', verbose_name='Cég (CRM)'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='crm.contact', verbose_name='Kapcsolattartók'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Rögzítette'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='issue_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Keltezés'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Ajánlat száma'),
        ),
        migrations.AddField(
            model_name='quoterequestitem',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bruttó összesen'),
        ),
        migrations.AddField(
            model_name='quoterequestitem',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Nettó összesen'),
        ),
        migrations.AddField(
            model_name='quoterequestitem',
            name='net_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Nettó egységár'),
        ),
        migrations.AddField(
            model_name='quoterequestitem',
            name='unit',
            field=models.CharField(default='db', max_length=20, verbose_name='Mennyiségi egység'),
        ),
        migrations.AddField(
            model_name='quoterequestitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=27.0, max_digits=5, verbose_name='ÁFA %'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.customer', verbose_name='Ügyfél'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='request_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Kérés szám'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Kérte'),
        ),
        migrations.AlterField(
            model_name='quoterequestitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Termék'), ('manufacturing', 'Egyedi gyártás'), ('service', 'Szolgáltatás')], max_length=20, verbose_name='Tétel típusa'),
        ),
        migrations.CreateModel(
            name='QuoteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sales.quoterequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Árajánlat napló',
                'verbose_name_plural': 'Árajánlat naplók',
            },
        ),
        migrations.AddField(
            model_name='quoterequestitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.service', verbose_name='Szolgáltatás'),
        ),
    ]
