# Generated by Django 4.2.7 on 2025-09-13 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_service_alter_quoterequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kedvezmény (fix)'),
        ),
        migrations.AddField(
            model_name='quoterequestitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Kedvezmény %'),
        ),
        migrations.AddField(
            model_name='quoterequestitem',
            name='discounted_gross_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kedvezményes bruttó összesen'),
        ),
        migrations.AddField(
            model_name='quoterequestitem',
            name='discounted_net_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kedvezményes nettó összesen'),
        ),
        migrations.CreateModel(
            name='SearchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Termék'), ('service', 'Szolgáltatás'), ('manufacturing', 'Egyedi gyártás')], max_length=20)),
                ('ref_id', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
                ('last_hit', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keresési statisztika',
                'verbose_name_plural': 'Keresési statisztikák',
                'unique_together': {('item_type', 'ref_id')},
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestItemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quote_items/%Y/%m/%d/')),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sales.quoterequestitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajánlat tétel csatolmány',
                'verbose_name_plural': 'Ajánlat tétel csatolmányok',
            },
        ),
    ]
