# Generated by Django 4.2.7 on 2025-09-13 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_quoterequestitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Ügyfél', 'verbose_name_plural': 'Ügyfelek'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Megrendelés', 'verbose_name_plural': 'Megrendelések'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Termék', 'verbose_name_plural': 'Termékek'},
        ),
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Árajánlat', 'verbose_name_plural': 'Árajánlatok'},
        ),
    ]
