# Generated by Django 4.2.7 on 2025-09-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_quoterequestattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Szolgáltatás', 'verbose_name_plural': 'Szolgáltatások'},
        ),
    ]
