# Generated by Django 4.2.7 on 2025-09-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_public_token_email_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoterequestemaillog',
            options={'verbose_name': 'Árajánlat e-mail napló', 'verbose_name_plural': 'Árajánlat e-mail naplók'},
        ),
        migrations.AlterField(
            model_name='quoterequestemaillog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
