# Generated by Django 4.2.7 on 2025-09-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_owner_invitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequestinvitation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
