# Generated by Django 4.2.7 on 2026-01-04 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_make_material_type_optional'),
        ('sales', '0013_alter_quoterequestinvitation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='warehouse.material', verbose_name='Alapanyag/Termék'),
        ),
    ]
