# Generated by Django 4.2.7 on 2026-01-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_add_material_to_quote_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Határidő'),
        ),
    ]
