# Generated by Django 4.2.7 on 2026-01-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_make_deadline_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='internal_description',
            field=models.TextField(blank=True, verbose_name='Belső leírás'),
        ),
    ]
