# Generated by Django 4.2.7 on 2026-01-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_quoterequest_internal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='partial_order_allowed',
            field=models.BooleanField(default=True, verbose_name='Részlegesen megrendelhető'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'Új'), ('in_progress', 'Feldolgozás alatt'), ('quoted', 'Ajánlat kész'), ('accepted', 'Elfogadva'), ('rejected', 'Elutasítva'), ('expired', 'Lejárt'), ('archived', 'Archív'), ('ordered', 'Megrendelve')], default='new', max_length=20, verbose_name='Státusz'),
        ),
    ]
