# Generated by Django 4.2.7 on 2026-01-04 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0017_quoterequest_partial_order_allowed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Megrendelés szám')),
                ('status', models.CharField(choices=[('new', 'Új'), ('confirmed', 'Megerősítve'), ('in_production', 'Gyártásban'), ('ready', 'Kész'), ('in_delivery', 'Szállítás alatt'), ('delivered', 'Kiszállítva'), ('cancelled', 'Törölve')], default='new', max_length=20, verbose_name='Státusz')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Megrendelés dátuma')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Megerősítve')),
                ('production_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Gyártás kezdete')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Kész')),
                ('delivery_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Szállítás kezdete')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Kiszállítva')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='sales.quoterequest', verbose_name='Árajánlat')),
            ],
            options={
                'verbose_name': 'Ügyfél megrendelés',
                'verbose_name_plural': 'Ügyfél megrendelések',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Vázlat'), ('sent', 'Elküldve'), ('accepted', 'Elfogadva'), ('rejected', 'Elutasítva'), ('expired', 'Lejárt')], default='draft', max_length=20, verbose_name='Státusz'),
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség')),
                ('unit', models.CharField(max_length=20, verbose_name='Egység')),
                ('net_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nettó egységár')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=27, max_digits=5, verbose_name='ÁFA %')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Kedvezmény %')),
                ('description', models.TextField(blank=True, default='', verbose_name='Leírás')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.customerorder', verbose_name='Megrendelés')),
                ('quote_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.quoterequestitem', verbose_name='Ajánlat tétel')),
            ],
            options={
                'verbose_name': 'Megrendelés tétel',
                'verbose_name_plural': 'Megrendelés tételek',
            },
        ),
    ]
