# Generated by Django 4.2.7 on 2026-01-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_customerorder_alter_quote_status_customerorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='delivery_confirmed',
            field=models.BooleanField(default=False, verbose_name='Szállítólevél visszaigazolva'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visszaigazolás ideje'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='delivery_notes',
            field=models.TextField(blank=True, default='', verbose_name='Szállítási megjegyzések'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='public_delivery_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publikus szállítás link lejár'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='public_delivery_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Publikus szállítás token'),
        ),
    ]
