# Generated by Django 4.2.7 on 2026-01-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_customerorder_delivery_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='show_prices',
            field=models.BooleanField(default=True, verbose_name='Árak láthatóak a szállítólevélen'),
        ),
    ]
