# Generated by Django 4.2.7 on 2026-01-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_customerorder_show_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Számla szám'),
        ),
    ]
