# Generated by Django 4.2.7 on 2026-01-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0014_alter_servicecostitem_markup_percentage'),
        ('sales', '0021_customerorder_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequestitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.service', verbose_name='Szolgáltatás'),
        ),
    ]
