# Generated by Django 4.2.7 on 2026-01-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_materialsupplier_supplier_external_id'),
        ('crm', '0008_contact_external_id'),
        ('sales', '0022_alter_quoterequestitem_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequestCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Cikkszám')),
                ('name', models.CharField(max_length=200, verbose_name='Megnevezés')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Mennyiség')),
                ('unit', models.CharField(default='db', max_length=20, verbose_name='Egység')),
                ('net_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Nettó egységár')),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Nettó összesen')),
                ('is_stock', models.BooleanField(default=False, verbose_name='Raktári')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.material', verbose_name='Alapanyag')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='sales.quoterequest', verbose_name='Ajánlat')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_costs', to='crm.company', verbose_name='Beszállító')),
            ],
            options={
                'verbose_name': 'Ajánlat költség',
                'verbose_name_plural': 'Ajánlat költségek',
            },
        ),
    ]
