# Generated by Django 4.2.7 on 2026-01-18 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0023_quoterequestcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(max_length=200, verbose_name='Munkafolyamat')),
                ('started_at', models.DateTimeField(verbose_name='Kezdés')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Befejezés')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Időtartam (mp)')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='sales.customerorder', verbose_name='Megrendelés')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customerorderitem', verbose_name='Tétel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Munkanapló',
                'verbose_name_plural': 'Munkanaplók',
                'ordering': ['-started_at'],
            },
        ),
    ]
