# Generated by Django 4.2.7 on 2026-01-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_chatmessage_chatthread_chatmessageattachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoterequestitem',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Ajánlatkérés tétel', 'verbose_name_plural': 'Ajánlatkérés tételek'},
        ),
        migrations.AddField(
            model_name='quoterequestitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sales.quoterequestitem', verbose_name='Szülő tétel'),
        ),
        migrations.AddField(
            model_name='quoterequestitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sorrend'),
        ),
    ]
