# Generated by Django 4.2.7 on 2026-01-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_alter_quoterequestitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='delivery_note_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Szállítólevél sorszám'),
        ),
    ]
