# Generated by Django 4.2.7 on 2026-01-26 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_company_vat_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0027_customerorder_delivery_note_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_number', models.CharField(max_length=50, unique=True, verbose_name='Szállítólevél száma')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Kiállítás dátuma')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Szállítás dátuma')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Visszaigazolva')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Visszaigazolás ideje')),
                ('confirmed_by_info', models.CharField(blank=True, max_length=255, verbose_name='Visszaigazolta (Külső/Egyéb)')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Elutasítás oka')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('public_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('public_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Visszaigazolta (Belső)')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact', verbose_name='Kapcsolattartó')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company', verbose_name='Ügyfél (CRM)')),
            ],
            options={
                'verbose_name': 'Szállítólevél',
                'verbose_name_plural': 'Szállítólevelek',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Szállított mennyiség')),
                ('item_name', models.CharField(blank=True, max_length=255, verbose_name='Tétel neve')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Egység')),
                ('net_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Nettó egységár')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='sales.customerorderitem', verbose_name='Megrendelés tétel')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.deliverynote', verbose_name='Szállítólevél')),
            ],
            options={
                'verbose_name': 'Szállítólevél tétel',
                'verbose_name_plural': 'Szállítólevél tételek',
            },
        ),
    ]
