# Generated by Django 4.2.7 on 2026-01-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_deliverynote_deliverynoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderitem',
            name='status',
            field=models.CharField(choices=[('new', 'Új'), ('confirmed', 'Megerősítve'), ('in_production', 'Gyártásban'), ('ready', 'Kész'), ('in_delivery', 'Szállítás alatt'), ('delivered', 'Kiszállítva'), ('cancelled', 'Törölve')], default='new', max_length=20, verbose_name='Státusz'),
        ),
    ]
