# Generated by Django 4.2.7 on 2026-02-03 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0029_customerorderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=50, verbose_name='Előző státusz')),
                ('requested_status', models.CharField(max_length=50, verbose_name='Kért státusz')),
                ('status', models.CharField(choices=[('pending', 'Jóváhagyásra vár'), ('approved', 'Jóváhagyva'), ('rejected', 'Visszaküldve')], default='pending', max_length=20, verbose_name='Kérelem státusza')),
                ('rejection_details', models.TextField(blank=True, verbose_name='Visszaküldés oka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='sales.customerorder', verbose_name='Megrendelés')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Kérelmező')),
            ],
            options={
                'verbose_name': 'Jóváhagyási kérelem',
                'verbose_name_plural': 'Jóváhagyási kérelmek',
                'ordering': ['-created_at'],
            },
        ),
    ]
