# Generated by Django 4.2.7 on 2026-02-13 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_company_external_id'),
        ('warehouse', '0020_materialgroup_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0030_approvalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kupon kód')),
                ('discount_type', models.CharField(choices=[('fixed', 'Fix összeg'), ('percent', 'Százalék')], max_length=10, verbose_name='Kedvezmény típusa')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kedvezmény értéke')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Érvényes ettől')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Érvényes eddig')),
                ('usage_limit', models.IntegerField(blank=True, null=True, verbose_name='Használati limit')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Használat száma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'POS kupon',
                'verbose_name_plural': 'POS kuponok',
            },
        ),
        migrations.CreateModel(
            name='POSCustomerIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=100, unique=True, verbose_name='QR kód')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utoljára használva')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_identifications', to='crm.company', verbose_name='Ügyfél')),
            ],
            options={
                'verbose_name': 'POS vásárló azonosítás',
                'verbose_name_plural': 'POS vásárló azonosítások',
            },
        ),
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=50, unique=True, verbose_name='Tranzakció száma')),
                ('transaction_type', models.CharField(choices=[('receipt', 'Nyugta'), ('invoice', 'Számla')], max_length=20, verbose_name='Tranzakció típusa')),
                ('payment_method', models.CharField(choices=[('cash', 'Készpénz'), ('card', 'Hitelkártya'), ('customer_card', 'Ügyfélkártya')], max_length=20, verbose_name='Fizetési mód')),
                ('status', models.CharField(choices=[('draft', 'Vázlat'), ('pending', 'Fizetés folyamatban'), ('completed', 'Befejezve'), ('failed', 'Sikertelen'), ('cancelled', 'Törölve')], default='draft', max_length=20, verbose_name='Státusz')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Ügyfél neve')),
                ('customer_address', models.TextField(blank=True, verbose_name='Ügyfél címe')),
                ('customer_tax_number', models.CharField(blank=True, max_length=20, verbose_name='Adószám')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('shopper_name', models.CharField(blank=True, max_length=200, verbose_name='Vásárló neve')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Részösszeg')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kedvezmény összege')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Nettó összesen')),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ÁFA összesen')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bruttó összesen')),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Átvett összeg')),
                ('amount_change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Visszajáró')),
                ('nav_invoice_number', models.CharField(blank=True, max_length=100, verbose_name='NAV számla szám')),
                ('nav_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='NAV tranzakció ID')),
                ('nav_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='NAV-nak küldve')),
                ('terminal_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Terminál tranzakció ID')),
                ('terminal_response', models.TextField(blank=True, verbose_name='Terminál válasz')),
                ('drawer_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Kasszafiók nyitva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Befejezve')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kinyomtatva')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pénztáros')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.poscoupon', verbose_name='Felhasznált kupon')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company', verbose_name='Ügyfél')),
                ('shopper_identification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.poscustomeridentification', verbose_name='Vásárló azonosítás')),
            ],
            options={
                'verbose_name': 'POS tranzakció',
                'verbose_name_plural': 'POS tranzakciók',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=50, verbose_name='Cikkszám')),
                ('product_name', models.CharField(max_length=200, verbose_name='Termék neve')),
                ('product_description', models.TextField(blank=True, verbose_name='Leírás')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mennyiség')),
                ('unit', models.CharField(max_length=20, verbose_name='Mértékegység')),
                ('gross_unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bruttó egységár')),
                ('net_unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nettó egységár')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ÁFA %')),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nettó összesen')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ÁFA összeg')),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bruttó összesen')),
                ('is_discounted', models.BooleanField(default=False, verbose_name='Kedvezményes')),
                ('original_gross_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Eredeti bruttó ár')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.material', verbose_name='Termék')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.postransaction', verbose_name='Tranzakció')),
            ],
            options={
                'verbose_name': 'POS tranzakció tétel',
                'verbose_name_plural': 'POS tranzakció tételek',
            },
        ),
        migrations.CreateModel(
            name='POSPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Összeg')),
                ('status', models.CharField(choices=[('pending', 'Folyamatban'), ('success', 'Sikeres'), ('failed', 'Sikertelen'), ('cancelled', 'Törölve')], default='pending', max_length=20, verbose_name='Státusz')),
                ('terminal_id', models.CharField(blank=True, max_length=50, verbose_name='Terminál ID')),
                ('terminal_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Terminál tranzakció ID')),
                ('terminal_response_code', models.CharField(blank=True, max_length=50, verbose_name='Terminál válasz kód')),
                ('terminal_response_message', models.TextField(blank=True, verbose_name='Terminál válasz üzenet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Befejezve')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.postransaction', verbose_name='Tranzakció')),
            ],
            options={
                'verbose_name': 'POS fizetés',
                'verbose_name_plural': 'POS fizetések',
                'ordering': ['-created_at'],
            },
        ),
    ]
