# Generated by Django 4.2.7 on 2026-04-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_pos_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestcost',
            name='currency_code',
            field=models.CharField(default='HUF', max_length=3, verbose_name='Pénznem'),
        ),
    ]
