# Generated by Django 4.2.7 on 2026-04-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_add_currency_code_to_quoterequestcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitem',
            name='imposition_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Impozíció adatok'),
        ),
    ]
