# Generated by Django 4.2.7 on 2026-05-04 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0054_manufacturingcostitem_supplier_email_sent_at'),
        ('sales', '0033_quoterequestitem_imposition_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='sub_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.manufacturingcostitem', verbose_name='Altétel'),
        ),
    ]
