# Generated by Django 4.2.7 on 2026-05-05 12:54

import apps.sales.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0034_worklog_add_sub_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.sales.models.order_attachment_upload_path, verbose_name='Fájl')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Eredeti fájlnév')),
                ('storage_file_id', models.IntegerField(blank=True, null=True, verbose_name='Storage fájl ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sales.customerorder', verbose_name='Megrendelés')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Feltöltötte')),
            ],
            options={
                'verbose_name': 'Megrendelés csatolmány',
                'verbose_name_plural': 'Megrendelés csatolmányok',
                'ordering': ['-created_at'],
            },
        ),
    ]
