# Generated by Django 4.2.7 on 2026-05-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_customer_order_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderattachment',
            name='remark',
            field=models.CharField(blank=True, max_length=500, verbose_name='Megjegyzés'),
        ),
        migrations.AddField(
            model_name='quoterequestattachment',
            name='storage_file_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Storage fájl ID'),
        ),
    ]
