# Generated by Django 4.2.7 on 2026-05-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_rfq_and_order_attachment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitemattachment',
            name='storage_file_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Storage fájl ID'),
        ),
    ]
