# Generated by Django 4.2.7 on 2026-05-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_quoteitem_attachment_storage_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderitem',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='Belső megjegyzés'),
        ),
    ]
