# Generated by Django 4.2.7 on 2026-05-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_customerorderitem_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='order_label',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Megrendelés megnevezése (szabad szöveges)'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='sales.customerorder', verbose_name='Megrendelés'),
        ),
    ]
