# Generated by Django 4.2.7 on 2026-05-08 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0039_worklog_nullable_order_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Megnevezés')),
                ('description', models.TextField(blank=True, default='', verbose_name='Leírás')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Mennyiség')),
                ('unit', models.CharField(default='db', max_length=20, verbose_name='Egység')),
                ('net_unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Eladási egységár')),
                ('cost_price', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Bekerülési ár')),
                ('cost_type', models.CharField(choices=[('customer', 'Ügyfél költsége'), ('own', 'Saját költség')], default='customer', max_length=10, verbose_name='Típus')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_works', to='sales.customerorder', verbose_name='Megrendelés')),
                ('customer_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_works', to='sales.customerorderitem', verbose_name='Tétel')),
            ],
            options={
                'verbose_name': 'Plusz munka',
                'verbose_name_plural': 'Plusz munkák',
                'ordering': ['created_at'],
            },
        ),
    ]
