# Generated by Django 4.2.7 on 2026-05-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_extra_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitem',
            name='formulas',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Képletek'),
        ),
    ]
