# Generated by Django 4.2.7 on 2026-05-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_customerorder_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitemattachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Eredeti fájlnév'),
        ),
    ]
