# Generated by Django 4.2.7 on 2026-05-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0063_manufacturingcostitemattachment_is_documentation'),
        ('sales', '0043_quoterequestitemattachment_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitemattachment',
            name='is_documentation',
            field=models.BooleanField(default=False, verbose_name='Kész dokumentáció'),
        ),
        migrations.CreateModel(
            name='DeliveryNoteDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_item_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.manufacturingcostitemattachment', verbose_name='Gyártási csatolmány')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_items', to='sales.deliverynote', verbose_name='Szállítólevél')),
                ('quote_item_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.quoterequestitemattachment', verbose_name='Ajánlat tétel csatolmány')),
            ],
            options={
                'verbose_name': 'Szállítólevél dokumentáció',
                'verbose_name_plural': 'Szállítólevél dokumentációk',
            },
        ),
    ]
