# Generated by Django 4.2.7 on 2026-05-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_quoterequestitemattachment_is_documentation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestattachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Eredeti fájlnév'),
        ),
    ]
