# Generated by Django 4.2.7 on 2026-05-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_quoterequestattachment_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitem',
            name='item_status',
            field=models.CharField(blank=True, choices=[('new', 'Új'), ('in_progress', 'Feldolgozás alatt'), ('quoted', 'Ajánlat kész'), ('accepted', 'Elfogadva'), ('rejected', 'Elutasítva'), ('ordered', 'Megrendelve'), ('archived', 'Archív')], default='new', max_length=20, verbose_name='Tétel státusz'),
        ),
    ]
