# Generated by Django 4.2.7 on 2026-05-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_quoterequestitem_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Érvényes'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='validity_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Érvényesség (nap)'),
        ),
    ]
