# Generated by Django 4.2.7 on 2026-05-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0052_pickuplocation_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP cím'),
        ),
    ]
