# Generated by Django 4.2.7 on 2026-06-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0053_quotelog_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Megrendelő IP-cím'),
        ),
    ]
