# Generated by Django 4.2.7 on 2026-06-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_customerorder_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitem',
            name='quote_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Ajánlatszám'),
        ),
    ]
