# Generated by Django 4.2.7 on 2026-06-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0056_backfill_item_quote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitem',
            name='internal_description',
            field=models.TextField(blank=True, default='', verbose_name='Belső leírás'),
        ),
    ]
