# Generated by Django 4.2.7 on 2026-06-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0057_add_internal_description_to_quoterequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitem',
            name='cost_items_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Közvetlen költségtételek'),
        ),
    ]
