# Generated by Django 4.2.7 on 2026-06-01 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0058_add_cost_items_data_to_quoterequestitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequestItemCostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_item_local_id', models.IntegerField(verbose_name='Altétel helyi ID (cost_items_data)')),
                ('file', models.FileField(upload_to='quote_cost_items/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_attachments', to='sales.quoterequestitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Direct altétel csatolmány',
                'verbose_name_plural': 'Direct altétel csatolmányok',
                'ordering': ['-created_at'],
            },
        ),
    ]
