# Generated by Django 4.2.7 on 2026-06-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0059_add_quoterequestitem_cost_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelog',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Metaadatok'),
        ),
    ]
