# Generated by Django 4.2.7 on 2026-06-05 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0060_quotelog_meta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='searchstat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_stats', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó'),
        ),
        migrations.AlterUniqueTogether(
            name='searchstat',
            unique_together={('item_type', 'ref_id', 'user')},
        ),
    ]
