# Generated by Django 4.2.7 on 2026-06-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0061_searchstat_add_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='imposition_presets',
            field=models.JSONField(blank=True, default=list, verbose_name='Impozíció presetek'),
        ),
    ]
