# Generated by Django 4.2.7 on 2026-06-18 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0064_quoterequest_manufacturable_marked_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='manufacturable_marked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gyárthatóvá jelölés ideje'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='manufacturable_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturable_marked_quote_requests', to=settings.AUTH_USER_MODEL, verbose_name='Gyárthatóvá tette'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'Új'), ('in_design', 'Tervezés alatt'), ('pending_customer_approval', 'Ügyfél jóváhagyásra vár'), ('pending_internal_approval', 'Belső jóváhagyásra vár'), ('in_progress', 'Feldolgozás alatt'), ('quoted', 'Ajánlat kész'), ('accepted', 'Elfogadva'), ('rejected', 'Elutasítva'), ('expired', 'Lejárt'), ('archived', 'Archív'), ('ordered', 'Megrendelve')], default='new', max_length=40, verbose_name='Státusz'),
        ),
    ]
