# Generated by Django 4.2.7 on 2026-06-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0066_quoterequest_primary_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='primary_delivery_note_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Elsődleges szállítólevél szám'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='primary_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Elsődleges kedvezmény %'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='primary_invoice_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Elsődleges számla szám'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='primary_item_description',
            field=models.TextField(blank=True, default='', verbose_name='Elsődleges tétel leírás'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='primary_item_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Elsődleges tétel neve'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='primary_net_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elsődleges nettó egységár'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='primary_order_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Elsődleges megrendelés szám'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='primary_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Elsődleges mennyiség'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='primary_quote_item_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Elsődleges tétel azonosító'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='primary_unit',
            field=models.CharField(default='db', max_length=20, verbose_name='Elsődleges egység'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='primary_vat_rate',
            field=models.DecimalField(decimal_places=2, default=27.0, max_digits=5, verbose_name='Elsődleges ÁFA %'),
        ),
    ]
