# Generated by Django 4.2.7 on 2026-06-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0067_rfq_first_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitemattachment',
            name='is_manufacturing_file',
            field=models.BooleanField(default=False, verbose_name='Gyártási file'),
        ),
    ]
