# Generated by Django 4.2.7 on 2026-06-24 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0068_quoterequestitemattachment_is_manufacturing_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestattachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Törölve (soft)'),
        ),
        migrations.AddField(
            model_name='quoterequestattachment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soft_deleted_quote_request_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoterequestitemattachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Törölve (soft)'),
        ),
        migrations.AddField(
            model_name='quoterequestitemattachment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soft_deleted_quote_request_item_attachments', to=settings.AUTH_USER_MODEL),
        ),
    ]
