# Generated by Django 4.2.7 on 2026-06-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0069_soft_delete_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='quote_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='sales.quoterequest', verbose_name='Árajánlat'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='rfq_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.quoterequestitem', verbose_name='RFQ Tétel'),
        ),
    ]
