# Generated by Django 4.2.7 on 2026-06-26 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0070_worklog_quote_request_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynoteitem',
            name='quote_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_items', to='sales.quoterequestitem', verbose_name='Ajánlat tétel'),
        ),
        migrations.AlterField(
            model_name='deliverynoteitem',
            name='customer_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_items', to='sales.customerorderitem', verbose_name='Megrendelés tétel'),
        ),
    ]
