# Generated by Django 4.2.7 on 2025-09-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Város'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_country',
            field=models.CharField(default='Magyarország', max_length=100, verbose_name='Ország'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_generic',
            field=models.TextField(blank=True, null=True, verbose_name='Cím'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_house_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Házszám'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Irányítószám'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_street_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Közterület neve'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address_street_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Közterület típusa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Születés ideje'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Születési keresztnév'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Születési vezetéknév'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Születés helye'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Férfi'), ('female', 'Nő')], max_length=10, null=True, verbose_name='Nem'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bruttó fizetés'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Anyja keresztneve'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Anyja vezetékneve'),
        ),
        migrations.AddField(
            model_name='employee',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nettó fizetés'),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Jelszó'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permission_level',
            field=models.CharField(choices=[('basic', 'Alapvető'), ('manager', 'Menedzser'), ('admin', 'Adminisztrátor'), ('superuser', 'Szuper felhasználó')], default='basic', max_length=20, verbose_name='Jogosultság szint'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Adószám'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tb_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TB szám'),
        ),
    ]
