# Generated by Django 4.2.7 on 2025-09-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_employee_salary_employee_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefonszám'),
        ),
    ]
