# Generated by Django 4.2.7 on 2025-09-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_employee_hire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='employees', to='hr.department'),
        ),
    ]
