# Generated by Django 4.2.7 on 2025-09-07 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0006_remove_employee_department_employee_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
