# Generated by Django 4.2.7 on 2025-09-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_remove_attendance_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__last_name', 'user__first_name', 'employee_id']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['title', 'department__name']},
        ),
    ]
