# Generated by Django 4.2.7 on 2025-12-29 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_project_profit_project_profit_margin_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0008_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_description', models.TextField(verbose_name='Feladat leírása')),
                ('start_time', models.DateTimeField(verbose_name='Kezdés időpontja')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Befejezés időpontja')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Időtartam (óra)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Megjegyzések')),
                ('is_billable', models.BooleanField(default=True, verbose_name='Számlázható')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='hr.employee', verbose_name='Alkalmazott')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='manufacturing.project', verbose_name='Projekt')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='manufacturing.workorder', verbose_name='Munkalap')),
            ],
            options={
                'db_table': 'time_logs',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['employee', 'start_time'], name='time_logs_employe_971ad2_idx'), models.Index(fields=['project', 'start_time'], name='time_logs_project_1353ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=100, verbose_name='Szerep')),
                ('participation_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Részesedési arány (%)')),
                ('start_date', models.DateField(verbose_name='Kezdés dátuma')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Befejezés dátuma')),
                ('contribution_description', models.TextField(blank=True, null=True, verbose_name='Hozzájárulás leírása')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to='hr.employee', verbose_name='Alkalmazott')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='manufacturing.project', verbose_name='Projekt')),
            ],
            options={
                'db_table': 'project_participations',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee', 'project'], name='project_par_employe_9699fc_idx')],
                'unique_together': {('employee', 'project', 'role')},
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_time', models.DateTimeField(verbose_name='Belépés időpontja')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Kilépés időpontja')),
                ('location', models.CharField(default='Főiroda', max_length=100, verbose_name='Helyszín')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Időtartam (óra)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Megjegyzések')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='hr.employee', verbose_name='Alkalmazott')),
            ],
            options={
                'db_table': 'access_logs',
                'ordering': ['-check_in_time'],
                'indexes': [models.Index(fields=['employee', 'check_in_time'], name='access_logs_employe_0fc11c_idx')],
            },
        ),
    ]
