# Generated by Django 4.2.7 on 2025-12-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_timelog_projectparticipation_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=8.0, max_digits=4, null=True, verbose_name='Napi munkaóra'),
        ),
        migrations.AddField(
            model_name='employee',
            name='net_monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Nettó havi bér'),
        ),
        migrations.AddField(
            model_name='employee',
            name='overhead_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Rezsi órabér'),
        ),
    ]
