# Generated by Django 4.2.7 on 2025-12-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_employee_daily_work_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='net_monthly_salary',
            new_name='net_hourly_rate',
        ),
        migrations.AlterField(
            model_name='employee',
            name='net_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Nettó órabér'),
        ),
    ]
