# Generated by Django 4.2.7 on 2026-01-01 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0011_rename_net_monthly_salary_to_net_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Eszköz név')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='Eszköz azonosító')),
                ('device_ip', models.GenericIPAddressField(verbose_name='IP cím')),
                ('device_port', models.IntegerField(default=8001, verbose_name='Port')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Helyszín')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Leírás')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beléptető eszköz konfiguráció',
                'verbose_name_plural': 'Beléptető eszköz konfigurációk',
                'db_table': 'access_control_configs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccessCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_type', models.CharField(help_text='face, fingerprint, card, password', max_length=50, verbose_name='Azonosító típus')),
                ('credential_data', models.TextField(blank=True, null=True, verbose_name='Azonosító adat')),
                ('function', models.CharField(choices=[('check_in', 'Belépés'), ('check_out', 'Kilépés'), ('door_access', 'Ajtó nyitás')], default='check_in', max_length=50, verbose_name='Funkció')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_credentials', to='hr.accesscontrolconfig', verbose_name='Eszköz')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_credentials', to='hr.employee', verbose_name='Alkalmazott')),
            ],
            options={
                'verbose_name': 'Beléptetőeszköz hozzáférés',
                'verbose_name_plural': 'Beléptetőeszköz hozzáférések',
                'db_table': 'employee_access_credentials',
                'ordering': ['employee', 'device_config'],
            },
        ),
    ]
