# Generated by Django 4.2.7 on 2026-01-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_accesscontrolconfig_employeeaccesscredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrolconfig',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
        migrations.AddField(
            model_name='accesscontrolconfig',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Utolsó csatlakozás'),
        ),
    ]
