# Generated by Django 4.2.7 on 2026-01-02 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0013_accesscontrolconfig_is_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
        migrations.AddField(
            model_name='department',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
