# Generated by Django 4.2.7 on 2026-01-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_remove_department_manager_department_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
