# Generated by Django 4.2.7 on 2026-01-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_resource_choices_to_permission'),
        ('hr', '0015_remove_employee_password_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='departments', to='core.role'),
        ),
    ]
