# Generated by Django 4.2.7 on 2026-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_attendancekioskconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancekioskconfig',
            name='kiosk_mode',
            field=models.CharField(choices=[('phone_qr', 'Mobil QR (Kioszk olvas)'), ('kiosk_qr', 'Kioszk QR (Mobil olvas)')], default='phone_qr', max_length=20, verbose_name='Működési mód'),
        ),
    ]
