# Generated by Django 4.2.7 on 2026-01-19 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_attendancekioskconfig_kiosk_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='break_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
