# Generated by Django 4.2.7 on 2026-01-20 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0019_alter_attendance_break_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=64, unique=True, verbose_name='Eszköz Azonosító')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eszköz Neve')),
                ('status', models.CharField(choices=[('pending', 'Függőben'), ('approved', 'Engedélyezve'), ('blocked', 'Letiltva')], default='pending', max_length=20, verbose_name='Státusz')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Utolsó aktivitás')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kiosk Eszköz',
                'verbose_name_plural': 'Kiosk Eszközök',
                'db_table': 'hr_kiosk_devices',
                'ordering': ['-status', '-last_seen'],
            },
        ),
    ]
