# Generated by Django 4.2.7 on 2026-01-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_kioskdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskdevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Cím'),
        ),
    ]
