# Generated by Django 4.2.7 on 2026-01-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_kioskdevice_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='inactivity_timeout',
            field=models.IntegerField(default=60, verbose_name='Inaktivitási időkorlát (perc)'),
        ),
    ]
