# Generated by Django 4.2.7 on 2026-01-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_department_inactivity_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
