# Generated by Django 4.2.7 on 2026-02-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_zone'),
        ('hr', '0023_attendance_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskdevice',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='kiosk_devices', to='core.zone', verbose_name='Zónák'),
        ),
    ]
