# Generated by Django 4.2.7 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_kioskdevice_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='email_domain',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='E-mail domain'),
        ),
        migrations.AddField(
            model_name='department',
            name='sort_order',
            field=models.IntegerField(default=100, verbose_name='Sorrend'),
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'db_table': 'departments', 'ordering': ['sort_order', 'name']},
        ),
    ]
