# Generated by Django 4.2.7 on 2026-02-16 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0025_department_email_domain_and_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Feladat neve')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Leírás')),
                ('schedule_type', models.CharField(choices=[('time', 'Idő alapú'), ('count', 'Darab alapú'), ('time_and_count', 'Idő és darab alapú')], default='time', max_length=20, verbose_name='Mikor? - Ütemezés típusa')),
                ('frequency_type', models.CharField(choices=[('daily', 'Napi'), ('weekly', 'Heti'), ('login', 'Belépés után')], default='login', max_length=20, verbose_name='Mikor? - Gyakoriság')),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Intervallum (perc)')),
                ('required_count', models.PositiveIntegerField(default=1, verbose_name='Elvárt darabszám')),
                ('days_of_week', models.JSONField(blank=True, default=list, verbose_name='Napok (0=Hétfő ... 6=Vasárnap)')),
                ('flexibility_minutes', models.PositiveIntegerField(default=0, verbose_name='Rugalmasság (perc)')),
                ('target_level', models.CharField(choices=[('person', 'Személy szintű'), ('department', 'Osztály szintű')], default='person', max_length=20, verbose_name='Személy vagy Osztály szintű')),
                ('qr_code', models.CharField(blank=True, default='', max_length=255, verbose_name='QR kód')),
                ('qr_required', models.BooleanField(default=False, verbose_name='QR kód szükséges')),
                ('kiosk_required', models.BooleanField(default=False, verbose_name='KIOSK szükséges')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_configurations', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='task_configurations', to='hr.department', verbose_name='Kinek szól? - Osztályok')),
                ('employees', models.ManyToManyField(blank=True, related_name='task_configurations', to='hr.employee', verbose_name='Kinek szól? - Alkalmazottak')),
            ],
            options={
                'db_table': 'hr_task_configurations',
                'ordering': ['name'],
            },
        ),
    ]
