# Generated by Django 4.2.7 on 2026-02-16 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0026_taskconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Folyamatban'), ('paused', 'Szüneteltetve'), ('completed', 'Befejezve')], default='in_progress', max_length=20, verbose_name='Státusz')),
                ('started_at', models.DateTimeField(verbose_name='Kezdés')),
                ('last_resumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Utoljára folytatva')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Szüneteltetve')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Befejezve')),
                ('total_duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Összes idő (másodperc)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Munkavégzés leírása')),
                ('period_key', models.CharField(db_index=True, max_length=64, verbose_name='Ütemezési periódus kulcs')),
                ('qr_verified_code', models.CharField(blank=True, default='', max_length=255, verbose_name='Igazolt QR kód')),
                ('kiosk_verified', models.BooleanField(default=False, verbose_name='KIOSK igazolva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_task_executions', to=settings.AUTH_USER_MODEL, verbose_name='Befejezte')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='hr.employee', verbose_name='Alkalmazott')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_task_executions', to=settings.AUTH_USER_MODEL, verbose_name='Elindította')),
                ('task_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='hr.taskconfiguration', verbose_name='Feladat konfiguráció')),
            ],
            options={
                'db_table': 'hr_task_executions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='hr_task_exe_employe_7b77b1_idx'), models.Index(fields=['task_configuration', 'period_key'], name='hr_task_exe_task_co_6821c2_idx'), models.Index(fields=['completed_at'], name='hr_task_exe_complet_f24c3d_idx')],
            },
        ),
    ]
