# Generated by Django 4.2.7 on 2026-02-16 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_taskexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfiguration',
            name='due_day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Hónap napjáig'),
        ),
        migrations.AlterField(
            model_name='taskconfiguration',
            name='frequency_type',
            field=models.CharField(choices=[('daily', 'Napi'), ('weekly', 'Heti'), ('monthly', 'Havi'), ('login', 'Belépés után')], default='login', max_length=20, verbose_name='Mikor? - Gyakoriság'),
        ),
    ]
