# Generated by Django 4.2.7 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_taskconfiguration_due_day_of_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskconfiguration',
            name='frequency_type',
            field=models.CharField(
                choices=[
                    ('once', 'Egyszeri'),
                    ('daily', 'Napi'),
                    ('weekly', 'Heti'),
                    ('monthly', 'Havi'),
                    ('yearly', 'Éves'),
                    ('login', 'Belépés után'),
                ],
                default='login',
                max_length=20,
                verbose_name='Mikor? - Gyakoriság'
            ),
        ),
    ]
