# Generated by Django 4.2.7 on 2026-02-17 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_alter_taskconfiguration_frequency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskconfiguration',
            name='due_month_of_year',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)],
                verbose_name='Év hónapja',
            ),
        ),
    ]
