# Generated by Django 4.2.7 on 2026-03-15 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0014_company_external_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Vázlat'), ('pending', 'Függőben'), ('confirmed', 'Visszaigazolva'), ('in_print', 'Nyomtatásban'), ('done', 'Kész'), ('cancelled', 'Törölve')], default='draft', max_length=20, verbose_name='Státusz')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_orders', to='crm.company', verbose_name='Cég')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_orders', to='crm.contact', verbose_name='Kapcsolattartó')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_orders', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozó')),
            ],
            options={
                'verbose_name': 'Nyomtatási megrendelés',
                'verbose_name_plural': 'Nyomtatási megrendelések',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_cost_per_m2', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Papír ár (HUF/m²)')),
                ('print_color_cost', models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='Színes nyomtatás (HUF/lap/oldal)')),
                ('print_bw_cost', models.DecimalField(decimal_places=2, default=20, max_digits=10, verbose_name='F-F nyomtatás (HUF/lap/oldal)')),
                ('print_color_white_cost', models.DecimalField(decimal_places=2, default=80, max_digits=10, verbose_name='Színes+Fehér nyomtatás (HUF/lap/oldal)')),
                ('cutting_cost', models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='Vágási munkadíj (HUF/munka)')),
                ('folding_cost_per_fold', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Hajtás díj (HUF/hajtáspont)')),
                ('margin_pct', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Fedezet (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Árazási konfiguráció',
            },
        ),
        migrations.CreateModel(
            name='PrintSizePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Szélesség (mm)')),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Magasság (mm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Méret preset',
                'verbose_name_plural': 'Méret presetek',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrintOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Nyomtatvány', max_length=200, verbose_name='Termék neve')),
                ('quantity', models.PositiveIntegerField(default=100, verbose_name='Mennyiség (db)')),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Szélesség (mm)')),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Magasság (mm)')),
                ('sides', models.CharField(choices=[('1', '1 oldalas'), ('2', '2 oldalas')], default='1', max_length=1, verbose_name='Oldalak száma')),
                ('side1_mode', models.CharField(choices=[('color', 'Színes'), ('bw', 'Fekete-fehér'), ('color_white', 'Színes + fehér'), ('none', 'Nyomatlan')], default='color', max_length=20, verbose_name='1. oldal nyomtatási mód')),
                ('side2_mode', models.CharField(choices=[('color', 'Színes'), ('bw', 'Fekete-fehér'), ('color_white', 'Színes + fehér'), ('none', 'Nyomatlan')], default='none', max_length=20, verbose_name='2. oldal nyomtatási mód')),
                ('binding', models.CharField(choices=[('cut', 'Méretre vágás'), ('fold', 'Hajtogatás')], default='cut', max_length=20, verbose_name='Kötészet')),
                ('folding_count', models.IntegerField(default=0, verbose_name='Hajtások száma')),
                ('folding_specs', models.JSONField(blank=True, default=list, verbose_name='Hajtás specifikáció')),
                ('design_json_side1', models.JSONField(blank=True, null=True, verbose_name='Tervezés 1. oldal')),
                ('design_json_side2', models.JSONField(blank=True, null=True, verbose_name='Tervezés 2. oldal')),
                ('artwork_side1', models.FileField(blank=True, null=True, upload_to='printshop/artwork/', verbose_name='Artwork 1. oldal')),
                ('artwork_side2', models.FileField(blank=True, null=True, upload_to='printshop/artwork/', verbose_name='Artwork 2. oldal')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='printshop/pdf/', verbose_name='Nyomdakész PDF')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Egységár (HUF)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Végösszeg (HUF)')),
                ('price_breakdown', models.JSONField(blank=True, null=True, verbose_name='Árkalkuláció részlet')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='printshop.printorder', verbose_name='Megrendelés')),
            ],
            options={
                'verbose_name': 'Nyomtatási tétel',
                'verbose_name_plural': 'Nyomtatási tételek',
            },
        ),
    ]
