# Generated by Django 4.2.7 on 2026-03-15 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printshop', '0001_initial_printshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorderitem',
            name='editor_locked',
            field=models.BooleanField(default=False, verbose_name='Szerkesztő zárolva'),
        ),
        migrations.AddField(
            model_name='printorderitem',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zárolás időpontja'),
        ),
        migrations.AddField(
            model_name='printorderitem',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_print_items', to=settings.AUTH_USER_MODEL, verbose_name='Zárolta'),
        ),
        migrations.AddField(
            model_name='printorderitem',
            name='preview_locked',
            field=models.BooleanField(default=False, verbose_name='Preview zárolva'),
        ),
    ]
