# Generated by Django 4.2.7 on 2026-03-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printshop', '0002_lock_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alapanyag',
                'verbose_name_plural': 'Alapanyagok',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='printorderitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='printshop.printmaterial', verbose_name='Alapanyag'),
        ),
    ]
