# Generated by Django 4.2.7 on 2026-04-01 21:39

import apps.printshop.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printshop', '0005_shared_print_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kategória neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sablon kategória',
                'verbose_name_plural': 'Sablon kategóriák',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sablon neve')),
                ('file', models.FileField(upload_to=apps.printshop.models.template_upload_path, verbose_name='Fájl (PDF/SVG)')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('svg', 'SVG')], max_length=10, verbose_name='Fájl típus')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='printshop/templates/thumbnails/', verbose_name='Előnézeti kép')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='printshop.printtemplatecategory', verbose_name='Kategória')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Feltöltötte')),
            ],
            options={
                'verbose_name': 'Nyomtatási sablon',
                'verbose_name_plural': 'Nyomtatási sablonok',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
