# Generated by Django 4.2.7 on 2026-04-21 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printshop', '0006_print_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedprintpreview',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Megosztás lejárati ideje'),
        ),
        migrations.CreateModel(
            name='SharedPrintPreviewFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mappa neve')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_print_preview_folders', to=settings.AUTH_USER_MODEL, verbose_name='Tulajdonos')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='printshop.sharedprintpreviewfolder', verbose_name='Szülő mappa')),
            ],
            options={
                'verbose_name': 'Tárhely mappa',
                'verbose_name_plural': 'Tárhely mappák',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sharedprintpreview',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previews', to='printshop.sharedprintpreviewfolder', verbose_name='Mappa'),
        ),
    ]
