# Generated by Django 4.2.7 on 2026-04-21 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printshop', '0007_sharedprintpreview_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPrintPreviewVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Verziószám')),
                ('pdf', models.FileField(upload_to='printshop/shared_preview/versions/', verbose_name='Verzió PDF')),
                ('annotations', models.JSONField(blank=True, default=list, verbose_name='Kommentek snapshot')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Verzió megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_print_preview_versions', to=settings.AUTH_USER_MODEL, verbose_name='Készítő')),
                ('preview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='printshop.sharedprintpreview', verbose_name='Preview')),
            ],
            options={
                'verbose_name': 'Preview verzió',
                'verbose_name_plural': 'Preview verziók',
                'ordering': ['-version_number'],
                'unique_together': {('preview', 'version_number')},
            },
        ),
    ]
