# Generated by Django 4.2.7 on 2026-05-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printshop', '0008_sharedprintpreviewversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Gép neve')),
                ('tech_type', models.CharField(choices=[('uv_flatbed', 'UV táblás (flatbed)'), ('uv_roll', 'UV tekercses (roll)'), ('digital_sheet', 'Íves digitális'), ('screen', 'Szita'), ('pad', 'Tampon'), ('other', 'Egyéb')], max_length=30, verbose_name='Technológia típus')),
                ('max_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Max. szélesség (mm)')),
                ('max_height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Max. magasság (mm)')),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=0, help_text='Energia + amortizáció + bér összesen', max_digits=10, verbose_name='Rezsi (HUF/óra)')),
                ('setup_time_min', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Beállítási idő (perc)')),
                ('print_cost_per_m2', models.DecimalField(decimal_places=2, default=0, help_text='Tinta + rezsi összesen m²-enként', max_digits=10, verbose_name='Nyomtatási ár (HUF/m²)')),
                ('speed_m2_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sebesség (m²/óra)')),
                ('click_cost_color', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Klikkdíj színes (HUF/lap)')),
                ('click_cost_bw', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Klikkdíj F/F (HUF/lap)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gép',
                'verbose_name_plural': 'Gépek',
                'ordering': ['tech_type', 'name'],
            },
        ),
    ]
