# Generated by Django 4.2.7 on 2026-05-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printshop', '0009_machine_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name'], 'verbose_name': 'Gép', 'verbose_name_plural': 'Gépek'},
        ),
        migrations.RemoveField(
            model_name='machine',
            name='click_cost_bw',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='click_cost_color',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='speed_m2_per_hour',
        ),
        migrations.AddField(
            model_name='machine',
            name='note',
            field=models.TextField(blank=True, verbose_name='Megjegyzés'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hourly_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Óradíj'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='max_height_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Max magasság (mm)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='max_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Max szélesség (mm)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='print_cost_per_m2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Nyomtatási költség / m²'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='tech_type',
            field=models.CharField(choices=[('uv_flat', 'UV Flatbed'), ('uv_roll', 'UV Tekercses'), ('digital_sheet', 'Digitális ívnyomtatás'), ('digital_roll', 'Digitális tekercs'), ('offset', 'Ofszet'), ('other', 'Egyéb')], default='uv_flat', max_length=30, verbose_name='Technológia'),
        ),
    ]
