# Generated by Django 4.2.7 on 2025-09-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_company_company_type'),
        ('core', '0006_alter_emailserverconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Külső rendszer azonosító', max_length=100, unique=True)),
                ('number', models.CharField(db_index=True, max_length=50, verbose_name='Számlaszám')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Keltezés')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Esedékesség')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fizetés dátuma')),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Nettó összesen')),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ÁFA összesen')),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bruttó összesen')),
                ('status', models.CharField(default='issued', max_length=50, verbose_name='Státusz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='Pénznem')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.company', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Számla',
                'verbose_name_plural': 'Számlák',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Külső rendszer azonosító', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Összeg')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Dátum')),
                ('method', models.CharField(blank=True, default='', max_length=50, verbose_name='Mód')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='Pénznem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice', verbose_name='Számla')),
            ],
            options={
                'verbose_name': 'Kifizetés',
                'verbose_name_plural': 'Kifizetések',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(default=1, verbose_name='Sorszám')),
                ('description', models.CharField(max_length=255, verbose_name='Megnevezés')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Mennyiség')),
                ('unit', models.CharField(default='db', max_length=20, verbose_name='Egység')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Egységár (nettó)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=27, max_digits=5, verbose_name='ÁFA %')),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Nettó összesen')),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ÁFA összesen')),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bruttó összesen')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice', verbose_name='Számla')),
            ],
            options={
                'verbose_name': 'Számlatétel',
                'verbose_name_plural': 'Számlatételek',
            },
        ),
    ]
