# Generated by Django 4.2.7 on 2026-02-14 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_invoice_partner_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kassza neve')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Kassza helye')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Kezdő egyenleg')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jelenlegi egyenleg')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_registers', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Pénznem')),
            ],
            options={
                'verbose_name': 'Kassza',
                'verbose_name_plural': 'Kasszák',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashTransactionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Megnevezés')),
                ('is_deposit', models.BooleanField(default=True, verbose_name='Betét művelet')),
                ('is_withdrawal', models.BooleanField(default=True, verbose_name='Kivét művelet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('order', models.IntegerField(default=0, verbose_name='Sorrend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kassza művelet ok',
                'verbose_name_plural': 'Kassza művelet okok',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashRegisterTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Összeg')),
                ('note', models.TextField(blank=True, default='', verbose_name='Megjegyzés')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Egyenleg előtte')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Egyenleg utána')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Időpont')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.cashregister', verbose_name='Kassza')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Alkalmazott')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.cashtransactionreason', verbose_name='Művelet oka')),
                ('target_cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='finance.cashregister', verbose_name='Cél kassza')),
            ],
            options={
                'verbose_name': 'Kassza tranzakció',
                'verbose_name_plural': 'Kassza tranzakciók',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CashRegisterEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_deposit', models.BooleanField(default=True, verbose_name='Betét jog')),
                ('can_withdraw', models.BooleanField(default=True, verbose_name='Kivét jog')),
                ('can_view', models.BooleanField(default=True, verbose_name='Megtekintés jog')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_permissions', to='finance.cashregister', verbose_name='Kassza')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_register_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Alkalmazott')),
            ],
            options={
                'verbose_name': 'Kassza alkalmazott',
                'verbose_name_plural': 'Kassza alkalmazottak',
                'unique_together': {('cash_register', 'employee')},
            },
        ),
    ]
