# Generated by Django 4.2.7 on 2026-02-14 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_cashregister_cashtransactionreason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='email_notify_on_deposit',
            field=models.BooleanField(default=False, verbose_name='E-mail értesítés betétről'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='email_notify_on_withdrawal',
            field=models.BooleanField(default=False, verbose_name='E-mail értesítés kivétről'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='notify_users',
            field=models.ManyToManyField(blank=True, related_name='cash_register_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Értesítendő felhasználók'),
        ),
    ]
