# Generated by Django 4.2.7 on 2026-02-14 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_kioskdevice_zones'),
        ('finance', '0004_cashregister_email_notify_on_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_registers', to='hr.employee', verbose_name='Létrehozta'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='notify_users',
            field=models.ManyToManyField(blank=True, related_name='cash_register_notifications', to='hr.employee', verbose_name='Értesítendő alkalmazottak'),
        ),
        migrations.AlterField(
            model_name='cashregisteremployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_register_permissions', to='hr.employee', verbose_name='Alkalmazott'),
        ),
        migrations.AlterField(
            model_name='cashregistertransaction',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='hr.employee', verbose_name='Alkalmazott'),
        ),
    ]
