# Generated by Django 4.2.7 on 2026-02-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_kioskdevice_zones'),
        ('finance', '0005_alter_cashregister_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='transaction_view_employees',
            field=models.ManyToManyField(blank=True, related_name='cash_register_transaction_view', to='hr.employee', verbose_name='Forgalmi lista jogosult alkalmazottak'),
        ),
    ]
