# Generated by Django 4.2.7 on 2026-09-23 06:42

import apps.matrixdisplay.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('serial', models.CharField(blank=True, default='', max_length=60, verbose_name='Sorozatszám')),
                ('kind', models.CharField(choices=[('full_color', 'Teljes színes (HDPlayer)'), ('mono', 'Egyszínű (HD2020)')], default='full_color', max_length=20, verbose_name='Típus')),
                ('protocol', models.CharField(choices=[('huidu_sdk2', 'Huidu SDK2 TCP (10001)'), ('huidu_gen6', 'Huidu Gen6 (HD2020 szöveg)'), ('manual', 'Csak nyilvántartás (kézi küldés)')], default='huidu_sdk2', max_length=20, verbose_name='Protokoll')),
                ('host', models.CharField(blank=True, default='', max_length=100, verbose_name='IP cím')),
                ('port', models.PositiveIntegerField(default=10001, verbose_name='Port')),
                ('mac', models.CharField(blank=True, default='', max_length=20, verbose_name='MAC')),
                ('gateway', models.CharField(blank=True, default='', max_length=20, verbose_name='Átjáró')),
                ('subnet', models.CharField(blank=True, default='', max_length=20, verbose_name='Alhálózati maszk')),
                ('wifi_ssid', models.CharField(blank=True, default='', max_length=64, verbose_name='WiFi SSID')),
                ('wifi_password', models.CharField(blank=True, default='', max_length=64, verbose_name='WiFi jelszó')),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Szélesség (px)')),
                ('screen_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Magasság (px)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Megjegyzés')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Utoljára elérhető')),
                ('last_status', models.CharField(blank=True, default='', max_length=200, verbose_name='Utolsó státusz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matrix kijelző',
                'verbose_name_plural': 'Matrix kijelzők',
                'db_table': 'matrix_displays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MatrixMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Név')),
                ('file', models.FileField(upload_to=apps.matrixdisplay.models.media_upload_path, verbose_name='Fájl')),
                ('kind', models.CharField(choices=[('image', 'Kép'), ('video', 'Videó'), ('audio', 'Hang'), ('other', 'Egyéb')], default='image', max_length=10, verbose_name='Típus')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Méret (bájt)')),
                ('md5', models.CharField(blank=True, default='', max_length=32, verbose_name='MD5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kijelző média',
                'verbose_name_plural': 'Kijelző médiumok',
                'db_table': 'matrix_media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatrixProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Beállítás')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Utoljára elküldve')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='matrixdisplay.matrixdisplay', verbose_name='Kijelző')),
            ],
            options={
                'verbose_name': 'Kijelző program',
                'verbose_name_plural': 'Kijelző programok',
                'db_table': 'matrix_programs',
                'ordering': ['display', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MatrixSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40, verbose_name='Művelet')),
                ('status', models.CharField(max_length=20, verbose_name='Állapot')),
                ('message', models.TextField(blank=True, default='', verbose_name='Üzenet')),
                ('request', models.TextField(blank=True, default='', verbose_name='Kérés')),
                ('response', models.TextField(blank=True, default='', verbose_name='Válasz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='matrixdisplay.matrixdisplay', verbose_name='Kijelző')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrixdisplay.matrixprogram', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Kijelző küldési napló',
                'verbose_name_plural': 'Kijelző küldési naplók',
                'db_table': 'matrix_send_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
