# Generated by Django 4.2.7 on 2026-09-21 20:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0073_postransaction_storno_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0016_company_discount_group'),
        ('warehouse', '0041_alter_materialcostitem_calculation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=30, unique=True, verbose_name='Kártyaszám')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Egyenleg (Ft)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_card', to='crm.company', verbose_name='Ügyfél')),
            ],
            options={
                'verbose_name': 'Üzemanyagkártya',
                'verbose_name_plural': 'Üzemanyagkártyák',
                'db_table': 'loyalty_fuel_cards',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_100_ft', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6, verbose_name='Pont / 100 Ft vásárlás után')),
                ('welcome_points', models.IntegerField(default=0, verbose_name='Üdvözlő pont regisztrációkor')),
                ('qr_token_ttl_seconds', models.PositiveIntegerField(default=120, verbose_name='QR token élettartama (s)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hűségprogram beállítás',
                'verbose_name_plural': 'Hűségprogram beállítások',
                'db_table': 'loyalty_config',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPointEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Pont (±)')),
                ('reason', models.CharField(max_length=30, verbose_name='Ok')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Rögzítette')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_entries', to='crm.company', verbose_name='Ügyfél')),
                ('pos_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_entries', to='sales.postransaction', verbose_name='POS bizonylat')),
            ],
            options={
                'verbose_name': 'Hűsegpont bejegyzés',
                'verbose_name_plural': 'Hűségpont bejegyzések',
                'db_table': 'loyalty_point_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Összeg (±)')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.fuelcard', verbose_name='Kártya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Rögzítette')),
                ('pos_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_card_transactions', to='sales.postransaction', verbose_name='POS bizonylat')),
            ],
            options={
                'verbose_name': 'Üzemanyagkártya tranzakció',
                'verbose_name_plural': 'Üzemanyagkártya tranzakciók',
                'db_table': 'loyalty_fuel_card_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kedvezmény (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='crm.company', verbose_name='Ügyfél')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_discounts', to='warehouse.material', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Ügyfél termékkedvezmény',
                'verbose_name_plural': 'Ügyfél termékkedvezmények',
                'db_table': 'loyalty_customer_product_discounts',
                'unique_together': {('customer', 'material')},
            },
        ),
    ]
