# Generated by Django 4.2.7 on 2026-02-16 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0021_material_vat_type_id'),
        ('hr', '0025_department_email_domain_and_sort_order'),
        ('finance', '0007_cashregister_is_pos_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='POS név')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Helye')),
                ('hepg', models.CharField(blank=True, default='', max_length=120, verbose_name='HePG')),
                ('show_all_categories', models.BooleanField(default=True, verbose_name='Összes termék kategória')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_employees', models.ManyToManyField(blank=True, related_name='pos_terminals', to='hr.employee', verbose_name='Jogosult alkalmazottak')),
                ('cash_register', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_terminal', to='finance.cashregister', verbose_name='Kassza')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos_terminals', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
                ('material_groups', models.ManyToManyField(blank=True, related_name='pos_terminals', to='warehouse.materialgroup', verbose_name='Termék kategóriák')),
            ],
            options={
                'db_table': 'pos_terminals',
                'ordering': ['name'],
            },
        ),
    ]
