# Generated by Django 4.2.7 on 2026-09-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0035_materialbarcode'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterminal',
            name='warehouses',
            field=models.ManyToManyField(blank=True, help_text='Ha üres, minden raktárban lévő termék megjelenik. Ha meg van adva, csak az itt felsorolt raktár(ak)ban lévő készlettel rendelkező termékek jelennek meg.', related_name='pos_terminals', to='warehouse.warehouse', verbose_name='Raktárak'),
        ),
    ]
