# Generated by Django 4.2.7 on 2026-09-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
        ('pos', '0002_posterminal_warehouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterminal',
            name='fuel_module_enabled',
            field=models.BooleanField(default=False, help_text='A POS kasszaképernyőn elérhetővé válik az üzemanyag adagolás (kútállapot, preset, kifizetés).', verbose_name='Benzinkút modul'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='fuel_pumps',
            field=models.ManyToManyField(blank=True, help_text='Ha üres, az összes aktív kútfej elérhető ezen a POS-on.', related_name='pos_terminals', to='fuel.fuelpump', verbose_name='Kútfejek'),
        ),
    ]
