# Generated by Django 4.2.7 on 2025-09-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
