# Generated by Django 4.2.7 on 2025-09-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_email_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailserverconfig',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'Email szerver beállítás', 'verbose_name_plural': 'Email szerver beállítások'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['name'], 'verbose_name': 'E-mail sablon', 'verbose_name_plural': 'E-mail sablonok'},
        ),
        migrations.AlterModelOptions(
            name='signaturetemplate',
            options={'ordering': ['name'], 'verbose_name': 'Aláírás sablon', 'verbose_name_plural': 'Aláírás sablonok'},
        ),
        migrations.AlterField(
            model_name='emailserverconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signaturetemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
