# Generated by Django 4.2.7 on 2025-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_emailserverconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixinvoiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Alapértelmezett', max_length=100)),
                ('base_url', models.URLField(default='https://api.pixinvoice.hu')),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PIXINVOICE beállítás',
                'verbose_name_plural': 'PIXINVOICE beállítások',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
