# Generated by Django 4.2.7 on 2025-09-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pixinvoiceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixinvoiceconfig',
            name='company_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pixinvoiceconfig',
            name='base_url',
            field=models.URLField(default='http://localhost:4001/api/'),
        ),
    ]
