# Generated by Django 4.2.7 on 2026-01-03 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_pixinvoiceconfig_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Konfiguráció neve')),
                ('interval', models.CharField(choices=[('daily', 'Napi'), ('weekly', 'Heti'), ('monthly', 'Havi')], max_length=10, verbose_name='Mentési gyakoriság')),
                ('retention_days', models.IntegerField(help_text='Ennyi nap után felülírhatók a régi backup fájlok', verbose_name='Megőrzési idő (nap)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('last_backup', models.DateTimeField(blank=True, null=True, verbose_name='Utolsó mentés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
            ],
            options={
                'verbose_name': 'Backup konfiguráció',
                'verbose_name_plural': 'Backup konfigurációk',
                'db_table': 'backup_configurations',
                'ordering': ['interval'],
            },
        ),
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Fájlnév')),
                ('filepath', models.CharField(max_length=500, verbose_name='Fájl útvonal')),
                ('file_size', models.BigIntegerField(verbose_name='Fájlméret (byte)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Manuális mentés')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='core.backupconfiguration', verbose_name='Konfiguráció')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
            ],
            options={
                'verbose_name': 'Backup fájl',
                'verbose_name_plural': 'Backup fájlok',
                'db_table': 'backup_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
