# Generated by Django 4.2.7 on 2026-01-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='default_cc',
            field=models.TextField(blank=True, default='', help_text='Alapértelmezett CC címzettek (vesszővel elválasztva)'),
        ),
    ]
