# Generated by Django 4.2.7 on 2026-01-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_default_cc_to_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='default_reply_to',
            field=models.EmailField(blank=True, default='', help_text='Alapértelmezett Reply-To cím', max_length=254),
        ),
    ]
