# Generated by Django 4.2.7 on 2026-01-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_default_reply_to_to_email_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Cég', 'verbose_name_plural': 'Cégek'},
        ),
        migrations.AddField(
            model_name='company',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Alapértelmezett'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(verbose_name='Cím'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='Logó'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Cégnév'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Adószám'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Weboldal'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, verbose_name='Bankszámlaszám')),
                ('bank_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Bank neve')),
                ('swift', models.CharField(blank=True, default='', max_length=11, verbose_name='SWIFT/BIC kód')),
                ('iban', models.CharField(blank=True, default='', max_length=34, verbose_name='IBAN')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Elsődleges')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.company', verbose_name='Cég')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Deviza')),
            ],
            options={
                'verbose_name': 'Bankszámla',
                'verbose_name_plural': 'Bankszámlák',
                'ordering': ['-is_primary', 'currency__code'],
                'unique_together': {('company', 'account_number')},
            },
        ),
    ]
