# Generated by Django 4.2.7 on 2026-01-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_company_options_company_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='eu_tax_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='EU adószám'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon'),
        ),
    ]
