# Generated by Django 4.2.7 on 2026-01-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_company_eu_tax_number_alter_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixinvoiceconfig',
            name='default_invoice_series_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Alapértelmezett számlatömb'),
        ),
    ]
