# Generated by Django 4.2.7 on 2026-01-12 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_pixinvoiceconfig_default_invoice_series_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Szerepkör neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('is_system', models.BooleanField(default=False, verbose_name='Rendszer szerepkör')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Szerepkör',
                'verbose_name_plural': 'Szerepkörök',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Hozzárendelte')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='core.role', verbose_name='Szerepkör')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Felhasználó szerepkör',
                'verbose_name_plural': 'Felhasználó szerepkörök',
                'db_table': 'user_roles',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('hr', 'HR'), ('manufacturing', 'Gyártás'), ('sales', 'Értékesítés'), ('crm', 'CRM'), ('finance', 'Pénzügy'), ('warehouse', 'Raktár'), ('orders', 'Megrendelések'), ('pos', 'POS'), ('settings', 'Beállítások')], max_length=50, verbose_name='Modul')),
                ('action', models.CharField(choices=[('view', 'Megtekintés'), ('create', 'Létrehozás'), ('edit', 'Szerkesztés'), ('delete', 'Törlés'), ('export', 'Export'), ('manage', 'Teljes jogosultság')], max_length=20, verbose_name='Művelet')),
                ('resource', models.CharField(blank=True, max_length=100, verbose_name='Erőforrás')),
                ('allowed', models.BooleanField(default=True, verbose_name='Engedélyezett')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.role', verbose_name='Szerepkör')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Jogosultság',
                'verbose_name_plural': 'Jogosultságok',
                'db_table': 'permissions',
                'indexes': [models.Index(fields=['module', 'action'], name='permissions_module_8c66f0_idx'), models.Index(fields=['role'], name='permissions_role_id_a1bd90_idx'), models.Index(fields=['user'], name='permissions_user_id_81124e_idx')],
            },
        ),
    ]
