# Generated by Django 4.2.7 on 2026-01-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_roles_and_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(blank=True, choices=[('hr.employees', 'HR - Alkalmazottak'), ('hr.departments', 'HR - Osztályok'), ('hr.positions', 'HR - Pozíciók'), ('hr.attendance', 'HR - Jelenléti ív'), ('hr.leave_requests', 'HR - Szabadság kérelmek'), ('hr.payroll', 'HR - Bérszámfejtés'), ('manufacturing.projects', 'Gyártás - Projektek'), ('manufacturing.products', 'Gyártás - Termékek'), ('manufacturing.work_sheets', 'Gyártás - Munkalapok'), ('manufacturing.materials', 'Gyártás - Anyagok'), ('sales.rfqs', 'Értékesítés - Árajánlatok'), ('sales.quotes', 'Értékesítés - Ajánlatok'), ('sales.orders', 'Értékesítés - Megrendelések'), ('sales.leads', 'Értékesítés - Leadek'), ('sales.opportunities', 'Értékesítés - Lehetőségek'), ('crm.companies', 'CRM - Cégek'), ('crm.contacts', 'CRM - Kapcsolattartók'), ('crm.activities', 'CRM - Tevékenységek'), ('finance.invoices', 'Pénzügy - Számlák'), ('finance.payments', 'Pénzügy - Kifizetések'), ('finance.expenses', 'Pénzügy - Kiadások'), ('warehouse.materials', 'Raktár - Anyagok'), ('warehouse.inventory', 'Raktár - Készlet'), ('warehouse.movements', 'Raktár - Mozgások'), ('orders.customer_orders', 'Megrendelések - Vevői megrendelések'), ('orders.purchase_orders', 'Megrendelések - Beszerzési megrendelések'), ('pos.transactions', 'POS - Tranzakciók'), ('pos.products', 'POS - Termékek'), ('settings.users', 'Beállítások - Felhasználók'), ('settings.roles', 'Beállítások - Szerepkörök'), ('settings.company', 'Beállítások - Cégadatok'), ('settings.email', 'Beállítások - E-mail'), ('settings.integrations', 'Beállítások - Integrációk')], max_length=100, verbose_name='Almodul/Erőforrás'),
        ),
    ]
