# Generated by Django 4.2.7 on 2026-01-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_resource_choices_to_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'Megtekintés'), ('view_own', 'Saját adatok megtekintése'), ('create', 'Létrehozás'), ('edit', 'Szerkesztés'), ('delete', 'Törlés'), ('export', 'Export'), ('manage', 'Teljes jogosultság')], max_length=20, verbose_name='Művelet'),
        ),
    ]
