# Generated by Django 4.2.7 on 2026-01-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_view_own_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('used_from_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emergency_access_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
