# Generated by Django 4.2.7 on 2026-01-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_bankaccount_company_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='previous_password_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Előző jelszó hash'),
        ),
    ]
