# Generated by Django 4.2.7 on 2026-01-20 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_userpreference_previous_password_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Cím')),
                ('message', models.TextField(verbose_name='Üzenet')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Hivatkozás')),
                ('type', models.CharField(choices=[('info', 'Információ'), ('success', 'Siker'), ('warning', 'Figyelmeztetés'), ('error', 'Hiba')], default='info', max_length=20, verbose_name='Típus')),
                ('is_read', models.BooleanField(default=False, verbose_name='Olvasott')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Értesítés',
                'verbose_name_plural': 'Értesítések',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
