# Generated by Django 4.2.7 on 2026-01-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixinvoiceconfig',
            name='base_url',
            field=models.URLField(default='http://inv.pixisys.eu/api/'),
        ),
    ]
