# Generated by Django 4.2.7 on 2026-02-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_pixinvoiceconfig_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_approve_orders',
            field=models.BooleanField(default=False, verbose_name='Jóváhagyási jogkör (Rendelések)'),
        ),
    ]
