# Generated by Django 4.2.7 on 2026-02-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_role_can_approve_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='can_approve_orders',
            field=models.BooleanField(default=False, verbose_name='Jóváhagyó'),
        ),
    ]
