# Generated by Django 4.2.7 on 2026-02-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_attendance_last_activity'),
        ('core', '0028_alter_role_can_approve_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zóna neve')),
                ('zone_number', models.CharField(max_length=50, unique=True, verbose_name='Zóna szám')),
                ('note', models.TextField(blank=True, default='', verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('departments', models.ManyToManyField(blank=True, related_name='zones', to='hr.department', verbose_name='Osztályok')),
            ],
            options={
                'verbose_name': 'Zóna',
                'verbose_name_plural': 'Zónák',
                'db_table': 'zones',
                'ordering': ['zone_number'],
            },
        ),
    ]
