# Generated by Django 4.2.7 on 2026-02-13 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Időpont')),
                ('action', models.CharField(choices=[('create', 'Létrehozva'), ('update', 'Módosítva'), ('delete', 'Törölve'), ('approve', 'Jóváhagyva'), ('reject', 'Elutasítva'), ('cancel', 'Törölve/Megszakítva'), ('send', 'Elküldve'), ('complete', 'Befejezve'), ('other', 'Egyéb')], max_length=20, verbose_name='Művelet')),
                ('description', models.TextField(verbose_name='Leírás')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Objektum ID')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Változások')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP cím')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Objektum típus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Tevékenység napló',
                'verbose_name_plural': 'Tevékenység naplók',
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='activity_lo_content_edc5bf_idx'), models.Index(fields=['user', 'timestamp'], name='activity_lo_user_id_e40ffe_idx')],
            },
        ),
    ]
