# Generated by Django 4.2.7 on 2026-02-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_multisite_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='ui_preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='UI beállítások'),
        ),
        migrations.AlterField(
            model_name='publicsiteconfig',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Marketing, kalkulátorok és kliens portál egy helyen.', verbose_name='Alcím'),
        ),
    ]
