# Generated by Django 4.2.7 on 2026-03-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_ui_preferences_to_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Eszköz neve')),
                ('device_type', models.CharField(choices=[('shelly_1mini_gen3_relay', 'Shelly 1 Mini Gen3 Relay')], max_length=60, verbose_name='Típus')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Hely')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('shelly_host', models.CharField(blank=True, default='', max_length=255, verbose_name='IP / Hostnév (Shelly)')),
                ('shelly_auth_user', models.CharField(blank=True, default='', max_length=100, verbose_name='Felhasználónév (Shelly)')),
                ('shelly_auth_pass', models.CharField(blank=True, default='', max_length=255, verbose_name='Jelszó (Shelly)')),
                ('shelly_channel', models.PositiveSmallIntegerField(default=0, verbose_name='Csatorna (0=alap)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IoT eszköz',
                'verbose_name_plural': 'IoT eszközök',
                'db_table': 'iot_devices',
                'ordering': ['name'],
            },
        ),
    ]
