# Generated by Django 4.2.7 on 2026-03-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_nfc_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctag',
            name='last_counter',
            field=models.PositiveIntegerField(default=0, help_text='Visszajátszás elleni védelem — az utolsó érvényes tap számlálója.', verbose_name='Utolsó SUN számláló'),
        ),
        migrations.AddField(
            model_name='nfctag',
            name='sun_key',
            field=models.CharField(blank=True, default='', help_text='32 hex karakter (16 bájt AES-128 kulcs). Csak NTAG424-hez szükséges.', max_length=32, verbose_name='SUN AES kulcs (hex)'),
        ),
    ]
