# Generated by Django 4.2.7 on 2026-03-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_taskconfiguration_due_month_of_year'),
        ('core', '0045_nfctag_sun_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, help_text='Ha üres, minden bejelentkezett felhasználó használhatja. Ha meg van adva, csak a listában szereplő osztályok tagjai.', related_name='iot_devices', to='hr.department', verbose_name='Jogosult HR osztályok'),
        ),
    ]
