# Generated by Django 4.2.7 on 2026-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_iotdevice_allowed_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfctag',
            name='require_login',
            field=models.BooleanField(default=True, help_text='Ha ki van kapcsolva, az NFC tag bejelentkezés nélkül is aktivál (csak NTAG424 SUN kriptó szükséges). Zárolt képernyőnél is működik.', verbose_name='Bejelentkezés szükséges'),
        ),
    ]
