# Generated by Django 4.2.7 on 2026-04-27 16:38

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0047_nfctag_require_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mappa neve')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_folders', to=settings.AUTH_USER_MODEL, verbose_name='Tulajdonos')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.storagefolder', verbose_name='Szülő mappa')),
            ],
            options={
                'verbose_name': 'Tároló mappa',
                'verbose_name_plural': 'Tároló mappák',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('hr', 'HR'), ('manufacturing', 'Gyártás'), ('sales', 'Értékesítés'), ('crm', 'CRM'), ('finance', 'Pénzügy'), ('warehouse', 'Raktár'), ('orders', 'Megrendelések'), ('pos', 'POS'), ('settings', 'Beállítások'), ('printshop', 'Nyomda'), ('storage', 'Tárhely')], max_length=50, verbose_name='Modul'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(blank=True, choices=[('hr.employees', 'HR - Alkalmazottak'), ('hr.departments', 'HR - Osztályok'), ('hr.positions', 'HR - Pozíciók'), ('hr.attendance', 'HR - Jelenléti ív'), ('hr.leave_requests', 'HR - Szabadság kérelmek'), ('hr.payroll', 'HR - Bérszámfejtés'), ('manufacturing.projects', 'Gyártás - Projektek'), ('manufacturing.products', 'Gyártás - Termékek'), ('manufacturing.work_sheets', 'Gyártás - Munkalapok'), ('manufacturing.materials', 'Gyártás - Anyagok'), ('sales.rfqs', 'Értékesítés - Árajánlatok'), ('sales.quotes', 'Értékesítés - Ajánlatok'), ('sales.orders', 'Értékesítés - Megrendelések'), ('sales.leads', 'Értékesítés - Leadek'), ('sales.opportunities', 'Értékesítés - Lehetőségek'), ('crm.companies', 'CRM - Cégek'), ('crm.contacts', 'CRM - Kapcsolattartók'), ('crm.activities', 'CRM - Tevékenységek'), ('finance.invoices', 'Pénzügy - Számlák'), ('finance.payments', 'Pénzügy - Kifizetések'), ('finance.expenses', 'Pénzügy - Kiadások'), ('finance.cash_registers', 'Pénzügy - Kasszák'), ('finance.cash_transactions', 'Pénzügy - Kassza tranzakciók'), ('warehouse.materials', 'Raktár - Anyagok'), ('warehouse.inventory', 'Raktár - Készlet'), ('warehouse.movements', 'Raktár - Mozgások'), ('orders.customer_orders', 'Megrendelések - Vevői megrendelések'), ('orders.purchase_orders', 'Megrendelések - Beszerzési megrendelések'), ('pos.transactions', 'POS - Tranzakciók'), ('pos.products', 'POS - Termékek'), ('settings.users', 'Beállítások - Felhasználók'), ('settings.roles', 'Beállítások - Szerepkörök'), ('settings.company', 'Beállítások - Cégadatok'), ('settings.email', 'Beállítások - E-mail'), ('settings.integrations', 'Beállítások - Integrációk'), ('printshop.preview', 'Nyomda - Preview'), ('storage.manage', 'Tárhely - Teljes hozzáférés (admin)')], max_length=100, verbose_name='Almodul/Erőforrás'),
        ),
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Fájl neve')),
                ('file', models.FileField(upload_to=apps.core.models.storage_upload_path, verbose_name='Fájl')),
                ('size', models.BigIntegerField(default=0, verbose_name='Méret (byte)')),
                ('content_type', models.CharField(blank=True, max_length=255, verbose_name='MIME típus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='core.storagefolder', verbose_name='Mappa')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to=settings.AUTH_USER_MODEL, verbose_name='Tulajdonos')),
            ],
            options={
                'verbose_name': 'Tárolt fájl',
                'verbose_name_plural': 'Tárolt fájlok',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Törölhet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.storagefile', verbose_name='Fájl')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.storagefolder', verbose_name='Mappa')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_shared_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Megosztotta')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_shared_with_me', to=settings.AUTH_USER_MODEL, verbose_name='Megosztva ezzel')),
            ],
            options={
                'verbose_name': 'Tárhely megosztás',
                'verbose_name_plural': 'Tárhely megosztások',
                'unique_together': {('folder', 'shared_with'), ('file', 'shared_with')},
            },
        ),
    ]
