# Generated by Django 4.2.7 on 2026-05-05 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_seed_manufacturing_ordered_products_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagefile',
            name='alias_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.storagefile', verbose_name='Eredeti fájl (alias)'),
        ),
    ]
