# Generated by Django 4.2.7 on 2026-05-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_permission_module_alter_permission_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('hr', 'HR'), ('sales', 'Értékesítés'), ('manufacturing', 'Gyártás'), ('finance', 'Pénzügy'), ('crm', 'CRM'), ('orders', 'Megrendelések'), ('warehouse', 'Raktár'), ('pos', 'POS'), ('tickets', 'Jegyek'), ('site_management', 'Weboldal kezelés'), ('storage', 'Tárhely'), ('printshop', 'Nyomda'), ('settings', 'Beállítások')], max_length=50, verbose_name='Modul'),
        ),
    ]
