# Generated by Django 4.2.7 on 2026-05-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_nfctriggerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='quote_validity_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Ajánlati érvényesség (nap)'),
        ),
    ]
