# Generated by Django 4.2.7 on 2026-06-05 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0059_company_quote_validity_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSeenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=100)),
                ('record_id', models.IntegerField()),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Megtekintett rekord',
                'verbose_name_plural': 'Megtekintett rekordok',
                'unique_together': {('user', 'page_key', 'record_id')},
            },
        ),
        migrations.CreateModel(
            name='UserPageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=100)),
                ('visited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oldallátogatás',
                'verbose_name_plural': 'Oldallátogatások',
                'unique_together': {('user', 'page_key')},
            },
        ),
    ]
