# Generated by Django 4.2.7 on 2026-09-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_order_received_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientportalsession',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name='Megerősítve (QR login esetén False)'),
        ),
        migrations.AlterField(
            model_name='clientportalsession',
            name='token',
            field=models.CharField(db_index=True, default='', editable=False, max_length=255, unique=True),
        ),
    ]
