# Generated by Django 4.2.7 on 2026-09-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_portal_session_confirmed_chartoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('target_language', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fordítás cache',
                'verbose_name_plural': 'Fordítás cache',
                'indexes': [models.Index(fields=['target_language'], name='core_transl_target__21cf87_idx')],
                'unique_together': {('source_text', 'target_language')},
            },
        ),
    ]
